### ISSUE TITLE
Dashboard direct URL fails with password reset

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1005]
Seen in beta.18
Steps to recreate:
Create a new user x
Grant read permission on a dashboard to user x
In another browser session navigate to https://<your IP>/stroom/dashboard?type=Dashboard&uuid=<your dashboard UUID>
When prompted to login, login as user x
You will be prompted to change the password
Once the password has been changed the browser is redirected to `/stroom/dashboard` and an alert is shown saying something like _The dashboard UUID has not been specified_.
If you paste in the full direct url then it works fine.

The request params are getting lost during the auth redirects.

**Comment by jc064522** [comment]
Fixed elsewhere, needs testing

**Comment by jc064522** [comment]
Testing should include both the automatic redirect and the clickable link
