### ISSUE TITLE
Viz is being passed too many rows from a data table

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1007]
Have a table that results in one row (limited maxresults)

A viz driven from this table is being passed a full set of data rather than the table data.

**Comment by stroomdev10** [comment]
The table needs a setting to trim results as required.
The default should be to mimic the value in the table.

**Comment by at055612** [comment]
Some more thought is needed on this.  i.e. how do we default a value when the settings dialog field that links to the limit setting doesn't support a null value.  Thus if we have a field for maxValues in the viz settings then the user is forced to use that to control the data sent to the viz and it will take the default value defined in the viz settings.

@10 and I think the viz should get the same data the table renders, though this is complicated by the table max results value being multi level (e.g. 1000,100,10,1 etc.).  We think that it is confusing for the user if the viz is rendering a different set of data to the data in the table that they can see.  However if the viz gets the same data as the table then what do the limit values do in the viz settings?   Do they optionally override what the table is doing and if so how given they cannot be null in the dialog.
