### ISSUE TITLE
Non-editable dashboard shows 'leave site?' dialog

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1008]
Seen in v6.0-beta.18

Create a dash and grant read perms on it to a lowly user.
Open the dash via a direct url.
The save button is disabled.
Change the dash in some way, e..g. adding a column to a table.
Hit F5 to reload the page.

Browser (chrome) prompts with a dialog saving:
```
Reload Site?
Changes that you made may not be saved
```
Similar dialog is show if you try to close the browser tab.

**Comment by stroomdev66** [comment]
Probably fixed at the same time as #1322
