### ISSUE TITLE
Upload data to a feed never proceeds on latest docker image

### ISSUE THREAD

**Issue by jockey10** [gchq/stroom#102]
Hi all,

I've just pulled the latest Stroom image from Docker Hub, and having a few issues.

After re-creating the container, the feed upload (feed -> data -> upload) hangs after a file is selected and "Ok" is selected, and never proceeds.

In addition, the build version and timestamp are no longer available, instead showing the following on the welcome page:

Build Version: ${pom.version}
Build Date: ${build.timestamp}

**Steps to reproduce**

1. docker stop stroom
2. docker stop stroom-db
3. docker rm stroom
4. docker rm stroom-db
5. docker pull gchq/stroom
6. docker pull mysql:5.6
7. docker run --name stroom-db -e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_USER=stroomuser -e MYSQL_PASSWORD=stroompassword1 -e MYSQL_DATABASE=stroom -d mysql:5.6
8. docker run -p 8080:8080 --link stroom-db -v ~/.stroom.conf.d:/root/.stroom.conf.d --name=stroom -e STROOM_JDBC_DRIVER_URL="jdbc:mysql://stroom-db/stroom?useUnicode=yes&characterEncoding=UTF-8" -e STROOM_JDBC_DRIVER_USERNAME="stroomuser" -e STROOM_JDBC_DRIVER_PASSWORD="stroompassword1" gchq/stroom

**Comment by jockey10** [comment]
Hi Stroom dev team, I just tested this with the latest image off Docker Hub (5.0-beta.10), and it still won't let me proceed past the "upload data" dialogue. 

Any ideas?

**Comment by danrids** [comment]
I just pulled `gchq/stroom:latest` (5.0-beta-9) with `mysql:5.6` and the file upload issue appears to be resolved. Containers are running on Docker version 1.13.0, build 49bf474 with Ubuntu 16.04 LTS

**Comment by jc064522** [comment]
I've just tested on tag `v5.0-beta.10` and don't see this issue - other than this I used the same steps as OP. The file I tried to import is the one from the [quick-start guide](https://gchq.github.io/stroom-docs/quick-start-guide/quick-start.html), the [CSV file](https://github.com/gchq/stroom-docs/blob/master/quick-start-guide/resources/mock_stroom_data.csv). 

 `gchq/stroom` is the same as `gchq/stroom:latest`, and latest is currently `v5.0-beta.9`. I'm about to add  `v5.0-beta.10` as a tag and update `latest`. I'll post back here when that's done.

**Comment by jc064522** [comment]
I've pushed `v5.0-beta.10` and updated `latest` - if you'd like to re-test please go ahead. You'll want to pull like this: `docker pull gchq/stroom:v5.0-beta.10`. A list of the version are [here on Docker Hub](https://hub.docker.com/r/gchq/stroom/tags/). Closing this now but if you still get it I'll re-open it and we can investigate further. Thanks for the report.
