### ISSUE TITLE
SupersededOutputHelper is not initialised

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1024]
[20181213.txt](https://github.com/gchq/stroom/files/2676134/20181213.txt)

**Comment by stroomdev66** [comment]
For some reason the ReferenceDataLoad pipeline is trying to write an output stream. This isn't expected to be the case.

**Comment by stroomdev66** [comment]
The `SupersededOutputHelper` will no longer check that output is superseded for pipelines that exist outside of normal processing.

Change will be available in v6.0-beta.21 onwards
