### ISSUE TITLE
Dashboard parameters need to support spaces and quotes

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#1030]
This needs testing with dashboard links too

**Comment by GCHQ-11** [comment]
I've hit issue after issue just trying to run the system, so I'm bailing out of this ticket until I can actually start to address the functionality again

**Comment by GCHQ-11** [comment]
Finally able to test (disable auth for the win). It actually looks like dashboard parameters work very well with spaces. It seems that the equals sign is the fulcrum of the parsing

**Comment by GCHQ-11** [comment]
I used cyberchef to encode
myApp=\"silly.com\" myIp=192.17.20.204
into
myApp%3D%5C%22silly%2Ecom%5C%22%20myIp%3D192%2E17%2E20%2E204
Then pasted as value of 'params' in direct dashboard link. The parameters were parsed correctly and the query ran as expected

**Comment by GCHQ-11** [comment]
It seems that quotes need to be back slash escaped. So
