### ISSUE TITLE
Proxy aggregation does not follow symbolic links

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#1047]
If the Stroom UI is configured to read from a symbolic link which points to valid proxy acquired files, it does not follow the link and hence does not aggregate the data.

If the stroom.proxyDir is configured to point at the directory the data actually resides in, it correctly aggregates the data found there.

This is in Stroom V5.5.6.

**Comment by stroomdev66** [comment]
Hopefully fixed in v6.0-beta.30
