### ISSUE TITLE
Migration durations from custom format to ISO8601

### ISSUE THREAD

**Issue by jc064522** [gchq/stroom#1048]
Currently durations in Stroom use a format like 10d, 4w. ISO8601 specifies a standard for durations which look quite similar. Java's `Duration.parse(...)` will parse these automatically, so we could delete those methods in `stroom.util.shared.ModelStringUtil`.

We should do this all in one go because having two standards for duration in Stroom would be terribad.

**Comment by stroomdev66** [comment]
But from a user perspective aren't the ISO8601 durations a little more cumbersome, e.g. `4w` would become `P4W`?

**Comment by jc064522** [comment]
Great suggestion. We could support both formats in this fashion, transforming where necessary.

**Comment by burnalting** [comment]
Just so long as we document that duration data is ISO8601 compliant and that we perform the conversion of certain duration values.
