### ISSUE TITLE
User is able to create multiple items with the same name in root 'System' node

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#108]
This shouldn't be allowed but will be fixed when explorer functionality is changed to use a 'closure' tree and a root 'System' node is physically created.

**Comment by jc064522** [comment]
Do we really care if we can do this? Do we want to create extra restrictions about what we can do? This needs to be discussed with @stroomdev66 and @stroomdev10.

**Comment by stroomdev10** [comment]
@stroomdev66  says this is no longer required
