### ISSUE TITLE
Table aggregate function to return first(), last() or nth() value in a group

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1083]

**Comment by stroomdev10** [comment]
Where there are multiple levels of grouping this is useful.

e.g.   User (Grp Level 1) , Host (first(${Host}) , Date (sorted Z-A)

So it would return the latest host for each user

**Comment by stroomdev66** [comment]
Added `any()`, `first()`, `last()`, `nth()`, `top()` and `bottom()` selection functions to select child values of grouped items.
