### ISSUE TITLE
Additions to Pipeline Processor Filter - Terminology Unclear

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1097]
When adding a new filter to a pipeline, it's not obvious what the various options are.  For example, when selecting by Feed, what is the difference between "is", "=" and "contains" ?

Similarly, when choosing a "Type", you're unable to select from a dropdown list but must have prior knowledge that you want to select "Raw Events" for example.

**Comment by stroomdev66** [comment]
I think the terminology has now been explained and the latter point has been resolved by improving the suggestion drop down.
