### ISSUE TITLE
NPE Stroom Stats Pipeline

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1115]
`java.lang.NullPointerException at stroom.pipeline.server.filter.AbstractSamplingFilter.setDocumentLocator(AbstractSamplingFilter.java:94) at stroom.connectors.kafka.filter.AbstractKafkaProducerFilter.setDocumentLocator(AbstractKafkaProducerFilter.java:53) at stroom.pipeline.server.filter.AbstractXMLFilter.setDocumentLocator(AbstractXMLFilter.java:114) at stroom.pipeline.server.filter.XSLTFilter.setDocumentLocator(XSLTFilter.java:294) at stroom.pipeline.server.filter.AbstractXMLFilter.setDocumentLocator(AbstractXMLFilter.java:114) at stroom.pipeline.server.filter.AbstractXMLFilter.setDocumentLocator(AbstractXMLFilter.java:114) at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startDocument(AbstractSAXParser.java:290) at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startDocument(XMLDTDValidator.java:636) at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.startEntity(XMLDocumentScannerImpl.java:542) at com.sun.org.apache.xerces.internal.impl.XML...`

**Comment by at055612** [comment]
Fixed in 8740081cf2c7eb9f04297b3bf8a1b7c01eed3fb0
