### ISSUE TITLE
Modify `StreamDumpTool` to allow one to extract original metadata and data from a given stream file.

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#1119]
There are a number of circumstances where one wants to extract the metadata and data from a given stream stored in the Stroom store filesystem from the command line. This includes breaking up an N file stream into N sets of metadata and data files.

The idea would be to specify a stream file prefix ... eg <feed-id>=<stream-id>.<datatype> and directory path and have the tool extract, for each file in the stream, it's stored metadata and data, into a given file set template (eg meta.000, data.000, meta.001, data.001, etc)

**Comment by stroomdev66** [comment]
See https://github.com/gchq/stroom-docs/blob/master/user-guide/tools/stream-dump-tool.md for instructions on how to use StreamDumpTool
