### ISSUE TITLE
New type of index processing (one stream to many shards)

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#1128]
On occasion, there is a requirement to establish (or re-establish) an index based on old Event data. It would have value on searching if one could have an index processor that creates an index shard based on the date of the event rather than the data of processing. This has an advantage of applying more efficient date based shard searching.
Naturally one would have to place limits on how far back one goes (ie the oldest dated shard can be defined as could any future dated shards).

**Comment by stroomdev10** [comment]
Event Time partitioned Indexes do this.
