### ISSUE TITLE
Check all module layers conform to agreed structure and responsibilities

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#1131]
TODO
FetchUserAppPermissionsAction (stroom.security.shared)
ChangeUserAction (stroom.security.shared)
LogoutAction (stroom.security.shared)
CreateUserAction (stroom.security.shared)
UpdateFsVolumeAction (stroom.data.store.impl.fs.shared)
ExportConfigAction (stroom.importexport.shared)
FetchNodeStatusAction (stroom.node.shared)
PipelineStepAction (stroom.pipeline.shared)
TerminateTaskProgressAction (stroom.task.shared)
FetchCacheRowAction (stroom.cache.shared)
ReprocessDataAction (stroom.processor.shared)
FetchDataAction (stroom.pipeline.shared)
UpdateGlobalConfigAction (stroom.config.global.api)
SessionListAction (stroom.core.servlet)
StroomStatsRollUpBitMaskPermGenerationAction (stroom.statistics.impl.hbase.shared)
DeleteProcessorAction (stroom.processor.shared)
DownloadDataAction (stroom.data.shared)
FindMetaRowAction (stroom.meta.shared)
DownloadDictionaryAction (stroom.dictionary.shared)
FetchPipelineXmlAct

**Comment by jc064522** [comment]
Not doing actions, just checking resources. Handlers will be refactored and aligned with our service style when we come to re-write the UI.
