### ISSUE TITLE
Would like a way for user to provide a description of dashboards

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#1133]
The name of a dashboard has to describe everything about that dashboard.  In many cases, this is inadequate.

It would be better if there was a description field, which could provide background/purpose and other details similar to things that might exist in comments of code.

**Comment by stroomdev10** [comment]
Maybe we need description of a whole bunch of objects

**Comment by gcdev373** [comment]
Agreed, this feature would ideally work on all documents in explorer tree.

**Comment by stroomdev10** [comment]
Available in 7.2
