### ISSUE TITLE
SQL Stats should delete unused sql_stat_key entries

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1141]
Unused SQL Stats keys will persist forever in the database.

This is undesirable from a performance and space utilisation point of view.

During SQL Stats Aggregation it should be possible to purge the sql_stat_key.

**Comment by at055612** [comment]
Probably what we want is do run sql like the following at the end of the stats aggregation process, while still under cluster lock.  This will delete any orphaned stat keys, as when we are removing old stat values we don't really know if we are removing all values for a key or just some.

```sql
delete from sql_stat_key ssk 
where not exists (
  select null 
  from sql_stat_val ssv 
  where ssv.name = ssk.name
)
```
