### ISSUE TITLE
ConstraintViolationException when processing a pipeline where the stream appender has a feed of None

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1170]
Seen in v6.0-beta.42-46

Set the feed property in the pipeline's stream appender to None and process the pipeline.  The stream will produce a fatal error with a constraint violation error.  There is no more detail to the exception but I suspect it is the lack of a feed.  The stream appender should really spot the missing feed before it tries to write the stream.

**Comment by stroomdev66** [comment]
It is in fact that the UI allows you to pick the `None` doc ref in the document picker. This should be interpreted in the UI as a null selection.
