### ISSUE TITLE
SQL Stats Queries aren't properly displayed in Server Tasks Window

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1191]
A SQL stats query appears as a GenericTask, User = INTERNAL and No Info

So not really that helpful

**Comment by at055612** [comment]
It may just be a case of calling setTaskName on the taskContext around line 376 of StatisticsSearchServiceImpl.

Also need to figure out why the task is not attributed to a user.  It just shows as 'internal'.

**Comment by stroomdev66** [comment]
Issue regarding `User = INTERNAL` has been split out as #1192
