### ISSUE TITLE
Proxy no longer accepting data without feed name header

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1216]
I've heard that v4 and v5 of STROOM proxy were able to accept zipfiles in proxy format (i.e. 001.dat and 001.meta) where no Feed header argument was provided, so presumably the proxy broke the zip file open to extract the feedname from the .meta file.  This doesn't occur in v6 and I have my doubts as to whether it ever worked.

Please confirm if such functionality was ever present.

**Comment by stroomdev66** [comment]
It appears that this was never possible so closing
