### ISSUE TITLE
Make Viz links work the same way as Table links

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1243]
Currently only StroomLink() is exposed to viz  and doesn't understand dashboard links

**Comment by stroomdev66** [comment]
Visualisations can now link in the same ways that tables can. The following functions are now available:

stroom.link(href, target)
stroom.dashboard(uuid, params, queryOnOpen)
stroom.annotation(annotationId, streamId, eventId, title, subject, status, assignedTo, comment)
stroom.stepping(id, partNo, recordNo)
stroom.data(id, partNo, recordNo, lineFrom, colFrom, lineTo, colTo)

The functions can be called via d3 handlers, e.g.
```
bar.on("click", function(d, i) {
   stroom.dashboard(null, "user=" + seriesData.key);
});
```
