### ISSUE TITLE
NPE when querying minimal/incorrectly defined index

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1289]
Create an index without StreamId and EventId

Attempts to query the index result in a NPE that is captured by the UI

**Comment by at055612** [comment]
Unable to recreate this.  Created an index/xslt with just a `Feed` field.  On querying the index I get

![image](https://user-images.githubusercontent.com/22818309/66817824-35b67a80-ef34-11e9-8662-0e337c737107.png)
