### ISSUE TITLE
Some paths using SecurityFilter that shouldn't be

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#1295]
`SecurityFilter` currently matches `/*` so applies to all resources. Internally it allows `clustercall.rpc` and `/datafeed` requests to proceed without authentication.  However other paths ought to also avoid `SecurityFilter` or the need for authentication internally: 
`/status`
`/echo`,
`/debug`
`/sessionList`
`/remoting/remotefeedservice.rpc`

Ideally the match pattern for security filter would allow these paths or the paths would be altered to make it obvious they didn't need authentication. For the paths that security filter does allow internally, `SecurityFilter` proceeds as if the `admin` user had initiated the request. Ideally all of the above paths would execute as the internal processing user.

**Comment by at055612** [comment]
Will require changes to the nginx conf to provide reverse proxy upstream paths for these locations
