### ISSUE TITLE
Incorrect screen rendering for an IPAddress with a <space> at the end

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1320]
In stepping, if an IPAddress contains `xxx.xxx.xxx.xxx<space>` then it is rendered as `xxx.xxx.xxx.xxx` in the XML output panes.

The schema filter correctly reports the error, but the rendering on the screen is incorrect.

This has been an issue since v4 at least.

I assume the fields are being trimmed?  Does this apply to all fields?

**Comment by stroomdev66** [comment]
Fixed in v6.0.19
