### ISSUE TITLE
Annotation fixes and Improvement

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1327]
Can't set a comment via the API using &comment=

In the Annotation popup, if the Title is very long it can't be read, either wrap or hover to see it all

**Comment by stroomdev10** [comment]
maybe show a message if streamid or eventid are null when updating/creating annotations

**Comment by stroomdev10** [comment]
please default datetime fields to use formatDate() in their expression

**Comment by stroomdev10** [comment]
When changing an annotation, please include before and after values for a field

**Comment by stroomdev10** [comment]
Hidden fields aren't visible to visualisations

**Comment by stroomdev10** [comment]
Querying on UpdatedOn or CreatedOn fails with a java.lang.NumberFormatException using either a date or date function

**Comment by stroomdev10** [comment]
annotation() is causing the Title (and maybe other fields) to appear as URLEncoded fields in the popup

**Comment by stroomdev10** [comment]
copy full comment history to the clipboard

Allow the user to populate a comment from some Standard text templates

**Comment by stroomdev10** [comment]
Have a think about many to many Event/Annotations

**Comment by stroomdev66** [comment]
Moving `Have a think about many to many Event/Annotations and the implications for open/close of multiple issues` to issue #1336 and closing this issue.
