### ISSUE TITLE
When Deleting a Stream Processor Filter allow the user to optionally delete ALL outstanding tasks against the filter

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#1346]
Sometimes, a Stream Processor filter will have tasks that are not marked **Complete**, and hence will not be automatically deleted (according to the _stroom.streamTask.deleteAge_ property).

When deleting a Stream Processor Filter that has such tasks, the UI should ask the user if they want all outstanding tasks deleted, irrespective of task status.

**Comment by stroomdev66** [comment]
A logical delete of a processor filter is now performed (see #1510). All associated tasks will be deleted by the system soon after a processor filter is deleted regardless of state.
