### ISSUE TITLE
The stroom start script should provide a longer timeout

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#1383]
When starting Stroom for the very first time and the data is loaded, a timeout of 120 seconds is a little low.
It is suggested that the variable `maxWaitSecs` is set to say 240 seconds as empirical tests have shown that the initialisation of the `stroom` database can take up to 190 seconds.

Thus in `stroom/latest/start.sh` set `maxWaitSecs=240`

**Comment by at055612** [comment]
Changed in both stroom and the stack
