### ISSUE TITLE
v6.1.1 Search never completes

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1387]
stroom v6.1.1
Running a simple search that's previously completed within seconds on v6.0 results in one of two nodes never completing and results missing.

Server Tasks shows:
```Cluster Search - Searching... found 40 documents performed 0 extractions (Stroom P5 #9)
   Extraction (Extraction #871)
   Search Result Sender - Creating Search Result (#8 - GenericServerTask)
```
Thread dump to follow.

**Comment by stroomdev00** [comment]
Ignore the hyperlinks in the initial report - I was just trying to put hash chars in.

**Comment by stroomdev10** [comment]
[20200221_StuckSearch.txt](https://github.com/gchq/stroom/files/4235477/20200221_StuckSearch.txt)

**Comment by stroomdev00** [comment]
Application restart fixes it for a while but then it fails again with:

TaskManagerImpl - exec() - Unexpected Exception (GenericServerTask)
