### ISSUE TITLE
v6.0 Search doesn't complete (different issue to 1387)

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1388]
v6.0.32
A long running query remained running in Server Tasks after all search results had been returned to the UI.

Dump to follow, P2 hash18.

**Comment by stroomdev10** [comment]
[20200221_AnotherSearchThing.txt](https://github.com/gchq/stroom/files/4243972/20200221_AnotherSearchThing.txt)

**Comment by stroomdev00** [comment]
Application restart fixes it for a while but then it fails again with:

TaskManagerImpl - exec() - Unexpected Exception (GenericServerTask)

**Comment by stroomdev66** [comment]
No longer seems to be happening
