### ISSUE TITLE
Searching gives dead tasks if paused and closed

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1413]
stroom v6.1.4
Running any dashboard search and pausing it, followed by closing the dashboard leaves dead and terminated tasks in the Server Tasks list.

**Comment by stroomdev10** [comment]
stroom.search.extraction.LinkedBlockingQueueTopic.get(LinkedBlockingQueueTopic.java:50)
stroom.search.extraction.ExtractionTaskProducer.lanbda$new$1(ExtractionTaskProducer.java:109)
stroom.search.extraction.ExtractionTaskProducer.$$Lambda$563/8263003.run(Unknown Source)
