### ISSUE TITLE
Processors and Filters to be stored with exported Pipelines

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#1417]
When pipeline elements are exported using Import/Export tool.  It would be good if the processor filters and their filters could also be exported.

Thought should be given to whether it needs to be optional, and if so whether on export, import or both.

It would be good if an "Enable filters and processors now?" feature was available on import.  Guess this would only enable any processors and filters that were enabled in the original export.

**Comment by at055612** [comment]
Relates to https://github.com/gchq/stroom/issues/926
