### ISSUE TITLE
StandardKafkaProducer will fail with an XML payload

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1433]
If the header/value or message/value is XML data then the sax parser will fire startElement and endElement events for the payload rather than just characters() as it would for json/text.

It may need to use something like AbstractSamplingFilter to transform the payload xml into a byte stream or similar. The ReferenceDataFilter does a similar thing as it has to deal with string or xml payload.

**Comment by gcdev373** [comment]
Anticipated behaviour has been confirmed.  Believe its possible to fix with more sophisticated state processing logic in StandardKafkaProducer.

**Comment by at055612** [comment]
You shouldn't need to manually craft XML with chevrons.  Just pass any sax events over to an AbstractSamplingFilter to handle while you are inside the value elements. Then at the end of the value element get the output stream from the ASF.
