### ISSUE TITLE
Inconsistencies between Index and Data Volumes Configuration and Display

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1478]
Various issues when looking at these volumes:
1. One data volume preconfigured on new install, no index volumes;
2. Editing/creating an index volume seems to have an additional step which just lists the volumes with no underlying details, unlike the data volumes;
3. Index volumes seem to contain volume groups but nothing to match for data volumes.

**Comment by stroomdev66** [comment]
This is expected as index volumes have an additional step due to the fact index volumes can be grouped to make selection easier when making an index. There was however an issue found when attempting to create data volumes which has been fixed.
