### ISSUE TITLE
Forward page buttons not enabling when more than 100 streams exist

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#1492]
Stroom v7 UI problem: Stream data browsing - when more than 100 streams exist for a particular feed / filter, only the first 100 are shown but the buttons that should allow paging to older streams do not enable.

**Comment by stroomdev00** [comment]
It looks like the issue is that it only registers a maximum of 100 rows because if you change the "1 to 100" to "1 to 10" then you can page through to "11 to 20" etc but only to a maximum of "91 to 100".
