### ISSUE TITLE
Need a "force delete" for Stream Processor Filters

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1530]
A user with Manage Processors privilege should be able to force the delete of a disabled Stream Processor Filter that has Unprocessed tasks in the Stream Task table.

When a user enables a processor filter, and then disables it before all the tasks are complete, it is impossible to ever delete the stream processor filter without making changes in the DB,  this change should fix that.

**Comment by stroomdev66** [comment]
Fixed as part of #1510
