### ISSUE TITLE
Default stream sort order suboptimal

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1531]
Data streams as viewed within either a Feed or Pipeline are now sorted with the oldest at the top by default, requiring paging to the end to view the latest streams.

On the positive side, sorting by columns works, but not sure how practical this would be if there were many thousands of streams.

**Comment by gcdev373** [comment]
Changed, though the default sort order is still not evident in the UI.  This should be resolved.  New issue opened for this: [https://github.com/gchq/stroom/issues/1534](url)
