### ISSUE TITLE
Possible performance issue in meta flush

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1533]
With a clean system ran setupSampleData, then fired up stroom and turned on processing.

In the logs the flushing of ~7k meta records seems to take longer than i would expect.

```
WARN  2020-05-05T07:17:29.137Z Stroom P2 #2 - Flush DataMetaDb s.m.i.db.MetaValueDaoImpl      Saved 1000 updates, queue size is 8276, completed in 9.2s 
WARN  2020-05-05T07:17:34.740Z Stroom P2 #2 - Flush DataMetaDb s.m.i.db.MetaValueDaoImpl      Saved 1000 updates, queue size is 7275, completed in 5.6s 
WARN  2020-05-05T07:17:40.704Z Stroom P2 #2 - Flush DataMetaDb s.m.i.db.MetaValueDaoImpl      Saved 1000 updates, queue size is 6274, completed in 5.9s 
WARN  2020-05-05T07:17:46.623Z Stroom P2 #2 - Flush DataMetaDb s.m.i.db.MetaValueDaoImpl      Saved 1000 updates, queue size is 5273, completed in 5.9s 
WARN  2020-05-05T07:17:52.649Z Stroom P2 #2 - Flush DataMetaDb s.m.i.db.MetaValueDaoImpl      Saved 1000 updates, queue size is 4272, completed in 6.0s 
WARN  2020-05-05T07:17:58.355Z Stroom P2 #2 - Flush DataMetaDb s.m.i.db.MetaValueDaoImpl      Saved 1000 updates, queue size is 3271, completed in 5.7s 
WARN  2020-05-05T07:18:04.113Z Stroom P2 #2 - Flush DataMetaDb s.m.i.db.MetaValueDaoImpl      Saved 1000 updates, queue size is 2270, completed in 5.7s
```

Also before these flushes happen in one contiguous block, it was processing various pipelines.  Processing appears to stop while the flush is happening, then resume when it completes.

The queue in the MetaDaoImpl is non blocking so not sure why processing appears to stop.  The fact the queue is blocking is a concern as it could get very large if there is a hold up on the flushing or the flushing lifecyle job is turned off.  DB locks may be coming into play that are stopping processing from happening while the flush is taking place.

May need to make this a blocking queue and also trigger a flush when the queue reaches a certain size.  Also may want to add an internal stat on the queue size (or a dropwiz metric) so we can monitor it.

**Comment by stroomdev10** [comment]
Mine too 1.5 hours

WARN   [2020-06-29T11:39:24.953Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 129230, completed in 4.1s
WARN   [2020-06-29T11:39:29.311Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 128229, completed in 4.3s
WARN   [2020-06-29T11:39:36.780Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 127228, completed in 7.4s
WARN   [2020-06-29T11:39:42.632Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 126227, completed in 5.8s
WARN   [2020-06-29T11:39:47.152Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 125226, completed in 4.5s
WARN   [2020-06-29T11:39:57.611Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 124225, completed in 10s
WARN   [2020-06-29T11:40:09.252Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 123520, completed in 11s
WARN   [2020-06-29T11:40:22.362Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 122615, completed in 13s
WARN   [2020-06-29T11:40:36.180Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 121668, completed in 13s
WARN   [2020-06-29T11:40:49.923Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 120793, completed in 13s
WARN   [2020-06-29T11:41:03.237Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 119882, completed in 13s
WARN   [2020-06-29T11:41:16.605Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 118965, completed in 13s
WARN   [2020-06-29T11:41:30.223Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 118027, completed in 13s
WARN   [2020-06-29T11:41:44.748Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 117143, completed in 14s
WARN   [2020-06-29T11:42:00.079Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 116142, completed in 15s
WARN   [2020-06-29T11:42:15.623Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 115153, completed in 15s
WARN   [2020-06-29T11:42:29.441Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 114170, completed in 13s
WARN   [2020-06-29T11:42:43.018Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 113169, completed in 13s
WARN   [2020-06-29T11:42:57.179Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 112168, completed in 14s
WARN   [2020-06-29T11:43:04.012Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 111187, completed in 6.8s
WARN   [2020-06-29T11:43:05.550Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 110186, completed in 1.5s
WARN   [2020-06-29T11:43:07.005Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 109185, completed in 1.4s
WARN   [2020-06-29T11:43:08.629Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 108186, completed in 1.6s
WARN   [2020-06-29T11:43:10.283Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 107187, completed in 1.6s
WARN   [2020-06-29T11:43:11.814Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 106186, completed in 1.5s
WARN   [2020-06-29T11:43:13.495Z] [Stroom P2 #6 - Flush DataMetaDb] stroom.meta.impl.db.MetaValueDaoImpl -  Saved 1000 updates, queue size is 105189, completed in 1.6s

**Comment by stroomdev66** [comment]
I've attempted to improve the performance of this in code but it might be a DB issue.
