### ISSUE TITLE
Stepping on a large file is slow

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1541]
If you step COUNT_FEED_LARGE in setupSampleData against CountStatisticsSQL, it takes minutes before you can start stepping the records.

**Comment by at055612** [comment]
From debugging ref data stepping it looks like when the stepper is first opened it process all records in the file as I am seeing the ref lookup calls for each record.  This doesn't seem right to me.

**Comment by stroomdev66** [comment]
This might have been fixed when I prevented stepping on opening as I can't reproduce. Closing for now....
