### ISSUE TITLE
Imported dashboards from v6.1 do not display any results in v7.0

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1544]
The attached dashboard was initially created in v6.1 and imported into v7.0, after which the "New Table Created in v7.0" was created in v7 to show the differences.

[StroomConfig.zip](https://github.com/gchq/stroom/files/4592444/StroomConfig.zip)

Issues seen:
1. Unable to rename the original Table (appears to rename but saving and reopening resets the name to "Table";
2. The old table shows no rows when run, whilst the new table shows many rows;
3. The old table only shows rows once the EventTime column is removed.  This is not specific to EventTime - if importing a table with multiple columns, it will only show an output when only StreamId and EventId remain;
4. If the EventTime column is removed and immediately replaced without saving in between, the table displays correctly;
5. Same issue occurs when extraction pipeline is set to "None".

![Screenshot_2020-05-07_10-56-36](https://user-images.githubusercontent.com/41046033/81286983-810bb400-9051-11ea-8350-167ccf2471ac.png)

**Comment by stroomdev66** [comment]
Fixed as part of #1396

**Comment by stroomdev00** [comment]
Have the same issue importing a dashboard created in v7.0-beta.31 into b.32.

**Comment by stroomdev66** [comment]
I think I've fixed this but have a feeling that `Unable to rename the original Table (appears to rename but saving and reopening resets the name to "Table";` occurs intermittently. Please perform further testing.
