### ISSUE TITLE
Only "Type = Raw Events" available in Feed and Pipeline filter drop-downs

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1586]
If selecting to filter by Type, only the Raw Even ts type is selectable.

This makes it impossible to recreate any pipelines so is high priority.

**Comment by at055612** [comment]
This is an issue of the types not being added to meta_type tbl during migration or on boot.

**Comment by at055612** [comment]
The types exist in SetupSampleData though, hence why it works in dev.
