### ISSUE TITLE
RecordOutputFilter is not removing records with an Error

### ISSUE THREAD

**Issue by outside-free** [gchq/stroom#1597]
In stroom_core_test-v7.0-beta.34.

Using a pipeline that inherits from the Reference Data Pipeline: in my scenario it reads 4 records. All generate an Error at the schemaFilter, but then it writes 4 records out, when I expected that to be zero.

The pipeline is as the original: with a RecordOutputFilter immediately aftert the schemaFilter.

**Comment by outside-free** [comment]
Maybe this isn't a bug (or not exactly as described) because my translation was erroneously adding a record-level element after the <reference>...</reference> element, and it seem this was being removed, but the original <reference> was left, and hence written out.

**Comment by outside-free** [comment]
Am confiovned this is not a bug. Simply me being confused by the read/error/write counts not simply adding up when a translation outputs multiple records.

**Comment by stroomdev66** [comment]
Non issue
