### ISSUE TITLE
Check all audit code

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#1598]
In handlers, resources and Commands

**Comment by at055612** [comment]
Before we overhaul the audit logging we need to bring the event-logging lib up to the latest schema.

We also need to release a version of event-logging that uses the fluent builder API (https://github.com/mklemm/jaxb2-rich-contract-plugin).  As my merged PR on his repo is still waiting to be released we may need to fork his repo and release to bintray.  The fluent API will make it much easier to craft events and if we address this before overhauling all the auditing there will be less to refactor later.
  
See 
https://github.com/gchq/event-logging/pull/8
https://github.com/gchq/event-logging-schema/pull/61

**Comment by gcdev373** [comment]
API calls listed, next need to work out which do / don't require audit logging and which of those don't have it yet.
[restfulApiLogging.xlsx](https://github.com/gchq/stroom/files/5604466/restfulApiLogging.xlsx)

**Comment by gcdev373** [comment]
Checking complete!
