### ISSUE TITLE
Can't filter for Kafka Configs in the navigator filter popup

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1602]
For other types you can filter by type e.g. XSLT

**Comment by at055612** [comment]
![image](https://user-images.githubusercontent.com/22818309/83387369-822bc900-a3e4-11ea-880d-9a3bb4013341.png)

Appears to be working in beta.35

**Comment by stroomdev10** [comment]
Not working on a new b.37
<img width="492" alt="Screen Shot 2020-06-15 at 13 01 11" src="https://user-images.githubusercontent.com/28703366/84655266-93a6c200-af08-11ea-812d-1ba5aadee737.png">

**Comment by stroomdev10** [comment]
is also missing SolrIndex, Rules

**Comment by stroomdev10** [comment]
Was the browser cache!
