### ISSUE TITLE
Attempting to delete streams provides incorrect/unnecessary detail

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1619]
Looks like the functionality provided by gchq/stroom#1557 needs a bit more work.  Attempting to delete a stream brings up a popup telling the user that zero items will be deleted and then goes on to list feeds/pipelines/etc, all with a count of zero.  Nowhere in the list does it specify the number of streams being deleted, which is all that was asked for by the user.

Update:

1. There is a bug in the summary where is says 0 items but then actually deletes one item (or the number selected)
2. If there are genuinely 0 items selected then it should say something like The current selection matches no data with no details etc.
3. We should drop the processors count as it is pointless
4. The details should be prefixed with the words The selected data exists in:
5. There should be an option to expand the counts of feeds, pipelines etc to see the actual detail (maybe in another popup)

**Comment by gcdev373** [comment]
Investigation has revealed more general problems relating to queries that use extended meta attributes.  The resolution should address these.

**Comment by gcdev373** [comment]
Investigation has revealed more general problems relating to queries that use extended meta attributes.  The resolution should address these.

**Comment by gcdev373** [comment]
Issue has been resolved.
However this suggestion:
>There should be an option to expand the counts of feeds, pipelines etc to see the actual detail (maybe in another popup)

Will be addressed via [enhancement](https://github.com/gchq/stroom/issues/1697)
