### ISSUE TITLE
Case sensitive issue with fuzzy match

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1620]
When attempting to pick a feed for a pipeline filter, data retention etc, typing "S" displays all STROOM-* feeds as expected, but typing "ST" returns nothing.  However, typing "st", "stro" etc all work as expected, returning all STROOM-* feeds.

**Comment by at055612** [comment]
Working as intended.  `ST` should match `STROOM_TEST` but not `STROOM`
