### ISSUE TITLE
Include Stream Type in Data Downloads and respect the value on Data Upload

### ISSUE THREAD

**Issue by outside-free** [gchq/stroom#1628]
The ability to Download a number of Streams in one go, and then restore them with all their Meta-data into another Feed is incredibly useful, except that it does not restore the Stream Type on upload, instead using the mandatory Stream Type chosen on the Upload dialog. 

So, if we download a number of mixed Streams (say Raw Events, Records, Events and Errors) then they will all be restored as the same Type, unless we manually split the zip, or perform multiple Downloads with different Filters.

Could the Stream Type be added into the meta of each downloaded stream, and then this used on the Upload to restore the original? The Upload dialog may need updating then to indicate that the chosen Stream Type is only for streams with no suitable meta.

**Comment by outside-free** [comment]
I just noticed that the Type is already  included in the `.mf` file, for example: `Type:Raw Reference`

**Comment by gcdev373** [comment]
Feeding streams other than either Raw Events or Raw Reference into Stroom directly can easily to problems/confusion.  These streams would not have been created by Stroom and so have no parent stream.
There would probably need to be a new permission to allow uploading non-raw streams directly to feeds.

**Comment by gcdev373** [comment]
The download / upload process is already  possible to script using the Stroom API.
It is therefore possible to determine the feed name from the downloaded meta file and use it for upload.  See [this gist.](https://gist.github.com/gcdev373/0ba814e55f958d88471131248e22e8b9) 
The upload script allows the user to replace one feed name with another, which is an example of why a scripted approach might be preferable in many cases.

**Comment by gcdev373** [comment]
Seems low priority as there is now a script that will achieve this.
