### ISSUE TITLE
Add != (notequal) operator to expression editor for Rules

### ISSUE THREAD

**Issue by outside-free** [gchq/stroom#1637]
This would also be applicable to other places that use the expression builder, but immediate request is to add a `!=` operator for Rules.

This would mean we could simply write:

`AND( "X-SSL-Client-Verify" != "SUCCESS")`

Instead of:

`NOT( AND( "X-SSL-Client-Verify" = "SUCCESS"))`

It doesn't look much different on paper, but would help a lot with the ediitng (a good number less mouse clicks required) :)

**Comment by stroomdev10** [comment]
Rules are now based on StroomQL, which has a `!=` operator
