### ISSUE TITLE
Inconsistency in use of standard blue colour

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1650]
looks like all of the btn svgs use the darker blue `#2196f3` while some (including Folder) of the document icons use the lighter blue `#64b5f6`

`#2196f3` is the one true stroom blue so we need to apply it everywhere.

e.g. 

![image](https://user-images.githubusercontent.com/22818309/84393676-c775a500-abf3-11ea-89ed-a3161dabe557.png)

**Comment by stroomdev10** [comment]
All Hail `#2196f3` the King of Blues
