### ISSUE TITLE
Indexing pipeline IndexVolumeGroup error

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1663]
[1:47:35 indexingFilter] FATAL: Unable to find any index volumes for group with name null
[xsltFilter] FATAL: stroom.pipeline.errorhandler.LoggedException: Unable to find any index volumes for group with name null

Index has a volume group assigned
<img width="571" alt="Screen Shot 2020-06-15 at 15 42 27" src="https://user-images.githubusercontent.com/28703366/84671108-de333900-af1e-11ea-9e94-c80ad8872d81.png">

**Comment by stroomdev10** [comment]
Upon updating the config (changing the retention) and saving, the pipeline no longer errors.

**Comment by stroomdev10** [comment]
This error started again after an upgrade to b38,  so something is resetting it

**Comment by gcdev373** [comment]
Believed to now be [fixed](https://github.com/gchq/stroom/commit/0efcc31c2c0d286ba9922a93781eb77cc961b46c)

**Comment by stroomdev10** [comment]
Still happening in b.71

**Comment by at055612** [comment]
This should be fixed by #2004 . Will close
