### ISSUE TITLE
New Pipeline Reference popup no longer has drop down for Type

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1665]
Previous versions had a drop down for Type, has this been removed or is this a bug.

If removed, then at least can we have suggestions as per the rest of the app please.
<img width="321" alt="Screen Shot 2020-06-17 at 08 23 50" src="https://user-images.githubusercontent.com/28703366/84868138-2152f080-b074-11ea-8f95-e3e0c5f06c43.png">

Also, once set, the Type value isn't reflected in the popup when editing
<img width="730" alt="Screen Shot 2020-06-17 at 09 32 21" src="https://user-images.githubusercontent.com/28703366/84875220-95de5d00-b07d-11ea-9899-dca159456ca3.png">

Oh, yeah, and the naming is inconsistent between the table and the popup, Stream Type vs Type

**Comment by stroomdev10** [comment]
Also happening in Pipeline editor...

<img width="756" alt="Screen Shot 2020-06-19 at 08 02 12" src="https://user-images.githubusercontent.com/28703366/85106006-5ccff500-b203-11ea-89ae-720513dfea96.png">

**Comment by gcdev373** [comment]
Stream types should be exposed and controlled via the explorer tree rather the current setup which allows any stream type, but assigns a special file extension to certain recognised (hard-coded) types.
