### ISSUE TITLE
When showing the editors in stepping mode some of the editors sometimes have horizontal scrollbar not at the start

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#168]

**Comment by burnalting** [comment]
I see a vertical line in various data displays as per sample attached images. Is this the same problem?

![issue168a](https://cloud.githubusercontent.com/assets/10084635/24326485/48755f44-1203-11e7-9621-1e8476e93c4d.PNG)
![issue168b](https://cloud.githubusercontent.com/assets/10084635/24326486/48970e96-1203-11e7-920f-2a9e7ff7dfa1.PNG)

**Comment by stroomdev66** [comment]
No those are print margins but they should be turned off. See issue #211.
