### ISSUE TITLE
Reprocessing from an unfiltered data browser creates incorrect processor filters

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1696]
UI makes a bunch of processor filters with the only condition being Status == Unlocked

<img width="1103" alt="Screen Shot 2020-06-29 at 11 23 22" src="https://user-images.githubusercontent.com/28703366/85996526-46dee300-ba00-11ea-8ccc-714868904c19.png">

**Comment by stroomdev66** [comment]
The filter is correctly created but when tasks are generated in `ProcessorTaskManagerImpl - runSelectMetaQuery() line 938` it needs to add an extra condition to only consider parents of children that were created with the processor we are creating tasks for.
