### ISSUE TITLE
Stepping/Ref Data Issue

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1700]
I'm stepping a translation to test loading of ref data.

When i step into the first and only event, i get multiple Stepping tasks in the ServerTasks / Task Manager screens.

I've taken 2 thread dumps, the second is when there are 3 tasks for my stepping job.

<img width="713" alt="Screen Shot 2020-06-30 at 13 02 01" src="https://user-images.githubusercontent.com/28703366/86123746-ec15bc00-bad1-11ea-9299-1f108cee74fa.png">

[ThreadDump.txt](https://github.com/gchq/stroom/files/4851690/ThreadDump.txt)
[ThreadDump2.txt](https://github.com/gchq/stroom/files/4851691/ThreadDump2.txt)

**Comment by at055612** [comment]
From the look of the dumps it seems the step resource is being called multiple times, which it should not be if the the user has only stepped once.

Also two threads appear to be RUNNING and trying to commit to LMDB.  The xslt has only one lookup to one effective stream so there should only be one thread trying to write to the store.  There should be locks in place to prevent dup loading.

**Comment by at055612** [comment]
``` xslt
<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet xpath-default-namespace="event-logging:3" xmlns:sm="stroom-meta" xmlns="event-logging:3" xmlns:rec="records:2" xmlns:stroom="stroom" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="3.0">
  <!-- Ingest the Evts tree -->
  <xsl:template match="rec:records">
    <xsl:element name="Events">
      <xsl:attribute name="xsi:schemaLocation">
        <xsl:text>event-logging:3 file://event-logging-v3.4.2.xsd</xsl:text>
      </xsl:attribute>
      <xsl:attribute name="Version">
        <xsl:text>3.4.2</xsl:text>
      </xsl:attribute>
      <xsl:apply-templates />
    </xsl:element>
  </xsl:template>
  <!-- Main record template for single Evt event -->
  <xsl:template match="rec:record">
    <xsl:variable name="cnt" select="rec:data[@name eq 'cnt']/@value" />
    <xsl:for-each select="1 to 5">
      <xsl:copy-of select="stroom:lookup('REFDATASRC1',concat('REFDATASRC1_',.),stroom:meta('ReceivedTime',''),false(),true())"/>
    </xsl:for-each>
  </xsl:template>
  <!-- Build the record element -->
</xsl:stylesheet>
```

**Comment by at055612** [comment]
ref data: 
``` xml
<referenceData xmlns="reference-data:2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.1" xsi:schemaLocation="reference-data:2  file://reference-data-v2.0.1.xsd">
  <reference>
    <map>REFDATASRC1</map>
    <key>REFDATASRC1_1</key>
    <value>REFDATASRC1_1_2020-06-01T00:00:00.000Z</value>
  </reference>
  <reference>
    <map>REFDATASRC1_XML</map>
    <key>REFDATASRC1_1</key>
    <value>
      <VAL xmlns="stroom">
        <MAP>REFDATASRC1</MAP>
        <VAL>1</VAL>
        <EFF>2020-06-01T00:00:00.000Z</EFF>
      </VAL>
    </value>
  </reference>
```

**Comment by at055612** [comment]
@stroomdev10 can you see if this is still an issue, as there has been a fair bit of change to ref data and stepping code.

**Comment by at055612** [comment]
Closing following re-testing by @stroomdev10
