### ISSUE TITLE
Load times for LMDB may be an issue

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1714]
I have an AWS box with an SSD storage volume rated at 1000 IOPS.

I have a process that loads 300MB of reference data, then performs a handful of reads before terminating.

This process is taking ~60 mins, mostly creating the data.mdb file.

<img width="419" alt="Screen Shot 2020-07-03 at 08 51 55" src="https://user-images.githubusercontent.com/28703366/86445673-b1e32f00-bd0a-11ea-9afb-4fd07f212ae2.png">

Disk performance seems OK when copying files around.

Next test will be with EC2 instance storage

**Comment by at055612** [comment]
For comparison I ran a junit load test which loads 2mill entries into the ref store (albeit with none of the xml parsing, but including the generation of the test data) and this is the result.

```
Produces a 245Mb lmdb file
15:45:53.560 [main] INFO  s.p.r.s.o.TestRefDataOffHeapStore - Counts:, KeyValue: 1000000, KeyRangeValue: 1000000, ProcInfo: 10
15:45:53.560 [main] INFO  s.p.r.s.o.TestRefDataOffHeapStore - COmpleted both loads in PT2M21.823188S
```

**Comment by stroomdev10** [comment]
Testing with EC2 SSD instance storage, got load times down to around 4 mins, which is good news

**Comment by at055612** [comment]
One option would be to try and make use of `MDB_APPEND` mode but this requires pre-sorted keys and the appended keys must be higher than all keys in the db.  Probably the only way we could do this is if a whole ref stream was loaded into a separate lmdb env (or db) in append mode.  We could have something in the master processing info db to indicate which lmdb env/db to look in for the entries.  A nightly job could then be used to transfer data over.  As the data is immutable lookups could still continue from the scratch env/db until the whole lot had been copied.  This would add more complexity to the process.

Would need to benchmark a load with/without append mode to see what benefit it brings.  It would also require pre-sorting the whole stream in memory when we are trying to get away from having a load of ref data on heap.

**Comment by at055612** [comment]
Another option is to use the `MDB_NOSYNC` env flag to prevent fsync calls after each commit.  Instead our code would need to manually call env.sync as needed.  This may speed up bulk loads where we can just sync right at the end, as long as the load is idempotent, i.e. if we lose the host part way through the load.
