### ISSUE TITLE
Content pack import importing from multiple dirs

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1728]
If enabled the import process tries to import from list of dirs that includes the configured dir.  This may be confusing for an admin as they have configured a dir and it then finds things to import in another dir.

Need to understand how the core_test stack is configured to imports its packs as any change will need to support that.

Either we should import from the first dir that we find from our list or change the config to be a List<String>.

**Comment by stroomdev66** [comment]
Fixed by gh-1944
