### ISSUE TITLE
IndexShardWriterCache.startup() takes ages during startup

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#174]

**Comment by stroomdev66** [comment]
Added logging to find out which part of startup is too slow. Enable logging by adding this to the Log4J configuration:

  <logger name="stroom.index.server.IndexShardWriterCacheImpl">
    <level value="trace" />
  </logger>

**Comment by burnalting** [comment]
Adding what?

**Comment by stroomdev66** [comment]
```
<logger name="stroom.index.server.IndexShardWriterCacheImpl">
        <level value="trace"/>
</logger>
```
