### ISSUE TITLE
User Event Logging for 'Viewing String' is not schema compliant in v6.1

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1742]
I think this happens when a user views Activities.  
View has no Object or similar

as for the NPE ????

```
<View>
  <Outcome>
     <Success>false</Success>
    <Description>java.lang.nullPointerException</Description>
  </Outcome>
</View>
```

**Comment by stroomdev66** [comment]
I can't recreate this issue, more testing is needed to find exactly when this happens

**Comment by gcdev373** [comment]
Fixed for Stroom v7, but not fixed for previous versions.
