### ISSUE TITLE
Explorer pane really needs an expand all button

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1753]
This is what the system shows me if I select only `Feed` in the filter
<img width="451" alt="Screen Shot 2020-07-27 at 10 07 33" src="https://user-images.githubusercontent.com/28703366/88524304-13887780-cff1-11ea-87d9-bf2048e554bf.png">

Clearly I want to see all the feeds, but I have to type something e.g. `-` into the quick filter to actually see any feeds. It would be nice to have an expand all or similar

**Comment by stroomdev66** [comment]
Expand all, collapse all and a button to find the current open item would also be good.

**Comment by at055612** [comment]
As a work-around you can use a NOT quick filter to expand all matches, i.e. everything, e.g. `!xxxxxxxxxxx`.
