### ISSUE TITLE
Edi User page allows one to edit the UserId, but doesn't reflect the change on next edit, then errors

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1768]
Created a User, edited User, changed UserId (removed space), pressed OK, change was shown on Users page, pressed Edit, it displays the original User Id.

<img width="712" alt="Screen Shot 2020-07-31 at 09 07 49" src="https://user-images.githubusercontent.com/28703366/89014537-8b1a1780-d30d-11ea-90b9-4a906225326f.png">

When you press save , you get this

<img width="418" alt="Screen Shot 2020-07-31 at 09 12 52" src="https://user-images.githubusercontent.com/28703366/89014875-12678b00-d30e-11ea-9ccd-7ee6938d6d7c.png">

If you close all the User pages and re-open, it is all OK

**Comment by stroomdev10** [comment]
duplicate of #1414

**Comment by stroomdev10** [comment]
re-opened as is slightly different to #1414

**Comment by stroomdev66** [comment]
I wasn't able to replicate this issue after fixing gh-1414
