### ISSUE TITLE
Attempting to view processed stream gives no output if input stream first set to meta

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1777]
If a Raw Events stream is selected in the viewer, then selecting the Events stream from the middle pane works as expected - the processed events are visible in the lower pane.  However, if when viewing the Raw Events stream, the Meta tab is selected instead of the Data tab and the matching Even ts stream is selected in the middle pane then no output is shown in the lower pane.

Earlier versions of stroom showed the Events stream regardless of whether Data or Meta was selected for the Raw Events.

**Comment by stroomdev66** [comment]
In recent discussions we believe it might make sense to at least show DB derived meta for data that has no associated meta file

**Comment by gcdev373** [comment]
Latest thinking is:
1. There would be a new tab called Meta that would show info from database about the stream
2. This Meta tab would be the default tab to display (always available for all streams).
3. The API would have a new call to discover which child streams are available for any stream
4. This call would be used by the UI to determine which tabs in additional to the new Meta tab would be shown.
5. The existing Meta tab would be renamed Headers (where it exists).
6. Where a selected stream does not contain the previously selected type of child stream, the default would be selected for all later selected streams.
