### ISSUE TITLE
Format functions don't work on aggregate functions 

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1784]
For example I want to do :

formatDate(max(${Create Time}),’YYYY-MM-dd’’T’‘HH:mm:ss.SSS’)

i.e. a string representation of the max date for a group.

**Comment by stroomdev66** [comment]
I think that my treatment of some functions as aggregates is incorrect and that functions like min/max etc are not aggregate functions as such as they are not aggregating several values just choosing one of the supplied values
