### ISSUE TITLE
data() popup called from table is having trouble displaying records correctly

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1799]
may be related to #1678 

I'm calling data() from a table that is displaying values from the Meta store.

An example Records stream has 3 records, generated from 3 lines of Raw log.

My column expressions are:

data(${Id},${Id})
data(${Parent Id},${Parent Id})

clicking on the ${Id} link shows a popup for the output stream, but no record is displayed for record 1.  Clicking onto the next record display records 2 and 3 respectively.

<img width="909" alt="Screen Shot 2020-08-18 at 16 28 32" src="https://user-images.githubusercontent.com/28703366/90533053-e3f00980-e16f-11ea-9de7-0623000bd065.png">
<img width="892" alt="Screen Shot 2020-08-18 at 16 29 20" src="https://user-images.githubusercontent.com/28703366/90533174-084be600-e170-11ea-92b6-dc66968c3c39.png">

clicking on the ${Parent Id} link shows a popup for the output stream, but "-1" is displayed
<img width="971" alt="Screen Shot 2020-08-18 at 16 30 31" src="https://user-images.githubusercontent.com/28703366/90533354-46490a00-e170-11ea-9458-4600b2439750.png">

**Comment by at055612** [comment]
As this whole area is being re-worked in #1678 it is worth waiting till that work is done and retesting then

**Comment by stroomdev10** [comment]
appears fixed
