### ISSUE TITLE
Change developer tool Setup Sample Data to read config yaml.

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1802]
stroom.path.temp is set to `/home/dev/tmp/stroom` (and was set to this in yml prior to 1st boot)
On booting for the 1st time:
the default stream vol is set to `/tmp/volumes/defaultStreamVolume`
the default index vol is set to `/home/dev/git_work/v7stroom/stroom-index/stroom-index-impl/build/libs/volumes/defaultIndexVolume`

This may be due in part to having run setupSampleData which may not be reading the yml, and thus is using the hardcoded default of /tmp.  

Using /tmp for this sort of persistent stuff may not be such a good idea as some linux distros clear out /tmp on boot.

**Comment by gcdev373** [comment]
Resolved as part of #1944
