### ISSUE TITLE
Creation of folder with name matching up to first N-1 characters of existing folder name will not display in explorer [bug]

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#181]
If you create two folders

> TestA

and

> Test

in this order, then the second folder will not display in the explorer pane.
If you subsequently create another folder with a different name, say

> Sample

then all three folders will display.

**Comment by stroomdev66** [comment]
I think this is due to an old caching issue that has been fixed. Please retest in the latest version.

**Comment by burnalting** [comment]
The issue has been corrected as it cannot be reproduced in beta.19
