### ISSUE TITLE
Quick filter is not working for partial UUID searches i.e. '#abcd'

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1810]
Seen in beta.45

Find the UUID of one of the entities in the explorer tree.
In the exp tree quick filter enter '#' followed by part of the UUID.
It should show that entity.

This also affects other quick filters.  I think the code got refactored at some point so it could filter over many fields and uuid handling has been lost.  Maybe the FilterFieldMappers class needs to have a hasUuid() method and a method to get the uuid.  When the filterFieldMappers is defined the code then supplies the extractor func for the uuid.

**Comment by stroomdev10** [comment]
similar to #1694 ?

**Comment by at055612** [comment]
yes, duplicate.
