### ISSUE TITLE
Daylight savings change issue?

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#182]
Daylight savings changed today and I noticed a weird timestamp issue in a feed as per

![image](https://cloud.githubusercontent.com/assets/10084635/24583440/0ddfc0ec-178d-11e7-87fc-eba8cfdabb2e.png)

This feed has been running for a while and the 23:00 date change issue has not been seen before.
Note the attributes for the first errant entry are

![image](https://cloud.githubusercontent.com/assets/10084635/24583449/b64739e0-178d-11e7-8790-854eeb49f948.png)

Will update tomorrow in case this is not a daylight savings change day issue (i.e the date doesn't jump ahead 24 hours for the last hour of the day)

**Comment by burnalting** [comment]
The day roll over from 2017-04-02 to 2017-04-03 worked fine, so it appears this date aberration is limited to the day daylight savings changes.

**Comment by stroomdev66** [comment]
This appears to be an issue with ClientDateUtil, i.e. a client only issue.

**Comment by stroomdev66** [comment]
Hopefully fixed this issue but testing required.

**Comment by burnalting** [comment]
Problem corrected with build version 5.0-beta.18. Thanks! 
![image](https://cloud.githubusercontent.com/assets/10084635/25027730/4b1bf912-20f2-11e7-8832-31148c253202.png)
