### ISSUE TITLE
SQL Stats query fails if you have zero stat related column expressions specified

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1821]
I've created a query and table against a SQL Stat (e.g. CPU)
The Query is `Date Time between year() and now()`

If I add a column expression `add(123,45)` and run the query, I get an SQL error.

Then I add another column `${Node}` and re-run, the Query works OK.

**Comment by stroomdev07** [comment]
Tested in V7-beta.46 and this bug is present
