### ISSUE TITLE
Annotation and Groups

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1837]
Here are a few ideas about annotation and grouping.

I would like to be able to raise an Annotation for multiple events, that allows me to create an annotation with pre-filled fields.
This mechanism could be either via selecting a Group, or selecting multiple Rows.

There is a concept in SQL to return a list of values for a given group, "group_concat()" in MySQL.  Maybe we could have a table expression similar to this for table groups.

I'd be happy if the group could use values from the first/last or any event in the group.

**Comment by stroomdev66** [comment]
Added `joining()` function in addition to `any()`, `first()`, `last()`, `nth()`, `top()` and `bottom()` child selection functions requested in #1083.
