### ISSUE TITLE
Make an admin account from the command line

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1850]
If using external authentication, it is hard/impossible to add an Stroom account that is an admin.

If we had a command line tool whereby we specify the userid, an admin account for that user is created.

**Comment by at055612** [comment]
We ought to do this as a dropwizard `ConfiguredCommand` like we have done with `stroom.app.commands.DbMigrationCommand` rather than having a separate cli tool.

**Comment by at055612** [comment]
```
app.jar CREATE_ACCOUNT config.yml uname pword //fails on account exists
app.jar RESET_ACCOUNT config.yml uname pword //fails if not exists
app.jar ADD_PERMISSION config.yml uname permName  // adds stroom_user entry if required, fails if perm already set
app.jar REMOVE_PERMISSION config.yml uname permName  // fails if perm not set on user
```
