### ISSUE TITLE
Hung Searches

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1854]
v6.1.11
Multiple stuck searches showing as AsyncSearchTasks with no child tasks, just showing as "Search '<blah>' - searching..."

Stack trace to follow.  Thread Ids: 3613, 3786, 3763, 3785, 3779, 3778.

**Comment by stroomdev10** [comment]
Stack Trace attached as requested 
[gh1854.txt](https://github.com/gchq/stroom/files/5223233/gh1854.txt)
