### ISSUE TITLE
Various User Screen Edit Account Issues

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1862]
By default, the admin user has no email or name values, so when an attempt is made to reset its password, values need to be entered before the password change is allowed.  Both email and name details should be optional.  If email really IS necessary, then please reconsider what addresses are valid and invalid.  Currently, fred@localhost is invalid but fred@localhost.localdomain is fine.

When changing a password, insufficient detail is provided as to the complexity requirements - for passwords of insufficient complexity it appears that the OK button just fails to work as it's not greyed out.  The whole red/amber/green thing also seems pointless as amber passwords are unable to be used so the only things that matter are password sufficient/insufficient.  Maybe use red/green although just greying out the OK would have the same effect.

**Comment by stroomdev66** [comment]
Closing as I think it is ok now.
