### ISSUE TITLE
Conditional Formatting regexes

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1878]
Can we have a regex operator in conditional formatting please

**Comment by at055612** [comment]
This will require a new value in the Condition enum (e.g. `matches`) which is part of the stroom-query lib.  Too much change for v6.  Will have to go in v7.

Also this should wait till a refactor of the conditional formatting is done to make the rules be executed server side.  If the rules are run server side then we can use java syntax regex which is consistent with the rest of the app vs js syntax regex which is not.

**Comment by stroomdev66** [comment]
It would be possible to achieve the same thing by creating a new dashboard column and using the `regex()` function, see similar response for gh-1927.

An example column expression could be:
`max(if(match(${UserId}, 'user1.*'), 1, 0))`
