### ISSUE TITLE
Search Hang v6.1.17

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1887]
Got a search hang on v6.1.17

Stack attached
[20201002.stack.txt](https://github.com/gchq/stroom/files/5317189/20201002.stack.txt)

Affected threads below (top task is from UI node, two below are from the processing node, as is stack)

Task
Name : AsyncSearchTask
User : xxxxx
Submit Time : 2020-10-02T08:03:09.500Z
Age : 1.7h

Id : {f4102e17-1f0e-4988-b660-ca4401be5828}
Thread Name : Stroom P2 #6 - AsyncSearchTask
Search '368|Stroom Errors - Detail|query-JT8D7|UKTF_1601625789165' - searching...

Task
Name : Extraction Task Producer
User : xxxxxx
Submit Time : 2020-10-02T08:03:09.856Z
Age : 1.6h

Id : {7374aa04-e940-4559-8776-c594a20b36d0}
Thread Name : Extraction #25 - GenericServerTask
Parent Id : {1ab01c6b-7938-455d-9210-ead3df3e92ea}
Adding extraction tasks

Task
Name : Cluster Search
User : xxxxx
Submit Time : 2020-10-02T08:03:09.853Z
Age : 1.6h

Id : {1ab01c6b-7938-455d-9210-ead3df3e92ea}
Thread Name : Stroom P5 #9 - ClusterSearchTask
Parent Id : {f4102e17-1f0e-4988-b660-ca4401be5828}
Searching... found 27 documents performed 18 extractions

**Comment by at055612** [comment]
stuck waiting at ``` java 
"Extraction #25 - GenericServerTask" #274 prio=5 os_prio=0 tid=0x00007fe1a0033000 nid=0x4e6a waiting on condition [0x00007fe551cdb000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007fe5beec37a0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
```
