### ISSUE TITLE
Three parameter version of XSLT function stroom:lookup failing in Stroom v7.0-beta.67

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#1905]
Reference data lookups of the form
`stroom:lookup('MYMAP-MAP', 'key', '2020-10-01T01:00:00.000Z')`

Failed to find the reference data stream with  `EffectiveTime:2020-09-30T00:00:00.000Z` as shown in meta tab.

This testing was performed on 15/16 October 2020.

**Comment by at055612** [comment]
Can't recreate this.  I have added content/config to SSD to exercise dated lookups with multiple ref streams, see feed `TEST_REFERENCE_DATA_EFF_DATE-EVENTS`

**Comment by gcdev373** [comment]
Lookups work as intended, but it is necessary to supply EffectiveTime as a http header parameter, it can't be supplied in meta strem.
