### ISSUE TITLE
Search Performance Issues v6.1.20

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1906]
1. Extraction Ordering, choose oldest
2. Nesting of tasks in server tasks
3. Reporting Queue sizes in Task Info
4. Configurable queue sizes
5. Doesn't appear to stop when table row limit reached (unsorted)

**Comment by stroomdev66** [comment]
Issues remaining:
1. Nesting of tasks in server tasks
2. Reporting Queue sizes in Task Info
3. Doesn't appear to stop when table row limit reached (unsorted)

**Comment by stroomdev66** [comment]
Issues remaining:
1. Reporting Queue sizes in Task Info
2. Doesn't appear to stop when table row limit reached (unsorted)
