### ISSUE TITLE
The stats 'JvmHeapUsedMb' etc should be changed to 'JvmHeapUsedMB' etc as the symbol for bytes is always 'B'. Stroom uses JEDEC multiples of 1024 for all values.

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#192]

**Comment by stroomdev66** [comment]
The values will be in Mebibytes but changing the named to *MiB seems a bit odd. Also changing the names to be suffixed with just M as we do elsewhere might also look a bit strange. As a result I think we should just have MB and agree that we are dealing with JEDEC definition.

**Comment by burnalting** [comment]
If we maintain this posture, then it should be very clear in our documentation, and repeated often, that within Stroom
> MB := JEDEC multiples of 1024

**Comment by stroomdev66** [comment]
Related to issue #231
