### ISSUE TITLE
Saving a dashboard with a Text Window, breaks the StreamId

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1921]
Create a dashboard with StreamId and EventId
Config Text Window with StreamId and EventId
Save Dashboard
Open Dashboard, Text Window has reverted to `__streamid__`

**Comment by at055612** [comment]
Seen in 6.1.22

**Comment by stroomdev10** [comment]
also if I hide these columns, the Text Window config reverts the EventId to __event_id__

**Comment by stroomdev10** [comment]
It also doesn't work when configured with `__stream_id__`  and `__event_id__` and looking at event detail within groups
