### ISSUE TITLE
Conditional Formatting, allow use of dashboard parameters

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1927]
I would like to use dashboard variables in Conditional Formatting 

e.g. user=${user1}

**Comment by stroomdev66** [comment]
It is possible to create a column in a table that uses the `param()` dashboard table function to grab a param, e.g. `user`, and compare it to a field, e.g. `UserId`, using if to control the column output. I have tested this using the following expression in a column called `Custom`:

`max(if(equals(param('user'), ${UserId}), 1, 0))`

and applying a conditional format rule to

`Custom = 1`
