### ISSUE TITLE
Log pane for stepping

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1941]
During stepping ERROR/WARN/INFO/DEBUG messages are accessed via a tooltip on an icon top left of the stepped element.

How about we have a log Pane to show any output messages instead / as well

**Comment by at055612** [comment]
If the log pane uses the Ace Editor then we could use a custom syntax highlighter to distinguish the different log levels.  May also want the log pane to be toggleable but that would then require some other indicator to show that the log pane has something in it.

**Comment by at055612** [comment]
fixed in > 7.2-beta.30
