### ISSUE TITLE
Error - State transition from DELETED to CLOSED was attempted but is not allowed

### ISSUE THREAD

**Issue by stroomdev07** [gchq/stroom#1946]
When stopping Stroom the following error is shown.

ERROR [2020-11-12T09:08:11.365Z] [Index Shard Writer Cache #7369 - Closing writer] stroom.index.impl.IndexShardManager - State transition from DELETED to CLOSED was attempted but is not allowed

Then the following:

INFO  [2020-11-12T09:10:17.712Z] [pool-6-thread-1] stroom.index.impl.IndexShardWriterCacheImpl - Waiting for 2 index shards to close

v7.beta67

**Comment by stroomdev66** [comment]
This is because an open shard has been deleted before the system tried to close it. We should either stop the user deleting open shards or suppress the error.
