### ISSUE TITLE
Set `useForwardedHeaders` to true in DW config

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#2032]
In Dropwiz 1.3 useForwardedHeaders is true by default but in v2 defaults to false.  As we have nginx in front, we want the client ip details from the `x-forwarded-for` header.  Therefore it makes sense to explicitly set this to true to ensure when we jump to DW v2 we don't lose this functionality.

See #2025

**Comment by stroomdev66** [comment]
This has been done in 7.1 as part of the uplift to DW 2.
