### ISSUE TITLE
Solr table field mappings are incorrect

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#2034]
When performing a search against a Solr index, the columns in result tables do not map to the corresponding Solr fields.

See the screenshot for an example.

![image](https://user-images.githubusercontent.com/17559369/106467107-51aaaa80-64f0-11eb-88df-e30c8cd3414c.png)

**Comment by p-kimberley** [comment]
To clarify, this affects the current master (as at 02 Feb 21) and *not* the 6.1 branch.

**Comment by stroomdev66** [comment]
switched to gh-2034 branch
