### ISSUE TITLE
Visualisations not using all the data from associated table

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2043]
Possibly related to #1989.
When a dashboard is displayed, the viz may not always display all data depending on the number of rows returned in the table.  Using the `dave / CPU (All nodes)` dashboard as an example on the AWS cluster, changing the time period to `> now()-1h` shows an hour of data from all 5 nodes, `> now()-8h` shows 8 hours of data from only 3 nodes and `> now()-24h` shows data from a single node from 24hours ago but only up until 7 hours ago.  What's displayed in the viz is not affected by ordering of the table data.

This occurs for stats dashboards, it's unclear if it also affects index dashboards asa separate issue is making these tricky to run.

**Comment by stroomdev66** [comment]
Removed an artificial limit on the number of data points that will be returned to a dashboard visualisation. The UI code had been written to only request a maximum of 1000 data points which meant that some visualisations were missing expected data. It may be necessary to add some limitation to avoid the UI being overloaded but the limitation has been removed for now as it was not configurable and did not warn the user when the limit had been reached.
