### ISSUE TITLE
Change Appender ERROR to WARN

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2050]
The following should really be a WARN:

`ERROR  [2021-02-12T14:55:28.020Z] [dw-28 - GET /api/node/v1/info/Stroom-1a] stroom.event.logging.impl.DocumentEventLogImpl -  No appender found for stroom.node.shared.ClusterNodeInfo`

**Comment by gcdev373** [comment]
Fixed in latest version (now debug level).
