### ISSUE TITLE
How do I migrate a v6 Stack with 3 DBs to a v7 stack?

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2082]
I tried, I failed.

**Comment by at055612** [comment]
See documents (WIP) in https://github.com/gchq/stroom-docs/pull/54

**Comment by at055612** [comment]
Migration of the auth db in a v6 will not work as the flyway schema table has been renamed so it will never find the v6 one and thus will try to create tables afresh which will conflict with the old ones.  The plan is to change the migration to rename all the v6 table to old_auth_ (use old_auth_ rathet than old_ to avoid any clashes with stroom tbls) then create the new ones and copy data over as needed if old_tables exist.

If we want to bring the auth db into the stroom db then we will need a pre mig step to rename all the auth tables then exp/imp all the renamed tables into stroom.
