### ISSUE TITLE
Run time Exception Fill Task Store stroom.procesor.impl.ProcessorTaskManagerImpl -  “Expected single value”

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2107]
Run time Exception Fill Task Store stroom.procesor.impl.ProcessorTaskManagerImpl -  “Expected single value”

can provide full stack on request

occurring on a handful of processor filters

I believe the affected processor filters , are of the form "Feed is XXXX" i.e they don't provide a Type="Raw Events"

**Comment by stroomdev10** [comment]
these dodgy migrated processor filters are buggy in the UI too, when editing them to add the  type=Raw Events, they warn ” you are about to process ALL feeds”

**Comment by stroomdev66** [comment]
Fixed the issue with the UI saying `you are about to process ALL feeds` but the initial issue remains.
