### ISSUE TITLE
Include upstream details in the NGINX log for the stack

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#2108]
Because we use NGINX as a reverse proxy it is really useful to know what upstream resources requests are forwarded to.

There are several placeholders that can be added to the log format to provide these details, see here:
https://stackoverflow.com/questions/9914792/logging-proxy-activity-in-nginx

```
log_format upstreamlog '[$time_local] $remote_addr - $remote_user - $server_name to: $upstream_addr: $request upstream_response_time $upstream_response_time msec $msec request_time $request_time';

access_log  /var/log/nginx/access.log upstreamlog;
```

Changing the log format might also require a change to the log processing.

**Comment by at055612** [comment]
This will also require a change to the stroom logging content pack so the data splitter can read and translate the new log format

**Comment by stroomdev66** [comment]
see gh-2163
