### ISSUE TITLE
User defaulting problem when creating new user

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2148]
When creating a new user and setting the password as part of the same task, the user Id defaults back to admin after setting the password.  Manually resetting the UserId to the correct user appears to work fine, but when trying to logon as the new user, it appears that the user's password has not been set at all.  Have to go back in as admin and edit the new user to set the password for it to work correctly.

Presumably this means that if you don't manually reset the UserId from admin then you may inadvertently change admin's password?

**Comment by stroomdev66** [comment]
It seems that this was the browser being helpful and auto completing the user-id field

**Comment by stroomdev10** [comment]
I tried to replicate on my beta 98, and I can't, I also tried replicating on the new sandbox, same result.

I wonder what is different for @stroomdev00
