### ISSUE TITLE
Change the default quick find behaviour to do simple contains lookup without the need for `/` prefix

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#2155]
The default behaviour should be a simple `contains` and not a fuzzy match. Fuzzy mode should be toggled on/off via a button. It should also be possible to choose a regex mode etc.

**Comment by at055612** [comment]
I would argue against changing it back to a default of a simple contains match until we understand the cases where the chars anywhere matching is inferior to a contains match.  Both approaches have trade offs.

One option would be to rank the matches coming back from the fuzzy match, so they get ranked in this order:
Matches starting with the contiguous term
Matches ending with the contiguous term
Matches containing the contiguous term 
Matches containing the term's chars anywhere

Each set of matches would be sorted a-z.

Or possibly:
Matches starting with, ending with or containing the contiguous term
Matches containing the term's chars anywhere

This should hopefully cases where short filter terms match on single chars dotted over the full string.

**Comment by at055612** [comment]
The use of the filter in the explorer tree and tree pickers prevents the use of any ranking so to keep quick filters consistent we will change the default match to be contains with chars anywhere available via a `~` prefix.  Still need to add ranking for results where applicable

**Comment by at055612** [comment]
Fixed in > 7.0-beta.116
