### ISSUE TITLE
Update operations on entities referenced by id are not logged correctly by autologger

### ISSUE THREAD

**Issue by stroomdev07** [gchq/stroom#2186]
Autologger currently expects the "After" version of an entity to be passed to a REST method in order for Update operation logging to work.  This means that any REST method that supplies a reference to the entity rather than the entity itself fail with an error message similar to the one below.
'''
ERROR [2021-04-22T06:59:23.096Z] [dw-34 - PUT /api/processorFilter/v1/17/enabled] stroom.event.logging.rs.impl.RestResourceAutoLoggerImpl - Unable to extract ID from request of type Boolean
'''
It would be possible to log the before version of the entity using only the id, but this means that any human inspecting the logs would have to infer the change based on the name of the method and the value of the other parameters supplied to it.  In order to avoid this guesswork it would be better to log the actual "before" object where it can be obtained from the underlying service.

**Comment by gcdev373** [comment]
Fixed (on 7.0 branch) - autologger now obtains the actual "before" value of the entity from the underlying service where possible.
