### ISSUE TITLE
Add Documentation item to Stroom

### ISSUE THREAD

**Issue by robin54747** [gchq/stroom#2197]
Would it be possible to add a Documentation item to Stroom, that could for example be a Markdown formatted text document? If it always opened in "rendered" view, but had a "source" view for editing, then it would provide a nice way to keep local documentation about feeds and translations, etc.

Local links to other documentation items would be useful.

Images might not be too important, but could be a useful addition later.

**Comment by at055612** [comment]
This would seem to do the job of markdown => html
https://github.com/vsch/flexmark-java
