### ISSUE TITLE
7.0 Minor UI things that are annoying me

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2241]
Data Retention screen, the icon at the end of each rule is unnecessary, could the UI not just add a new line where the current highlighted item is?

Processor Filter edit screen:  selecting a new field / operator collapses the line you are working on, same for Query editor

Quicksearch is kind of if annoying in this new mode with a system with *loads* of content, i would like the default to be regex or simple text search and the current default to be available via a modifier.  an example is using the old search  i found 3 results by typing 6 chars, with the new search I've got more than 30 results, that isn't helpful

**Comment by at055612** [comment]
The quicksearch bit relates to #2155
