### ISSUE TITLE
Data Retention Impact Summary Nested View clicky problems

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2249]
I can't expand the second level of nesting via the Expand All or the group triangle.

Table view seems to be showing lots of data

**Comment by at055612** [comment]
Seems to be an issue with the nesting rather than the data, as the flat view appears to show everything.  It wasn't showing the detail level.

**Comment by at055612** [comment]
Fixed in >beta.16

**Comment by stroomdev10** [comment]
I'm guessing > beta.116
