### ISSUE TITLE
Quickfilter help. myfield example is confusing

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2266]
The `myfield:abc` line is a bit confusing, maybe expand the to examples. section to include more instead

<img width="789" alt="Screenshot 2021-05-24 at 13 43 33" src="https://user-images.githubusercontent.com/28703366/119349506-2366fb80-bc96-11eb-8dd1-28182505ea24.png">

**Comment by at055612** [comment]
Fixed in b.118
