### ISSUE TITLE
Improve support for XSLT 3.0

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#2320]
Certain aspects of the XSLT 3.0 spec, like `xsl:map` are currently not supported with the version of Saxon (9.7, release in 2017).

These features would be very handy in XSL filters and could improve maintainability and performance.

Recommend updating the Saxon library to >= 9.8 in order to enable support for `xsl:map` and other features.

**Comment by gcdev373** [comment]
This change is known to cause issues with certain translations.  Retesting is strongly recommended!

Comments attached to this issue refer to particular aspects that have been observed to be especially problematic.

**Comment by gcdev373** [comment]
Behaviour of `current-group()` has changed.  In addition to the documented fact that it is now no longer used within `xsl:merge` operations, it appears to have changed in other more subtle respects too.
