### ISSUE TITLE
Content Pack Import not working as described

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2337]
Zipfiles in the content_pack_import directory aren't moved to a subdir after either being imported (or possibly failing to import) as described in the content_pack_import/README.md file.

**Comment by at055612** [comment]
Just tried this.  Placed a content pack zip in the `content_pack` dir and on boot it was imported and moved to the `imported` sub dir.

**Comment by at055612** [comment]
Closing as unable to replicate after discussion with @stroomdev00
