### ISSUE TITLE
Path problems within logs.sh script or its config

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2350]
When setting $STROOM_HOME to `/home/$stroomuser/stroom/` to enable logs to be stored in this directory rather than in `/home/$stroomuser/stroom/latest/`, logs.sh tries to set `local path_to_app_log=/home/$stroomuser/stroom/latest/home/$stroomuser/stroom/logs/app/app.log` at which point, it starts looking in the wrong place for logs and fails to find them.

**Comment by stroomdev00** [comment]
Looking further, it seems that log locations are being defined in various scripts  in `latest/` as `${script_dir}/${RELATIVE_PATH_TO_APP_LOG}` rather than `${STROOM_HOME_DIR}/${RELATIVE_PATH_TO_APP_LOG}`

It would be useful to know that there's no underlying issue with setting `$STROOM_HOME_DIR` to `~/stroom/` and `$STROOM_APP_HOME_DIR` to `~/stroom/latest/` and to get the scripts working in accordance with this so that the logs can live in `~/stroom/logs/` rather than `~/stroom/logs/latest/`.

**Comment by at055612** [comment]
Proposed solution is to set the yaml to
```
home: "${STROOM_HOME:-}"
```
and ensure that `HomeDirProviderImpl` treats empty strings and nulls as the same, as I suspect this would return an empty string if not set.  Then the bash can set an env var or leave it unset to let java use its fallback of the jar dir.

**Comment by at055612** [comment]
Also need to set the default values for home and temp to null and let the providers provide sensible defaults (i.e. jar dir and TEMP/stroom)

**Comment by at055612** [comment]
Fixed in >beta.139
