### ISSUE TITLE
AppConfigMonitor is logging en ERROR on FileNotFound

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2353]
can it not log an ERROR because ansible is creating transient temp files on a config change

thrown by isSameFile.java

**Comment by at055612** [comment]
It looks like ansible is creating a temporary file as part of an update to a different config file in the directory being monitored.  This is triggering the watch event but by the time isSameFile is called the file has gone.  Just need to catch the NoSuchFileException and quietly ignore it (with some debug).

**Comment by at055612** [comment]
Fixed in > v7.0-beta.139
