### ISSUE TITLE
Edit Account - Inactive/Enabled selection

### ISSUE THREAD

**Issue by stroomdev42** [gchq/stroom#2425]
Edit Account Dialog Box

Using existing users imported from Stroom 6.1.
User=xxxx Inactive.
In Edit Account Dialog box find Inactive selected . Expect to be able to click "Enabled", which will clear "Inactive".
The three selections Enabled/Inactive/Locked should be mutually exclusive to each other and at all times one must be selected.

**Comment by stroomdev66** [comment]
The states are distinct so this is a non issue
