### ISSUE TITLE
Adding additional user to a Folder Permissions. Selection not activated with OK, need double click.

### ISSUE THREAD

**Issue by stroomdev42** [gchq/stroom#2426]
Adding an existing user to an existing Folder that they no access to.
Set Folder Permissions dialog box, click “+” below “?”.  Highlight name and then select OK. NOT added.
Needed to double click new user in "Choose User To Add" to get selection to be added

**Comment by stroomdev42** [comment]
Still occurring on v7.0-b155. Seen HS SBX 09/11/21

**Comment by stroomdev42** [comment]
Still occurring on v7.0-b155. HS SBX on 09/Nov

**Comment by stroomdev66** [comment]
Still works for me in 157
