### ISSUE TITLE
User Account Status not updated upon confimation

### ISSUE THREAD

**Issue by stroomdev07** [gchq/stroom#2427]
When attempting to change account status in Manage Users from Enabled, Inactive or Locked the status does not seem to update upon clicking OK.

The tick boxes will stay the same upon reopening the account and no more changes will be possible due to an error. 

![image](https://user-images.githubusercontent.com/66727220/133260636-f264f02b-f9c0-48f1-b373-1087c02e238a.png)

The account status is only updated and editable once the Manage Users window is closed and reopened.

**Comment by stroomdev66** [comment]
The account was probably changed in the background - might have been made inactive while being changed so this is expected behaviour
