### ISSUE TITLE
Ref Data Locking Issues

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2444]
on a UI node the Ref Data Purge was locked for many hours.

Searches of the Reference Data Store are not returning any values, due to them requesting the same lock as held by the purge.

/shrug

**Comment by at055612** [comment]
Issue was happening when a ref search was terminated then rerun.  The release code was not returning buffers to the queue once the thread was interrupted.

**Comment by at055612** [comment]
Fixed in >beta.145
