### ISSUE TITLE
Stroom Search is occasionally not logging the Additional Context from an Activity

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2446]
There are instances where the Additional Context is not being recorded on Stroom Internal User logging events.

The affected Event has `TypeId = Search` & `Purpose/Data[@name eq 'requireQueryInfo']/@Value = 'true'`

However there is no `Additional Context:` block appended to the associated activity text.

This is v6.1 but may also affect v7

**Comment by stroomdev66** [comment]
Appears to work fine in v7
