### ISSUE TITLE
Orphan File Finder is incorrectly reporting files as orphaned

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2474]
seems to be lots of different types, no real pattern, it reported all 3 files for one Stream that arrived today

just feels all sorts of wrong

**Comment by stroomdev66** [comment]
Added debug and trace logging to `stroom.data.store.impl.fs.FsOrphanFileFinder`

**Comment by stroomdev66** [comment]
Found the problem and fixed
