### ISSUE TITLE
LMDB Reference Data - Broken lookup

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2484]
Raising this , even though Idon't know the specific route to recreate...
The reference map in the error does *NOT* use ranges, although one loaded map does.

```
[1:1:232 xsltFilter] ERROR: Lookup - Lookup errored (map = REFDATASRC1, key = REFDATASRC1_X1, event time = 2021-09-30T00:00:00.000Z) Error performing work in read transaction: Key REFDATASRC1_X1 cannot be used with the range store as it cannot be converted to a long
```

**Comment by at055612** [comment]
The key does exist in the key value store when queried via the api.  For some reason it is not finding the key in the kv store and trying to look it up in the range store.  What is odd is that the error message seen would only happen if the  map in question had entries in the range store but it doesn't.

**Comment by stroomdev10** [comment]
[StroomConfig.zip](https://github.com/gchq/stroom/files/7277310/StroomConfig.zip)

**Comment by at055612** [comment]
```
got some further info for the failed ref data lookup
11:05
reduced the number of entries back from 1000000 to 2
11:06
restarted the node with no reference_data dir
11:06
the lookup failed
11:06
so i deleted the reference data again
11:06
and removed the reference loader for the stream that contained a range
11:06
then the lookups worked OK
11:07
so it seems that having a range style reference stream “loaded” is contributing to the error
```

So there are 4 ref loaders on the event pipe.  2 of them contain the map that the lookups are failing on.  One contains range data.

**Comment by at055612** [comment]
Fixed in beta.149
