### ISSUE TITLE
Rendering of Locked Error Streams in Stream Browser

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2490]
I Have 2 Error streams, one Locked, one Unlocked

Click on the Unlocked Error Stream.
Bottom Pane shows `Info | Error| Data Preview` click on `Info`
Click on Locked Error Stream
Bottom Pane shows `Info | Error| Data Preview` click on `Error`
Error pane disappears and is replaced with Locked Stream message

Why wait for the user to click the pane before deciding it isn't valid to show it?

**Comment by stroomdev66** [comment]
Was this raised in the latest version as I may have fixed already. Works for me when tested on latest codebase.

**Comment by stroomdev10** [comment]
all good
