### ISSUE TITLE
Errors from further along a pipeline showing up in earlier steps when stepping

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2512]
If an invalid timestamp is generated by an XSLT and a later XSLT within the pipeline expects that timestamp to be valid, then the later XSLT causes a popup alert within the first XSLT, stopping any further stepping.

For example, output of XSLT1:
`<TimeCreated>notAValidTime</TimeCreated>`

Content of XSLT2:
`<xsl:if test="xs:dateTime(TimeCreated > current-dateTime())">
   ...`

Probably related to #2511

**Comment by stroomdev66** [comment]
Fixed #2511 and believe this is also fixed as a result
