### ISSUE TITLE
Invalid EventLogging XML generated on logout

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2533]
Some events from `<TypeID>AuthenticationResourceImpl</TypeId>` are missing a `<User>` element

The `<Description>` element in the `<Outcome>` element reports:

`Cannot invoke "java.security.Principal.getName()" because the return value of "javax.servlet.http.HttpServlet.getUserPrincipal()" is null`

**Comment by gcdev373** [comment]
Fixed
