### ISSUE TITLE
Hanging Search  - Advice required

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2554]
I was running some high memory queries which caused OOm on the UI.

The following was logged multiple times on the remote node:

[Search Errors after UI OOM.txt](https://github.com/gchq/stroom/files/7503259/Search.Errors.after.UI.OOM.txt)

Is this just the remote node spotting that the UI has disappeared?

**Comment by stroomdev66** [comment]
Review after #2564 is fixed

**Comment by stroomdev66** [comment]
Review after #2564 is fixed
