### ISSUE TITLE
Changing Priority of a Processing Filter Changes Historic Values Too

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2561]
Set a processing filter to priority 10 and let it run for a bit.  Then change the priority.  The view of processor tasks shows all of the new AND old tasks to be set to the new priority.

This only appears to be the case when combined with #2563 so may not happen at all when that's fixed.

**Comment by stroomdev66** [comment]
Won'f fix as this is not a bug. This issue has been replaced by enhancement request #2571.
