### ISSUE TITLE
Allow pipeline to access Stream attributes such as Effective time

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#258]
In the same way one can access the Stream Id via the @StreamId element in a translation, it would be of value to access other Stream elements. 

In particular, accessing the stream's `Effective` timestamp would be of considerable benefit if one wanted to create indexes out of Reference feeds.

**Comment by stroomdev66** [comment]
The effective timestamp should be accessible already via `stroom:feed-attribute("EffectiveTime")`
