### ISSUE TITLE
Complete Processor Task has Status = <blank> after pane refresh. 

### ISSUE THREAD

**Issue by stroomdev42** [gchq/stroom#2580]
Create Processor such as Id=7777 once complete expect Status to be marked as complete after refreshing pane, or opening pane anew.
Never marked as "Complete"
Compare v6.1 which marks such a processor as Complete.

**Comment by stroomdev66** [comment]
For now it is probably best for us to set a max create time on a filter if somebody creates a filter by selecting specific streams

**Comment by stroomdev66** [comment]
Fixed as part of #2574

**Comment by stroomdev42** [comment]
Rechecking 
Using v7.0b155 (HS SBX) 
If checking Reprocess data:  in Create Processors dialog box this issue, does not occur.
