### ISSUE TITLE
Password Reset Request Failure

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2587]
Go to User/pass login screen, enter valid User Name and click `Forgot password?`.

URL changes to `<CorrectFQDN>/s/resetPasswordRequest`, showing blank white screen and no email is received.

**Comment by stroomdev10** [comment]
Work around:   Reset your password via the User screen.

**Comment by at055612** [comment]
Replaced by https://github.com/gchq/stroom/issues/4008
