### ISSUE TITLE
Case insensitive regex in `matches()` call causes stream processing slowdown

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#2591]
During processing a single feed (Stroom v7.1, built approx. 10 Oct 21), stream processing was significantly slower than expected, taking > 15 hrs to process streams of 1GB (uncompressed) data. A different feed was much faster to process. After analysing the Java call stack of one of the nodes, it appeared that 19 out of 20 processing threads were in a `BLOCKED` state, with `jstack` output similar to:

```
Blocked at:
Net.sf.saxon.regex.CaseVariants.getCaseVariants(CaseVariants.java:92)
– waiting to lock
Net.sf.saxon.regex.REMatcher.equalCaseBlind(REMatcher.java:715)
Net.sf.saxon.regex.Operation$OpAtom.iterateMatches(Operation.java:631)
…
Stroom.pipeline.filter.XsltFilter.endDocument(XsltFilter.java:282)
Stroom.pipeline.filter.AbstractXMLFilter.endDocument
Stroom.pipeline.filter.SplitFilter.endElement
```

During processing of the slow feed, CPU usage was no more than 8% of the host max. The faster feed processed faster, with near max CPU observed.

The key difference between the slow feed and the fast one, was the former had multiple (14) calls in series, to `matches($str, <regex pattern>, 'i')`, where `'i'` is the case insensitivity flag. Once we removed the `'i'` flag, processing rate and CPU usage increased significantly.

It appears the Saxon regex parser is blocking when case insensitivity mode is active.

**Comment by p-kimberley** [comment]
See this related Saxon issue that appears to be the cause of the locking: https://saxonica.plan.io/issues/4449

**Comment by at055612** [comment]
Closing this as it has been duplicated by #3850 and that now contains more detail.
