### ISSUE TITLE
beta.159 search is reporting a buffer underflow in the error popup

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2603]
Nothing in the logs
Can you suggest some debug?

**Comment by stroomdev66** [comment]
Unable to replicate waiting on stack trace

**Comment by stroomdev10** [comment]
possible related stack trace based on temporal alignment :)

[Buffer_Underflow.txt](https://github.com/gchq/stroom/files/7676035/Buffer_Underflow.txt)

**Comment by stroomdev10** [comment]
Stack attached

[20211216_Buffer_Underflow.txt](https://github.com/gchq/stroom/files/7728001/20211216_Buffer_Underflow.txt)
