### ISSUE TITLE
Search, error popup says java.lang.Error

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2611]
nothing in logs, trying to switch on error Consumer debug

had a bunch of reference data loads going on the node at the same time, search was very slow / hanging on Extractions

**Comment by stroomdev10** [comment]
attempting to recreate by clearing down the reference_data LMDBs, setting DEBUG and restarting

**Comment by stroomdev66** [comment]
Unable to replicate waiting on stack trace

**Comment by stroomdev10** [comment]
[Task_Terminated.txt](https://github.com/gchq/stroom/files/7661181/Task_Terminated.txt)
