### ISSUE TITLE
Search is slow when processing node is loading reference data

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2612]
Looking for confirmation that this looks like disk contention rather than some locking issue

Will attach stack traces from a proc node and UI too

**Comment by stroomdev10** [comment]
[proc_node_stack1.txt](https://github.com/gchq/stroom/files/7641989/proc_node_stack1.txt)
[proc_node_stack2.txt](https://github.com/gchq/stroom/files/7641991/proc_node_stack2.txt)
[proc_node_stack3.txt](https://github.com/gchq/stroom/files/7641993/proc_node_stack3.txt)
[proc_node_stack4.txt](https://github.com/gchq/stroom/files/7641996/proc_node_stack4.txt)
[ui_node_stack1.txt](https://github.com/gchq/stroom/files/7641999/ui_node_stack1.txt)
[ui_node_stack2.txt](https://github.com/gchq/stroom/files/7642000/ui_node_stack2.txt)
[ui_node_stack3.txt](https://github.com/gchq/stroom/files/7642002/ui_node_stack3.txt)
[ui_node_stack4.txt](https://github.com/gchq/stroom/files/7642003/ui_node_stack4.txt)

**Comment by stroomdev66** [comment]
Is this still the case?

**Comment by at055612** [comment]
It does look like disk contention.  Have checked that two LMDB envs (i.e. search and ref) can co-exist without blocking each other.
