### ISSUE TITLE
Reprocess is breaking on checkSuperseded

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2615]
I've reprocessed a bunch of FATAL Error'd streams

In the logs are ERRORs related to checkSuperseded.

[Superseded.txt](https://github.com/gchq/stroom/files/7649576/Superseded.txt)

In the Stream browser, the output Streams are showing as deleted with missing attributes

![ParentStream](https://user-images.githubusercontent.com/28703366/144602746-6358642e-882a-4b56-84ae-175fb4be9d06.jpg)
![OriginalError](https://user-images.githubusercontent.com/28703366/144602744-c6147895-848c-4eea-be40-4db4d4f0e021.jpg)
![Events](https://user-images.githubusercontent.com/28703366/144602742-f31a0482-e0ac-46af-986a-8f879283674b.jpg)

![DataPreview of Events](https://user-images.githubusercontent.com/28703366/144602735-d676fc16-1416-4c5b-9842-89105bd22710.jpg)

**Comment by stroomdev66** [comment]
Currently unable to reproduce missing file data

**Comment by stroomdev66** [comment]
Retest after next release
