### ISSUE TITLE
Table 'stroom.oauth_client' doesn't exist (on attempting to run stroom for the first time

### ISSUE THREAD

**Issue by gpeters86** [gchq/stroom#2662]
Version 7.01, beta 160. 
Receiving this error when trying to run start.sh.

I'm using mariadb for the databases. Everything is setup on a single server.

**Comment by at055612** [comment]
Stroom is written with MySQL in mind and we don't actively support MariaDB.

I just tried 7.0-beta.169 against a Maria 10.7.1 docker container and I don't see the error you mention but it is failing due to the collation `utf8mb4_0900_ai_ci` being unsupported on Maria.

I think you will need to switch to using MySQL instead.

**Comment by gpeters86** [comment]
Switched to mysql, did a complete rebuild to remove all the config muddling . still exact same error?
Have tried 5.6 and 5.7 mysql.

My main issue is I'm working completely offline, so can't just pull the docker prereqs live.

**Comment by at055612** [comment]
Stroom 7.0 (currently latest is  7.0-beta.175) is built around MySQL 8, though I appreciate the docs probably don't mention this.

Can you please explain how you are running stroom and what config you have changed from the defaults?  Are you running one of our docker stacks (https://github.com/gchq/stroom-resources/releases) or have you installed java + MySql and are running the stroom zip distribution from here (https://github.com/gchq/stroom/releases/tag/v7.0-beta.175)?

The docs are in a bit of a state at the moment but are currently undergoing work to tidy them up and remove all the legacy content.

This issue relates to #2724

**Comment by gpeters86** [comment]
> Stroom 7.0 (currently latest is 7.0-beta.175) is built around MySQL 8, though I appreciate the docs probably don't mention this.
> 
> Can you please explain how you are running stroom and what config you have changed from the defaults? Are you running one of our docker stacks (https://github.com/gchq/stroom-resources/releases) or have you installed java + MySql and are running the stroom zip distribution from here (https://github.com/gchq/stroom/releases/tag/v7.0-beta.175)?
> 
> The docs are in a bit of a state at the moment but are currently undergoing work to tidy them up and remove all the legacy content.
> 
> This issue relates to #2724

Thanks.

I've attempted numerous manual installs of Stroom. One thing I realise is I was trying to use MySQL5.6 at one point and perhaps I should try again with a clean build and use MySQL 8.

I've also tried using the docker stacks, as theoretically this will be the quickest way to get things running - 
With some versions I can get the stack "running" however the repeated "waiting for packet" messages tell me that it is unable to connect to DB, also the web GUI is only showing a stroom icon, no content. Health status is showing stroom as healthy, but stroom admin as unhealthy.

I've actually had a colleague produce for me a docker export .tar.gz from his working docker stack, which should contain all dependencies. Unfortunately it's telling me that config.yml could not be found, as well as not being found in the config-fallback directory. Possibly some mistake on his part when he produced the docker export, or he had configured it to look in a non-standard location for the config.yml.

My Docker skills aren't enough to 'inject' the missing config.yml file and can't seem to find the directory structure under /var/lib/docker. I am unable to run his docker package with /bin/sh or /bin/bash as the launch command, presumably because these parts are not included in the docker image.

I have gotten hold of a centos VM with web proxy access for further testing, so hopefully I can get things running there in a more forgiving environment, then repackage/export it to bring onto the airgapped system.

**Comment by gpeters86** [comment]
@at055612 
Hi , so I'm now attempting to setup in my Centos 7 VM, which is web connected, via a proxy.

Currently running 7.1-beta.9 , attempting to use the _core docker stack. Have installed docker & docker-compose successfully.

Just wondering if I need to configure the web proxy for stroom somewhere? 
Should I be using a stroomuser user account and chown everything as stroomuser:stroomuser ?  Or is all of this handled within the docker stack/config contained within?



Current output of ./start.sh or ./restart.sh:

`Using hostname ***** and IP address xx.xx.88.169 for audit logging.
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
[+] Running 0/0
 ⠿ stroom-proxy-local Error                                                0.0s
 ⠿ nginx Error                                                             0.0s
 ⠿ stroom Error                                                            0.0s
 ⠿ stroom-all-dbs Error                                                    0.0s
 ⠿ stroom-log-sender Error                                                 0.0s
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 131.185.81.86:53: no such host
`
