### ISSUE TITLE
b.168 Search Failing to return all results

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2664]
I haver a dashboard with 5x same queries that return 100,000 results each.

The queries run OK, and 4x queries  return 100,000 rows
One query returns ~40,000 results and no more (the query appears to be running from the stop/go button state)
There is nothing in Server tasks for the query.

No ERRORs in the logs

**Comment by stroomdev10** [comment]
Can't currently reproduce this

**Comment by stroomdev66** [comment]
Me neither
