### ISSUE TITLE
Pipeline Data view is slow to load when the `meta` table has many records

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#2679]
When a large number of `meta` entries exists in the database, attempting to view the "Data" tab of a pipeline causes a long-running query. Depending on configuration, UI timeouts may also occur.

In an environment where well over 1M streams are present, it was observed that the following query was taking several seconds to run, exceeding the client timeout limit:

```sql
select `m`.`id`, `f`.`name`, `t`.`name`, `p`.`processor_uuid`, `p`.`pipeline_uuid`, `m`.`parent_id`, `m`.`status`, `m`.`status_time`, `m`.`create_time`, `m`.`effective_time`
from `meta` as `m` straight_join `meta_feed` as `f` on `m`.`feed_id` = `f`.`id` straight_join `meta_type` as `t` on `m`.`type_id` = `t`.`id` left outer join `meta_processor` as `p` on `m`.`processor_id` = `p`.`id` where (`p`.`pipeline_uuid` = ? and `m`.`status` = ?)
order by `m`.`create_time` desc limit ? offset ?
```

In a dev environment with approximately 100k `meta` entries, the above query resulted in the following query plan output:
![image](https://user-images.githubusercontent.com/17559369/147902598-ba3cfe80-d9e9-4160-a2a2-40515342e74a.png)

Note the full table scan against the `meta_processor` table. This is causing significant slowdown.

Recommend creating an additional index against the column `meta_processor.pipeline_uuid`. Testing indicates this will result in the following improved query plan:
![image](https://user-images.githubusercontent.com/17559369/147902690-46cba9f1-2495-473a-85c4-30da07e326c3.png)

**Comment by stroomdev10** [comment]
Have you updated your table stats?

Thats often the cause of incorrect query plans.

FYI I've got an env with 4M rows on Meta and this isn't happening.

`analyze table meta;`

**Comment by at055612** [comment]
The index has been added in the v7.0 branch, awaiting merge or cherry picking up to master
