### ISSUE TITLE
Unable to Select Bespoke streamTypes in Pipeline Stream Appender

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2688]
Only the following streamType values are available for selection in a streamAppender within a pipeline:

- Error
- Events
- Raw Events
- Raw Reference
- Records
- Reference

Although `Test Events` is a valid type within `meta_type`, it is not available from the dropdown.  If editing the pipeline Source directly then the UI is unable to render it correctly.

**Comment by gcdev373** [comment]
Looks like `Detections` is also missing in that case.

**Comment by at055612** [comment]
Fixed in beta.172
