### ISSUE TITLE
Schema Pool misses seem high, please investigate

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2689]
Schema Pool 

Hit Rate = 57187
Miss Rate = 82024

Entries = 39

Total Load Time = 1148937316003

Recent processing has had the following issues, that may help identifying the issue

Warning from XSLT: Source document is in namespace records:2, but none of the templates match elements in this namespace.

Error from SchemaFilter: Invalid content was found starting with Element {Meta}. One of {EventTime} is expected

**Comment by stroomdev66** [comment]
Try enabling debug logging for `stroom.pipeline.cache.SchemaLoaderImpl` to see what is causing large numbers of failed schema loads.
