### ISSUE TITLE
It would be useful if an Index could list those searches/dashboards that use it as a data source

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#272]
It would be useful if an Index could have a tab that identifies which searches (and pipelines) are referencing it as a data source.

**Comment by burnalting** [comment]
This should be extended to most objects. For example it would be very useful to know which **Feeds** are using a given **TextConverter** or **XSLT Translation**

**Comment by stroomdev10** [comment]
Dependencies screen does this.
