### ISSUE TITLE
Offline step by step guide?

### ISSUE THREAD

**Issue by gpeters86** [gchq/stroom#2724]
I'm trying to setup stroom in an offline environment, and have been for some time. 
I'm not sure which documentation to follow as there seem to be 5 different guides, some of which are easily accessible and some buried in links of other guide parts. I've tried various versions from 5 to 7 and all have failed in some way.

I can pretty much bring any packages across that I need from outside, but it'd be useful if someone had a list of what is currently functioning and which install method they used (manual, docker, etc).

Thanks.

**Comment by stroomdev10** [comment]
We've got many different flavours of disconnected deployments working OK.

If you want a simple install, then just download the stroom binaries and run it on a single node.

If you want a full stack on a single node, then the stroom-stack might fit.  You'll need the docker containers which can either be download from dockerhub or saved from a connected machine that has run the stroom-stack. If you download from dockerhub, then you need to set the tags after loading.

For larger scale deployments, a mix of containerised services and stroom jars is pretty common.

As for versions, 7.0 , although in beta should work fine for you.  7.0-beta.175 is the latest version.

Let us know how you get on.

**Comment by at055612** [comment]
This stackexchange post links to a shell script which may be useful for downloading docker images if you do not have the `docker` binary on your internet connected machine.  I have not tried it so can't vouch for it.

The simplest installation (assuming you can get the right docker images into your local docker repo) is using our `stroom_core` or `stroom_core_test` docker stacks.  These are fine for single node installs or evaluations and remove the need to install MySQL/Java, but they obviously need docker and docker-compose.

Assuming you use either of those stacks then you will need to download the stack zip from [stroom-resources](https://github.com/gchq/stroom-resources/releases) and load these docker images into your local repo 
```
nginx gchq/stroom-nginx:v7.0-beta.2
stroom gchq/stroom:v7.1-beta.9
stroom-all-dbs mysql:8.0.23
stroom-log-sender gchq/stroom-log-sender:v2.2.0
stroom-proxy-local gchq/stroom-proxy:v7.1-beta.9
```

**Comment by gpeters86** [comment]
> We've got many different flavours of disconnected deployments working OK.
> 
> If you want a simple install, then just download the stroom binaries and run it on a single node.
> 
> If you want a full stack on a single node, then the stroom-stack might fit. You'll need the docker containers which can either be download from dockerhub or saved from a connected machine that has run the stroom-stack. If you download from dockerhub, then you need to set the tags after loading.
> 
> For larger scale deployments, a mix of containerised services and stroom jars is pretty common.
> 
> As for versions, 7.0 , although in beta should work fine for you. 7.0-beta.175 is the latest version.
> 
> Let us know how you get on.

@at055612 
Hi , so I'm now attempting to setup in my Centos 7 VM, which is web connected, via a proxy.

Currently running 7.1-beta.9 , attempting to use the _core docker stack. Have installed docker & docker-compose successfully.
(Edit - FWIW I have also tried using 6.0.36-12 - same error occurring, HOST_IP variable not set)

Just wondering if I need to configure the web proxy for stroom somewhere? 
Should I be using a stroomuser user account and chown everything as stroomuser:stroomuser ?  Or is all of this handled within the docker stack/config contained within?
Do I need to alter the config.yml?



Current output of ./start.sh or ./restart.sh:

`Using hostname ***** and IP address xx.xx.88.169 for audit logging.
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string. 
[+] Running 0/0
 ⠿ stroom-proxy-local Error                                                0.0s
 ⠿ nginx Error                                                             0.0s
 ⠿ stroom Error                                                            0.0s
 ⠿ stroom-all-dbs Error                                                    0.0s
 ⠿ stroom-log-sender Error                                                 0.0s
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 131.185.81.86:53: no such host
`

**Comment by at055612** [comment]
Is there a reason you are using 7.1?  I would recommend using 7.0 as 7.1 is a little bit cutting edge and not something we are actively testing yet.  Also I would initially recommend using the `stroom_core_test` stack.  This should work and pass health checks out of the box where as `stroom_core` requires some configuration to get it passing the health check.  Get the simplest thing working first then proceed from there.  

There seem to be a few things going on.

It looks like docker is unable to connect to its registry.  I suspect you need to configure docker to be aware of your proxy server https://docs.docker.com/network/proxy/.

When you run `./start.sh` it tries to establish the IP address of the machine and then uses this in the config. This is to deal with network comms from host to container and vice versa.  It looks like it is not able to detect what it is for some reason.  In that case you need to un-comment the line
```sh
#export HOST_IP=<enter you hostname here>
```
and set it to the value of your host's IP public address (not 127.0.0.1 or localhost) or if you have a dns server in place then you can set it to the FQDN.  Either value must be resolvable inside the docker containers.  If HOST_IP can be determined or is not manually set then lots of things will not work.

**Comment by at055612** [comment]
>Just wondering if I need to configure the web proxy for stroom somewhere?
Stroom should not need to call out to the internet so no.

>Should I be using a stroomuser user account and chown everything as stroomuser:stroomuser ? Or is all of this handled within the docker stack/config contained within?
 You don't need to run as a specific os user.  Normal practice would be to download the stack as a non-root user (that is a member of the docker group so it can use the docker cli without sudo), extract it somewhere and then run it.  No chmoding should be needed.

>Do I need to alter the config.yml?
If you are running up `stroom_core_test` then no changes should be needed in that file to get it working.

**Comment by gpeters86** [comment]
@at055612 @stroomdev10 

Hi again and thanks for all the assistance! I am almost there now, have traversed the docker/proxy issues that were holding me back.

Attempted to run up stroom_core_test-v7.0-beta.175 and had some startup errors. Wondering if I should just give another v7.0 variant a shot to see if it runs?

Attached the healthcheck.json below (which is a great sign, as the web server GUI stuff actually seems to be working)

[healthcheck.json.txt](https://github.com/gchq/stroom/files/7967339/healthcheck.json.txt)

**Comment by stroomdev10** [comment]
I'm running b.175 in multiple places OK, so I suspect it's an environmental issue.

What specific startup errors are you seeing?

**Comment by at055612** [comment]
@gpeters86 It looks like there is some network issue at play.  The remote proxy is trying to establish if the feed status check is working by sending a feed status check request.  As all services are running inside containers it can use the docker service name as the host, in this case `nginx` but for some reason it can't find the host.

The beta.175 release is fine.  That is the one we are currently running in a number of environments.  I also just fired up a fresh ubuntu host with just docker and docker compose on it, downloaded/unpacked the stack zip and ran start.sh.  It started fine with a clean healthcheck.  There must be something wrong with your environment that is causing this issue.

**Comment by at055612** [comment]
Closing due to no comments in a long time.
