### ISSUE TITLE
Active Task pane shows error for empty folders

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#2732]
SQL [select `processor_feed`.`name`, `processor`.`pipeline_uuid`, `processor_filter`.`priority`, `processor_task`.`status`, count(*) from `processor_task` left outer join `processor_node` on `processor_task`.`fk_processor_node_id` = `processor_node`.`id` join `processor_feed` on `processor_task`.`fk_processor_feed_id` = `processor_feed`.`id` join `processor_filter` on `processor_task`.`fk_processor_filter_id` = `processor_filter`.`id` join `processor` on `processor_filter`.`fk_processor_id` = `processor`.`id` where (false or false) group by `processor`.`pipeline_uuid`, `processor_task`.`fk_processor_feed_id`, `processor_filter`.`priority`, `processor_task`.`status` limit ? offset ?]; Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'stroom.processor_feed.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by at055612** [comment]
Fixed in > 7.0-beta.175
