### ISSUE TITLE
It appears only the active tab is saved when editing an TextConverter

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#274]
Reproduce by
- create a new Text Converter
- select the Conversion Tab
- author a Text Conversion translation
- select the Settings Tab
- select the Text Converter Type
- press Save icon
- select the Conversion Tab and identify you have lost your translation

**Comment by stroomdev66** [comment]
Is this is beta.20 as there has been a change in this area?

**Comment by burnalting** [comment]
Yes, it it Beta.20.

**Comment by stroomdev66** [comment]
This may have been some of what was experienced by users when raising issue #212.
