### ISSUE TITLE
DBSearch Tasks provide no detail in Server Tasks pane

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2751]
Something useful like which store is being queried?

**Comment by at055612** [comment]
Changing the task name to be `XXX Search` where XXX is the searchable name, e.g. Meta Store or Processor Tasks.  Also ensuring the info is populated

![image](https://user-images.githubusercontent.com/22818309/152558625-414ea66c-a529-40c2-a48b-30c217ba2fd3.png)

**Comment by at055612** [comment]
Fixed in b.178
