### ISSUE TITLE
Autologging not configured - PipelineResourceImpl

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2758]
Remote resource PipelineResourceImpl is not properly configured for auto logging.  Before operation object will not be available

**Comment by gcdev373** [comment]
This happens when structure changed in XML edit mode.  
Logging is actually inadequate for pipelines in general - structure and parent not recorded.
will fix.

**Comment by gcdev373** [comment]
Fixed on branch `7.0`
