### ISSUE TITLE
Using custom CA/SSL certificates with docker

### ISSUE THREAD

**Issue by gpeters86** [gchq/stroom#2771]
Currently testing/setting up with 7.0beta173 docker build.

Just looking for assistance on how to get custom certificates running (signed by my network's CA)

Tried replacing the files in /volumes/nginx/certs and /certs , but it doesn't look like whatever I'm doing is correct - 

`"stroom.proxy.app.handler.RemoteFeedStatusService": {
 "healthy": false,
 "message": Error sending request request DUMMY_FEED - dummy DN to https://nginx/api/feedStatus/v1/getFeedStatus: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",`

Documentation has numerous sections relating to SSL certs but not sure which are relevant. One mentions setting up keystore with java, Is this still relevant for docker build?
eg - if I use my custom certs for the java keystore, but the default certs are still in the /certs & /volumes/nginx/certs directories.
(also: java ImportKey gives class not found)

**Comment by stroomdev10** [comment]
I assume you're using stroom_core you need:

/volumes/nginx/certs/ca.pem.crt
/volumes/nginx/certs/server.pem.crt
/volumes/nginx/certs/server.unencrypted.key

/volumes/stroom-log-sender/certs/ca.pem.crt
/volumes/stroom-log-sender/certs/client.pem.crt
/volumes/stroom-log-sender/certs/client.unencrypted.key

/volumes/stroom-proxy-local/certs/ca.jks
/volumes/stroom-proxy-local/certs/client.jks

The error you are seeing is related to the stroom-proxy-local checking the status of the feed in stroom (via nginx) so you've likely got a mismatch between the stroom-proxy-local client.jks and the nginx ca.pem.crt

I think /certs is irrelevant in this scenario

**Comment by gpeters86** [comment]
> I assume you're using stroom_core, so you need:
> /volumes/nginx/certs/ca.pem.crt /volumes/nginx/certs/server.pem.crt /volumes/nginx/certs/server.unencrypted.key
> /volumes/stroom-log-sender/certs/ca.pem.crt /volumes/stroom-log-sender/certs/client.pem.crt /volumes/stroom-log-sender/certs/client.unencrypted.key
> /volumes/stroom-proxy-local/certs/ca.jks /volumes/stroom-proxy-local/certs/client.jks
> I think /certs is irrelevant in this scenario

Thanks for that.
I will move the second set of keys/certs from /certs to /volumes/stroom-log-sender/certs

As for the java keystore - where do I run "java KeyImport"? Which docker container should I send that command to?
Or alternately - what is the location of the stroom-util*.jar in the docker containers? (doesn't seem to be in the base stroom_core directory/subdirectories)

**Comment by stroomdev10** [comment]
use `openssl` to convert pem to pkcs12
use `keytool` to convert pkcs12 to jks

you don't need any Stroom stuff to do this.

**Comment by gpeters86** [comment]
> use `openssl` to convert pem to pkcs12 use `keytool` to convert pkcs12 to jks
> 
> you don't need any Stroom stuff to do this.

Thanks again. One final question (or 2)
1) does client.jks imply that the jks file is built out of the client.pem.crt in stroom-log-sender? Or should it be a separate cert for the stroom-proxy-local server?

2) How do I build ca.jks without the key to my CA? or do I actually need to include my CA's key ? Or is the ca.jks file irrelevant (you mention mistmatch before between client.jks and nginx's ca.pem.crt being probable cause)

**Comment by stroomdev10** [comment]
1. It can be any client cert, it doesn't *have* to be the same one, but it could be. 
2. `ca.jks` is a trust store, it just stores the public key of any CA that you trust. No CA private key is required.
3. `env.sh` is legacy and not used. client jks password is specified in `.../volumes/stroom-proxy-local/config.yml`

**Comment by gpeters86** [comment]
> 1. It can be any client cert, it doesn't _have_ to be the same one, but it could be.
> 2. `ca.jks` is a trust store, it just stores the public key of any CA that you trust. No CA private key is required.
> 3. `env.sh` is legacy and not used. client jks password is specified in `.../volumes/stroom-proxy-local/config.yml`

Thanks again.

So just to clarify (I'm still getting an unknown host exception for 'nginx' during feedstatus checks, while running start.sh or restart.sh). Nginx, stroom-proxy-local, stroom-log-sender are showing stopped/unhealthy.

Action taken:
-create 2x certificates on windows CA - export as pfx/p12
-export CA certificate from CA. link to:
/volumes/nginx/certs/ca.pem.crt
/volumes/stroom-log-sender/certs/ca.pem.crt
/volumes/stroom-proxy-local/certs/ca.pem.crt

-convert the server pfx file into separate certificate & unencrypted private key, link to /volumes/nginx/certs/server.pem.crt & server.unencrypted.key

-convert the client pfx file into client certificate, and client unencrypted private key. link to /volumes/stroom-log-sender/certs/client.pem.crt & client.unencrypted.key

- use keytool to create ca.jks and client.jks from the ca & client pfx/p12 files. link to /volumes/stroom-proxy-local/certs/ca.jks & client.jks

the alias for client.jks is set to 'client' as in the self-signed example provided.
the alias for ca.jks is set to 'ca' as in the self signed example (should this be my CA's name?)
the subject alternate information for the new server certificate was copied from the self-signed version provided (eg DNS = nginx, DNS = stroom-log-sender, DNS=localhost.localdomain, DNS=stroom, etc etc etc.)

Apologies for not providing an actual health check/error report yet, I need to do some finessing to get it off my network in terms of higher ups approvals etc.

**Comment by stroomdev10** [comment]
First thing would to get nginx to start.

you can do `start.sh nginx`. to just start the nginx container

`logs.sh nginx` works too whilst it is running

you can also do `docker logs nginx`

**Comment by gpeters86** [comment]
> First thing would to get nginx to start.
> 
> you can do `start.sh nginx`. to just start the nginx container
> 
> `logs.sh nginx` works too whilst it is running
> 
> you can also do `docker logs nginx`
> 
> Hopefully this will point to why nginx isn't starting

Hi, thanks again.

I managed to talk to a couple of local stroom users yesterday and we stepped through the certificate issues (mostly).
The core issue was that I was using symlinks to the certificates - copying the actual files into: 
/volumes/nginx/certs
/volumes/stroom-log-sender/certs
/volumes/stroom-proxy-local/certs
/volumes/stroom-proxy-remote/certs

Got things running to the point where nginx will start. I can also now send https data across the network via the curl command.
I'm still getting issues with feedstatus responding 400.

Wondering if this is an API Key issue - 
according to https://gchq.github.io/stroom-docs/7.0/docs/install-guide/configuration/configuring-stroom-proxy/

API key needs to be set. 
Should I be using the default API key that came generated already in the stroom interface? 
Or should I be creating a new one ? (In which case, for which user? admin?)

**Comment by stroomdev10** [comment]
Tools->Users - create a User called `proxyFeedCheck` tick `Inactive` 
Tools -API Keys - create an API Key for user `proxyFeedCheck`, copy the API key
edit `.../volumes/stroom-proxy-local/config/config.yml`. add the API key from above to `proxyConfig:/feedStatus"/apiKey:` 

If the API key is not set then the proxy cannot determine if the feed exists, so it accepts data for any feed.
If the feed specified does not exist then that ingested data cannot be processed by Proxy Aggregation and stays in the proxy repo and never makes it into Stroom.  If the feed exists, then the data makes it through OK.
