### ISSUE TITLE
Change dashboard play/pause/resume/stop behaviour

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#2778]
When you pause the search you could easily go to resume and accidentally start a new search if it finishes just as you click it. Also when it is paused and completes the tables and vises never update to show the final results unless you refresh them individually (not sure the vises can be refreshed with final data at all).

It would be much neater if each result component (table and vis) had it's own pause button just so you could stop it long enough to select something etc. Components could be paused for as long as the user needs even if a new search starts. Resuming would allow the component to get the latest data. Paging would have the effect of resuming as results are not held client side.

Having pause as in independent thing means the play/pause/stop buttons could just be one button that is play/stop.

**Comment by stroomdev66** [comment]
See also gh-2971

**Comment by p-kimberley** [comment]
Search "pause" functionality poses a problem for Elasticsearch searches. If a search is paused, the Elasticsearch query scroll context will expire after a pre-defined period of inactivity, causing the context to be lost and subsequent attempts to resume the query, to fail.

We might want to have a way of disabling pause functionality for data sources (like ES) that don't support it - or somehow have results continue to stream into the result store in the backend, invisible to the user.
