### ISSUE TITLE
Add ace editor vim bindings as a user preference

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#2780]
Currently using vim bindings in the ace editor is done via the right click menu in the editor.  It would be better if this could be set at the user level, then maybe overridden at the editor instance level if required.

Also if we are adding vim bindings as a user pref it would be good to add a pref for mapping `jk` to `<Esc>` and maybe `kj` too.
In the editor you can do `:imap jk <Esc>` so presume this can be done programatically too.

Or maybe have a user pref that takes a list of key mappings to allow the user to add in any maps that ace can support, though may need to be sure that sending user input direct to the ace code like this doesn't introduce a vulnerability.

**Comment by at055612** [comment]
This would seem to do the trick for adding a mapping

```js
editor.setKeyboardHandler('ace/keyboard/vim');

ace.config.loadModule('ace/keyboard/vim', function(module) {
   var VimApi = module.CodeMirror.Vim;
   VimApi.map('jk', '<Esc>', 'insert');
});
```

**Comment by stroomdev10** [comment]
vi > vim

**Comment by at055612** [comment]
Was added in 7.2
