### ISSUE TITLE
Setting assignTasks to null breaks config properties / shows SQL errors 

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2782]
The last part (Multiple values) only happens in a clustered

In the properties screen filter for `stroom.processor.assignTasks`

tick `Set Database value`
press `OK`
Error popup shows horrible message including `Message: null`
press `Close`
press `OK`
another SQL error pops up
press `Close`
press `Cancel`

--only on a clustered env--
Edit the assignTasks property again, and there is an Yellow triangle against the Node effective value indicating `Multiple values`
Click on the yellow triangle
Only the UI node shows a value which is blank

**Comment by at055612** [comment]
Fixed in b.184
