### ISSUE TITLE
Dashboard Query will error if a viz is attached, but not specified

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2806]
Create a Query against 'Processor Tasks' datastore

Create a table referencing the above

Attach a visualisation to the dashboard , specify the table, but do not select a viz

run the query, error pops up saying 

`Cannot invoke "stroom.query.api.v2.TableSettings.getFields()" because "child" is null`

**Comment by at055612** [comment]
Problem is, I think, in this code
```java
        final TableSettings child = tableSettings.get(tableSettings.size() - 1);

        fields = child.getFields();
```
in `stroom.query.common.v2.FlatResultCreator`

**Comment by at055612** [comment]
Fixed in >beta.191
