### ISSUE TITLE
Manage Accounts screen generates  SQL error

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2840]
Open Tools->Users
Add a Quick Filter term e.g. admin
Click on Status column to sort
Error below appears

<img width="830" alt="image" src="https://user-images.githubusercontent.com/28703366/164429743-57cd7c5d-eaeb-47b3-b0bd-5939b9634cfb.png">

**Comment by stroomdev10** [comment]
Also not sure sorting by Status actually works anyway

**Comment by stroomdev10** [comment]
Also this...
<img width="830" alt="image" src="https://user-images.githubusercontent.com/28703366/164430737-5f5f13e4-d241-4bd1-9e31-98cadf4715e8.png">

**Comment by stroomdev10** [comment]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/28703366/164431008-553b2ed1-ce68-4217-adfd-0d1e17bde67c.png">

**Comment by stroomdev10** [comment]
Also I sometimes get 

`Error, Status undefined, Msg: undefined`

**Comment by at055612** [comment]
Fixed in > beta.199
