### ISSUE TITLE
API Keys page raises Errors when sorting

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2841]
Add a quick filter to the API Keys page
click on various column headings to sort
<img width="830" alt="image" src="https://user-images.githubusercontent.com/28703366/164432205-38bfd0b7-55e9-458e-8bb1-0d506eb4eabe.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/28703366/164432614-e1cbe506-5c38-4bb2-beec-31cb700012e4.png">

**Comment by at055612** [comment]
Fixed in > beta.199
