### ISSUE TITLE
Data Preview Being Too Clever When It Thinks It Sees XML

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2867]
v7.0-beta.203
Upload source data in a single file:
`A,B,C,D`
`E,F,G,H`
`I,J,K,L`
Data Preview is as expected.

Upload source data in a single file:
`A,B,C,D`
`E,F,G,<OOPS>`
`I,J,K,L`

Data Preview gets confused and displays:
`A,B,C,D`
`E,F,G,<OOPS>I,J,K,L`

View Source still works as expected.

**Comment by at055612** [comment]
Fixed in >7.0.1
