### ISSUE TITLE
Track reprocessed stream ID in `meta` to allow for later cleanup

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#2875]
# Problem
Indexing pipelines currently don't have an automated way of cleaning up reprocessed `Event` streams. This often leads to data duplication within the target index, impacting search results.

While manual cleanup of reprocessed stream data is possible, it is a cumbersome process.

# Recommendation
Track the ID of the reprocessed stream in `meta`. This would enable indexing and other pipeline elements to implement appropriate cleanup logic.

**Comment by at055612** [comment]
Based on discussions with @p-kimberley and @66 we think the way forward is as follows:

Create a new db `meta_destination` table of the form:

```sql
id -- surrogate autoincrement id
meta_id -- the stream id with a FK to the meta table
destination_type varchar -- a name for the type of destination, e.g. elastic, lucene, etc.
destination_identifier varchar -- an identifier within the scope of the destination_type and only understood by the destination service.
create_ms -- time record is create
create_user -- user that triggered the creation of the rec, e.g. the user attributed to the pipe process. 
```

The processing of a single stream would create 0-many records in this table depending on whether it sent any data to a supported destination, e.g an elastic index.  If it sends to multiple `destination_identifier`s within a `destination_type`, e.g. multiple elastic index names, then you would have one record per `destination_identifier`.

A record would be written **prior** to sending to the destination as it is preferable to have a record of something that was never sent than the other way round.  Keeping an in memory set (pipeline scoped) of the identifiers already recorded is wise to reduce the trips to the db.  

The table has a FK to the `meta` table to ensure that meta records cannot be physically deleted without dealing with these meta_destinations first.

A new periodic job would run that would join logically deleted `meta` rows to the `meta_destination` to identify items that need to be processed.  Likely this job would be fairly frequent to ensure it runs soon after the logical delete.  Each identified row would be passed to a service for the destination_type.  We need some interface then we can use a guice map binder to bind to impls by destination type.

The destination specific service would be responsible for reading/writing the rows in `meta_destination`.  If the identifier  is not primitive then it could be json to support a complex key but the service would have to handle the (de)ser.  The service can then call out to the destination to delete anything it needs to for the given `meta_id`(s) on each `destination_identifier`.

Physical deletion of meta would need to ensure it doesn't delete rows that are in the meta_destination table, either via the FK or pre-preemptively.

Failure conditions need thought, i.e. what do we do if we can't connect to the destination call delete on it.  Do we just try again next time round or track a retry count in the table as an extra col?  Some failures may be ignorable, e.g. if the destination can't find the identifier.
