### ISSUE TITLE
Fatal error: "Expected a new writer but got the same one back!!!" IndexingFilter line 220

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#288]

**Comment by stroomdev66** [comment]
For now I'm changing the fatal error to a warning as this condition might be ok and not fatal after all.

I need to know what happened just before the error so please turn on debug logging for the IndexShardWriterImpl and IndexShardWriterCacheImpl and keep a look out for the warning.
```
  <logger name="stroom.index.server.IndexShardWriterImpl">
    <level value="debug"/>
  </logger>
  <logger name="stroom.index.server.IndexShardWriterCacheImpl">
    <level value="debug"/>
  </logger>
```

**Comment by stroomdev10** [comment]
Still happening in beta 28
