### ISSUE TITLE
Orphaned proc filter when pipeline is deleted in the UI

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2889]
A working pipeline with an enabled proc filter is deleted in the UI

This leaves the enabled proc filter which errors continuously in `stroom.processor.impl.ProcessorTaskManagerImpl`
`Error processing filter with id = nnnn for pipeline xxxx-xxxx-xxxxxx`

Deleting a Pipeline can leave hanging processor and processor_filter rows

**Comment by at055612** [comment]
Code change so far logically deletes the processor, processor filters and any unprocessed tasks.  Question still remains about when these items get physically deleted.  Do we need a new clean up job to do it.

**Comment by at055612** [comment]
Fixed in >7.0-beta.207
