### ISSUE TITLE
<xsl:import> getting confused

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2937]
b.212
Create an XSLT with the line `<xsl:import href="xxx"/>`
Create two XSLTs both named `xxx`.
Step main XSLT and get the error `FATAL XsltPoolImpl - java.io.IOException: Found 2 resources for : "xxx"`
Rename one of the `xxx` XSLTs.
Restep main XSLT and same error occurs despite only one instance of `xxx` present.
Delete the previously renamed `xxx` XSLT
Restep main XSLT and same error occurs despite only one instance of `xxx` present.
Works fine if href is changed to the uuid but then impossible to lookup uuid to name from UI.

**Comment by stroomdev00** [comment]
Actually seems to be a caching issue.  Clearing the XSLT cache solves the problem.

However, deletion or renaming of an XSLT should really cause the cache to update.

**Comment by at055612** [comment]
Fixed in >7.0.1
