### ISSUE TITLE
Allow Cache configuration to be more dynamic

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2992]
Currently caches can only be configured at startup.

It would be useful to allow an admin to modify the cache configuration. e.g. TTI times or max size

**Comment by at055612** [comment]
Should be doable but will mean the cache would have to be recreated using the new settings, i.e. clearing the cache.
The cache screen would probably need some kind of re-build icon at the cluster and node levels, which would recreate the cache using the currently configured settings.

**Comment by at055612** [comment]
Fixed in >7.0.2
