### ISSUE TITLE
UI in Stroom Beta 28 has mixed mode UI issues with latest Chrome and Firefox

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#300]
When connecting to Beta28 via https using certificates, one gets the error below. This is for a single node stroom instance. A similar error occurs from the latest firefox as well.
![image](https://cloud.githubusercontent.com/assets/10084635/26295249/548d32e4-3f0c-11e7-9128-dec829302204.png)

The Chrome console shows

Mixed Content: The page at 'https://stroomsingle.swtf.dyndns.org/stroom/' was loaded over HTTPS, but requested an insecure script 'http://stroomsingle.swtf.dyndns.org:9876/recompile-requester/stroom'. This request has been blocked; the content must be served over HTTPS.
injectScriptTag @ stroom.nocache.js:54

Reverting back to beta27 works without the error.

**Comment by stroomdev66** [comment]
Sorry - bad build. Hopefully fixed now.
