### ISSUE TITLE
Test Window is truncating events for display, but this causes failures when using a Display pipeline

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3011]
Text Window is truncating Events for display, fair enough, however if one adds a display pipeline to the window the pipeline fails due to bad XML caused by the truncation.

**Comment by at055612** [comment]
Changed it so it now truncates the output of the pipeline, not the input, if there is a pipeline in place.

**Comment by at055612** [comment]
Fixed in >7.0.1
