### ISSUE TITLE
Raw Event Data Preview not displaying correctly for LF-terminated lines 

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#3015]
A series of line-feed separated lines of source data display as a single long line within `Data Preview` although `View Source` and stepping show the lines correctly formatted.

**Comment by at055612** [comment]
Can you provide a few lines of some example raw data pls

**Comment by stroomdev00** [comment]
Raised in error.  Problem is actually because data is incorrectly parsed as XML.  Previously raised as #2867.
