### ISSUE TITLE
Add dashboard field search suggestions and type hints

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#3039]
# Field suggestions
Currently field suggestions are limited to certain scenarios like feed names. It would be useful if search-as-you-type suggestions were implemented for search providers such as Elasticsearch, where such functionality already exists via the API.

The main benefit would be reduced guesswork when creating search queries as a list of terms will be provided dynamically based on the user's entered text.

# Dashboard query field type hints
Additionally, some users have reported difficulty with identifying the data type of dashboard query fields and how to format query values. The data type of each field should be indicated to the user, along with guidance on how to use such fields. While documentation is available online, having quick tips available at the point of entry would be more accessible.

**Comment by p-kimberley** [comment]
At this stage, basic [terms-based Elasticsearch suggestions](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#term-suggester) have been implemented, as these do not require any special index mappings. A future extension point could be to allow per-field customisation of suggestion logic to enable more sophisticated forms like phrase suggesters.

**Comment by at055612** [comment]
@p-kimberley can this be closed now?
