### ISSUE TITLE
Expose stream attributes in XSLT

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#306]
It would be useful to be able to query stream attributes in the XSLT.

e.g. Stream Type

**Comment by burnalting** [comment]
Can we close  #258 in favour of this more generic enhancement request?

**Comment by stroomdev66** [comment]
Added a stroom `meta` XSLT function. The XSLT function now exposes `Feed`, `StreamType`, `CreatedTime`, `EffectiveTime` and `Pipeline` meta attributes from the currently processing stream in addition to any other meta data that might apply. To access these meta data attributes of the current stream use `stroom:meta('StreamType')` etc. The `feed-attribute` function is now an alias for the `meta` function and should be considered to be deprecated.
