### ISSUE TITLE
Index Volumes screen limit issues

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3063]
If I specify a limit of 1.9T, then the limit is shown as 1.8T

**Comment by at055612** [comment]
The issue seems to be that the conversion of an IEC byte size string <=> bytes is no reversible as when you convert back from bytes it is always flooring the value to 1 decimal point.  This leads to a potential  reduction of the value each time you convert.

**Comment by at055612** [comment]
Fixed in >7.0.3
