### ISSUE TITLE
Set Strict-Transport-Security header in HTTPS web server

### ISSUE THREAD

**Issue by dfencegit** [gchq/stroom#3066]
An issue is raised against the Stroom web server when scanned with Nessus around the lack of the Strict-Transport-Security header not being set.

Can this be enabled, either as an option or by default?

**Comment by at055612** [comment]
Thanks for raising this.  The proposed change means Stroom will set the header with a value of `max-age=31536000; includeSubDomains; preload` on all responses.  This is configurable but will be the default.
