### ISSUE TITLE
Stream browser defaulting to UTF8 when using a custom Raw Stream type

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3084]
I have narrowed down our data encoding issue in Stroom7 as mentioned above for Windows Sec events to be related to Stream Type. If I import using "Raw Events" everything works as expected. When I import using "<Customer> Raw Events" which we use I 100% always get the "Unable to display source [12345:1:1] as text - Error fetching data: unable to decode a UTF-8 character....." error. No matter what data encoding I try it ALWAYS thinks it's UTF-8 and it's not, it is UTF-16LE and flushing the Feed Doc Cache makes no difference. It looks like the change to data encoding isn't registering for anything other than "Raw Events".
We have all of events set to "<Customer> Raw Events" so this is a problem for us. Is there something we can do to fix this or is there an underlying change required?

**Comment by at055612** [comment]
Have added a new property `stroom.data.meta.rawMetaTypes` to categorise stream types as being types for receipt of _raw_ data.  Any types included in this property will use the Data Encoding value set on the feed.

Thus if you have a custom stream type `Custom Raw` you need to add this value to both `stroom.data.meta.metaTypes` and `stroom.data.meta.rawMetaTypes`.

**Comment by at055612** [comment]
Showing utf32 data with a custom stream type

![image](https://user-images.githubusercontent.com/22818309/200002042-c5af9c26-4f48-4812-b099-9d958f43a565.png)

Showing the info tab that now displays the encoding (from the feed settings and appropriate to the stream type)

![image](https://user-images.githubusercontent.com/22818309/200002319-42614cc0-36dc-4c86-a715-dd641473ead5.png)

**Comment by at055612** [comment]
Fixed in >v7.0.6
