### ISSUE TITLE
Content Import "Enable processors" defaults review

### ISSUE THREAD

**Issue by DS177** [gchq/stroom#3101]
When importing content into Stroom the import Window has has the "Enable Processor Filters" on by default and the date field is unpopulated.  Presumably this means that all streams in the defined Feeds will be processed in the imported pipeline processors. We think this is a somewhat dangerous setting as it could easy lead to accidentally set off a large processing load by forgetting to change these settings when importing.
We think it would be preferrable to have the "Enable Processors" unselected as the default, or at least have the date/time set to (now) rather than blank.

**Comment by p-kimberley** [comment]
Leaving the option `Enable Processor Filters` as unchecked (the default) on import, while also leaving the next option as the default (set to the current time) results in all imported processor filters being enabled. The only way to avoid processor filters being automatically enabled is to clear the date field - however this results in the filters not being created at all. Potentially confusing.

It would be more logical if processor filter enabled state matches the option `Enable Processor Filters`.

Tested against 7.1 branch.
