### ISSUE TITLE
Ability to copy a pipeline processor

### ISSUE THREAD

**Issue by DS177** [gchq/stroom#3108]
When developing a pipeline or just doing some testing, the need to recreate pipeline processors with essentially the same filter becomes tedious rather quickly, especially if the filter is complex.
A quick copy of an existing filter and then minimal tweaking (if required) would save a lot of time and frustration.

**Comment by p-kimberley** [comment]
Merged into `master` already, but not the `7.0` branch. See:

* #2376 
* #2643
