### ISSUE TITLE
Property Screen property edit popup is not wide enough in same cases

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3141]
When editing a property with a short name e.g. stroom.node.name. the popup is not wide enough, suggest we have a minimum width

**Comment by at055612** [comment]
Screen grab of the problem.  

![image](https://user-images.githubusercontent.com/22818309/208405522-eaeae60b-dd2c-4d4a-a3fb-25ac376c0be2.png)

![image](https://user-images.githubusercontent.com/22818309/208405664-631a2526-189a-49b0-ae7b-914519fed907.png)

**Comment by at055612** [comment]
Fixed in > 7.1-beta.17
