### ISSUE TITLE
Dark 2 Mode feedback

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3150]
- Deleted Icon (dustbin) isn't visible enough when you have deleted streams
- Tick boxes outline on Stream browser is too similar to the light grey alternate line shading
- Tools->Monitoring Icons aren't colour whereas most others are
- User->Change password and User popup buttons use a different blue to the rest of the theme
- Pane height adjusters on Dat Browser aren't visible
- Spinners look a bit rubbish/blocky/too light
- It's not obvious which tab is currently being viewed
- There is a small grey square (12.x12) bottom right of the top pane in Stream browser

I don't have an decent (IPS) screen, so maybe this is causing issues

**Comment by at055612** [comment]
I think we need new icons for XSLT and XSD.  They don't really work on a dark bg and are a bit inconsistent with the style of most other icons.

**Comment by at055612** [comment]
Regarding 
>Tools->Monitoring Icons aren't colour whereas most others are
Could we just make them all blue, as the majority of the menu icons are blue?

**Comment by at055612** [comment]
Can't really see the delete button on selected rows on the Caches screen.  

![image](https://user-images.githubusercontent.com/22818309/211350330-a853a8ae-1aba-45f8-be51-86554f927788.png)

Similar problem on the Data retention screen

![image](https://user-images.githubusercontent.com/22818309/211350598-705e64a1-db80-4d14-be87-04efa21e0fc0.png)
