### ISSUE TITLE
User Task Manager terminate buttons are grey in dark mode

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#3159]
Branch: 7.1.

The user Task Manager dialog doesn't render well in dark mode:
![image](https://user-images.githubusercontent.com/17559369/209951447-5bd47b46-8fed-468d-88f9-201385f285d0.png)

Text is not wrapped and the "terminate" buttons are greyed out.

**Comment by at055612** [comment]
Fixed in > v7.1-beta.17
