### ISSUE TITLE
Using expression field picker is difficult with large field count

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#3163]
When there is a large number of expression fields available, such as with an index, finding the desired field is time consuming as there is no way of filtering the list.

Ideally the user would be presented with a text box with which to narrow down the list to those field names containing the entered characters.

# Example
![image](https://user-images.githubusercontent.com/17559369/210230671-4abbf926-1a4c-41e3-92f3-f982af9f8ee9.png)

**Comment by at055612** [comment]
Fixed in > v7.1-beta.18
