### ISSUE TITLE
Export of multiple Streams results in a zip file that cannot be imported to another Stroom instance

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#3166]
The following is an example of exporting 15 raw event streams, that when one attempts an import, the import process identifies that the exported file is malformed with respect to an import operation. The following show the attempted import of a file that was just exported from a stroom instance. 

![image](https://user-images.githubusercontent.com/10084635/210732507-36e1635b-6729-47f7-b9b9-bf43daff5f54.png)

**Comment by at055612** [comment]
Fixed in > v7.1-beta.17
