### ISSUE TITLE
Active Tasks tab doesn't show any detail in the 'i' icon on the lower pane in certain circumstances

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3220]
Certainly when the source meta is locked, nothing is displayed

There may be others

**Comment by at055612** [comment]
It was filtering on status == unlocked.  Also was only showing the tooltip if a meta row exists

![image](https://user-images.githubusercontent.com/22818309/215849694-5ed933ce-f655-4f5c-ba0d-039a7e5745f8.png)

**Comment by at055612** [comment]
Fixed in >7.0.19
