### ISSUE TITLE
STROOM_USER-EVENTS is logging TaskResourceImpl.terminate

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3270]
This is not a User level event, so not sure why it is being logged.

Should we be logging any INTERNAL_PROCESSING_USER level stuff here?

**Comment by at055612** [comment]
Changing it to ignore any requests attributed to the processing user.  In this instance, terminate can be called by users and proc user.

**Comment by at055612** [comment]
Fixed in >7.0.24
