### ISSUE TITLE
Feature Request - Data Stepping Pipeline showing when/where filter applied

### ISSUE THREAD

**Issue by stroomdev33** [gchq/stroom#3293]
As agreed with @66, raising feature request.

Something in the UI to show when a filter is applied to the pipeline element when stepping through data.
![image](https://user-images.githubusercontent.com/30118901/223680152-65af174e-22f2-44da-998f-fc4cf5ac34ba.png)

In particular - a user will want to know where, on what pipline elements a filter is applied.
A simple check on a pipeline element to show some filter is applied however, could be extended to show eg different icon depending on filter types. ie xpath contains/is exactly, show > ERROR, and so on.

**Comment by at055612** [comment]
Closing as covered by #3412

**Comment by at055612** [comment]
Fixed in >7.2-beta.32
