### ISSUE TITLE
changes to stroom.ui.theme.backgroundColour via the UI are not respected

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3356]
even through a reboot.

I assume it is meant to change the Navigator background

**Comment by stroomdev66** [comment]
Use the following properties to customise the environment:
`stroom.ui.htmlTitle` set the browser tab text, e.g. set to `Production`
`stroom.ui.theme.pageBorder` to add a page border, e.g. `border: 5px solid green;`
