### ISSUE TITLE
Opening a pipeline structure returns a 500 in the browser

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3360]
`/api/pipeline/v1/fetch/fetchPipelineData 500 (Internal Server Error)`

I also get an error popup 
`stroom.docstore.api.DocumentNotFoundException: Document not found: DocReft{type='Pipeline',uuid=blah, name=null}`

not sure if the upgrade from 7.0 to 7.2 broke this, will check the backups

**Comment by stroomdev66** [comment]
Unable to replicate
