### ISSUE TITLE
Internal Searchable Items hang off Favourites if you have them in the Explorer

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3372]
they should hang off System

related stack attached
[2023-04-11_Explorer.txt](https://github.com/gchq/stroom/files/11210081/2023-04-11_Explorer.txt)

**Comment by stroomdev66** [comment]
Possibly fixed by gh-3383

**Comment by stroomdev10** [comment]
Not fixed by https://github.com/gchq/stroom/issues/3383

**Comment by stroomdev66** [comment]
Unable to reproduce
