### ISSUE TITLE
Stepping Filters, improve visibility

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3412]
If we have a stepping filter enabled then it would be helpful if the filter icon on the main stepping page could indicate this.

Also on the Change Filters screen, it would be helpful if Stroom showed which element has an active filter set, as currently you have to click each one in turn to find out what is set.

**Comment by at055612** [comment]
We could display a little filter icon next to each element with one applied, possibly with a hover tip on it that describes the type of filter, e.g. xpath/output/severity.

**Comment by at055612** [comment]
This also relates to #1941, in that we need to visually identify which elements have errors on them so the user can see where the error is occurring.

**Comment by at055612** [comment]
Fixed in >7.2-beta.32
