### ISSUE TITLE
Select All and Delete gives blank Alert popup

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3459]
System - Data pane
Set filter to `Id in <list of 500 ids`
clicked Select All  tick box, then Delete
got Confirm delete selected popup -> OK
got Confirm ~You have selected ALlL items popup-> OK
go ALERT popup, no  text and action not performed

If I de-select one item and press delete 

Confirm  delete selected popup -> OK
Delete Summary -> OK
Items deleted.

Assume Select All flow is broken due to 2 Confirm popups?

**Comment by stroomdev66** [comment]
Unable to replicate, closing for now
