### ISSUE TITLE
Unable to read function description in 7.2

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#3480]
A useful looking popup appears when I select a function for my column expression but I can't read its contents (see screenshot).  If it had a vertical scroll bar, this might work, but popup should be taller initially, as it only currently displays the title.
![Screenshot ](https://github.com/gchq/stroom/assets/25030212/d2336dbf-9045-48ef-a1d5-24453904d6c2)

**Comment by stroomdev10** [comment]
On my screen **every** help text has a horizontal scrollbar.

Some of the menus that popup when selecting functions have horizontal scrollbars too
