### ISSUE TITLE
Detection issue

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3494]
I have a rule

```
from blah
where some stuff
eval EventTime=floorDay(EventTime)
eval patternCnt=sum(if(match(Field1,'Pattern'),1,0))
eval notPatternCnt=sum(if(match(Field1,'Pattern'),0,1))
eval weirdFirst=first(Field4)
group by EventTime,Field1,Field2
having patternCnt = 0 and notPatternCnt > 0
select EventTime, Field1, Field3, patternCnt, notPatternCnt, weirdFirst
```

When the rule fires and generates multiple detections **every** detection has the same value for `Weird`

On checking the source data , the values for Weird do NOT appear in the results for the first N reported groups, however it does appear for the last group detected.

If I run the query, the values for weirdFirst, they appear correct in the table, only the detections look incorrect.

UPDATE::  Using the Shards pane, I can see that  all of the values of weirdFirst for all groups are the same!!!!

FURTHER UPDATE: I changed the Rule to `joining(Field4)` and the data looks correct, i.e. different for each Key and correct

**Comment by stroomdev66** [comment]
This is probably something to do with using `first()`. Investigate once realtime analytic search is present.
