### ISSUE TITLE
Beta 43 Search is still having problems with Search

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#354]
Stack shows ehcache issues.....

**Comment by stroomdev66** [comment]
org.apache.lucene.index.IndexWriter.close 893
stroom.index.server.IndexShardWriterImpl.destroy 334
stroom.cache.AbstractCacheBean.destroy 168
stroom.cache.AbstractCacheBean.destroy 161
stroom.cache.AbstractCacheBean.access$100 36
stroom.cache.AbstractCacheBean$CacheListener.notifyElementExpired 240
net.sf.ehcache.event.RegisteredEventListeners.notifyListener 298
net.sf.ehcache.event.RegisteredEventListeners.invokeListener 284
net.sf.ehcache.event.RegisteredEventListeners.internalNotifyElementExpiry 216
net.sf.ehcache.event.RegisteredEventListeners.notifyElementExpiry 194
net.sf.ehcache.Cache.notifyRemoveInternalListeners 2351
net.sf.ehcache.Cache.removeInternal 2337
net.sf.ehcache.Cache.tryRemoveImmediately 2117
net.sf.ehcache.Cache.elementStatsHelper 2078
net.sf.ehcache.Cache.searchInStoreWithoutStats 2072
net.sf.ehcache.Cache.getQuiet 1858
net.sf.ehcache.Cache.getQuiet 1841
stroom.cache.AbstractCacheBean.getQuiet 76
stroom.index.server.IndexShardWriterCacheImpl.getQuiet 70
stroom.search.server.shard.IndexShardSearcherCache.getWriter 136
