### ISSUE TITLE
Adding a new dashboard widget causes existing widgets to get compressed

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#3559]
When adding a new widget, existing widgets will be "squashed" vertically, requiring the user to manually resize them.

Ideally if the constraint "Fit Height" is enabled, the newly added widget should have a smaller height value - instead of taking up most of the viewable area and squashing the other widgets.

# Before adding
![image](https://github.com/gchq/stroom/assets/17559369/b68c87c2-a7ce-4af6-81e0-939240dc3ec9)

# After adding
![image](https://github.com/gchq/stroom/assets/17559369/1593068e-4014-4f67-be93-e47406e02210)

**Comment by stroomdev66** [comment]
Fixed by making the user choose where to place new dashboard components.
