### ISSUE TITLE
Query Picker Help - click highlight issue

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3566]
In the Query Picker Help

Expand the following items:

```
Functions ->Mathematics->Rounding->ceiling
Functions ->Mathematics->Rounding->floor
Functions ->Mathematics->Rounding->round

```
Now click on `... (value)`  under `round` , the Picker will highlight `... (value)` under `ceiling`

The displayed content is correct, only the highlighting is incorrect.

**Comment by at055612** [comment]
Fixed in > 7.2-beta.41
