### ISSUE TITLE
Permissions Not Added to New Objects

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#3577]
Adding a feed/xslt/etc. to a folder does not add the destination permissions to the object despite that being the default option.

**Comment by stroomdev00** [comment]
Version 7.2.beta-33-open-id-1

1. As admin user, create a new subfolder (not tested as a folder in root)
2. Look at user perms of that folder - no users added (would expect creating user to be owner)
3. Change folder perms - add a user with perms
4. Create new XSLT within folder
5. Look at user perms of the XSLT - would expect to match new folder perms but no users listed.

Steps 1-2 above weren't originally mentioned but may be relevant.

**Comment by stroomdev10** [comment]
Confirmed, when the folder is added under System, there is no Owner permission assigned.

**Comment by at055612** [comment]
fixed in `v7.2-beta.43-open-id-3`
