### ISSUE TITLE
Log rolling - dropping events

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3580]
If we have a time based roll for a log and archivedFileCount set to a value other than 0 then there is a possibility that logs will be lost during idle periods

**Comment by at055612** [comment]
From the logback docs (which is what is doing the log rolling).  `archivedFileCount` in DropWizard is mapped to `maxHistory` in logback.

>The maxHistory property controls the maximum number of archive files to keep, deleting older files. For example, if you specify monthly rollover, and set maxHistory to 6, then 6 months worth of archives files will be kept with files older than 6 months deleted. Note as old archived log files are removed, any folders which were created for the purpose of log file archiving will be removed as appropriate.

>For various technical reasons, rollovers are not clock-driven but depend on the arrival of logging events. For example, on 8th of March 2002, assuming the fileNamePattern is set to yyyy-MM-dd (daily rollover), the arrival of the first event after midnight will trigger a rollover. If there are no logging events during, say 23 minutes and 47 seconds after midnight, then rollover will actually occur at 00:23'47 AM on March 9th and not at 0:00 AM. Thus, depending on the arrival rate of events, rollovers might be triggered with some latency. However, regardless of the delay, the rollover algorithm is known to be correct, in the sense that all logging events generated during a certain period will be output in the correct file delimiting that period.

The default config has `archivedFileCount` set to 100 with minute rolling logs.  It looks like what is happening is that if stroom is idle for longer than 100 mins, then the last minutes worth of logs from the end of the previous day will roll when someone logs into stroom in the morning, but will immediately get deleted as they are are for a time window that is older than 100 minutes.

Thus, either set the `archivedFileCount` to `0` to keep all rolled logs and have something else manage deletion, or set it to a value higher than the longest idle period.
