### ISSUE TITLE
Reorganise main menu

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#3584]
Tools / User Permissions -> Security / Application Permissions
Tools / Data Volumes -> Configuration / Data Volumes
Tools / Index Volumes -> Configuration / Index Volumes
Tools / API Keys -> Security / Manage API Keys
Tools / Users -> Security / Manage Accounts
Tools / Data Retention -> Configuration / Data Retention
Tools / Properties -> Configuration / Properties
Tools / Dependencies
Tools / Import
Tools / Export
Monitoring / Database Tables
Monitoring / Jobs
Monitoring / Nodes
Monitoring / Caches
Monitoring / Server Tasks
Monitoring / Search Results
User / Preferences
User / Logout
User / Change Password

**Comment by at055612** [comment]
May _Administration_ instead of _Configuration_
