### ISSUE TITLE
Change classic column expression fields to not require `${}`

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#3594]
The need to wrap fields with `${}` makes editing and selection more fiddly.  Would be good to remove the need for the braces and dollar, which would also then make it consistent with StroomQL.

relates to #3568

**Comment by at055612** [comment]
If we change this then the field completion snippets will need to change to not surround field names with `${` `}`

**Comment by stroomdev66** [comment]
The use of `${}` is now optional unless a field contains spaces in which case it is required.
