### ISSUE TITLE
Dark mode text contrast too low

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#3645]
Even in a dimly-lit environment, active text elements lack contrast, making them hard to read.

**Comment by at055612** [comment]
Any chance of some screen shots of specific examples?

**Comment by p-kimberley** [comment]
# Current
![image](https://github.com/gchq/stroom/assets/17559369/77d208ed-700b-42ec-a6c9-ef744bf5fdea)

# Recommended
Set `--text-color` to `#e6e1dc` (same as `--navigation-text-color`).

![image](https://github.com/gchq/stroom/assets/17559369/f0216634-00b1-4d48-89ca-8ddc1054322a)
