### ISSUE TITLE
Allow Documentation tab on Folders

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3698]
for consistency, can we have a Documentation tab on Folders

**Comment by at055612** [comment]
This is a non-trivial change.  Folders are not the same as other entities under the hood.  They do not exist in the `doc` table.  They just exist within the explorer tree.

Now that the user can create a documentation entity (#3699) within a folder I am not sure this issue should be pursued.

**Comment by at055612** [comment]
Too complicated to implement so given it is possible to achieve this by creating a Documentation entity in the folder, this is a wont fix.
