### ISSUE TITLE
Search fails when you have a variable in the top bar

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#371]
can't paste an error at the moment :(

**Comment by stroomdev10** [comment]
Certainly for stats queries, not tried index queries yet

**Comment by GCHQ-11** [comment]
Might this have been fixed with commit 6ee5810335746c7809080108880e1f3e4911cf33 ?

**Comment by GCHQ-11** [comment]
Nope, but it will be fixed now by https://github.com/gchq/stroom/pull/453

**Comment by GCHQ-11** [comment]
Having found the emptyMap mistake in two places, I believe this is now fixed.
