### ISSUE TITLE
Search is returning StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#373]

**Comment by at055612** [comment]
Exception happens when the search returns no data.

**Comment by at055612** [comment]
Having fixed the StringIndex exception with  https://github.com/gchq/stroom/commit/d02692e04e98dfe961844a584050f8d4f593eebd
the dashboard now does not update the table when there are no results, it leaves whatever was in the table from the last query.  Raised #374.

**Comment by at055612** [comment]
Fix will be available when PR #375 is merged down to master
