### ISSUE TITLE
Welcome tab build details are incorrect

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#376]
Currently the build details text in the bottom right corner of the welcome tab show
```
Build version: ${pom.version}
Build date: ${build.timestamp}
```
This needs to be fixed to extract the build date and version from somewhere, and for gradle to record that information somewhere

**Comment by GCHQ-11** [comment]
pull request to fix
https://github.com/gchq/stroom/pull/450

**Comment by GCHQ-11** [comment]
This has been solved in dev, considering finished
