### ISSUE TITLE
Dashboard UI failing on login screen with `inputStream` error shown in red

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#379]
This is caused by RemoteServiceHandlerAdapter setting the wrong path for the GWT serialisation policy file and the file path causing an `inputStream` error.

The system is expecting to find GWT RPC policy files in `/ui/stroom/%s.gwt.rpc` when it ought to look in `/ui/dashboard/%s.gwt.rpc` when using the dashboard client on it’s own as it is completely separate code. We need a way to choose the policy file path based on the request URL.

**Comment by GCHQ-11** [comment]
I believe I have fixed this with branch #409
