### ISSUE TITLE
I'd like to be able to add/remove Tags from multiple Objects

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3814]
currently you can only enter the Tags screen for single Objects

**Comment by at055612** [comment]
Potentially we would need a different tags screen for tagging multiple nodes as we cannot display a list of current tags on the node as there are multiple nodes in play.

So if we have the text input field, the list of known tags and then Add, Remove and Cancel btns.  Add would add the selected/input tag(s) to all selected nodes if not already present.  Remove would remove the selected/input tag(s) from all selected nodes if present, silently ignoring nodes that do not have the tags to be removed.

**Comment by at055612** [comment]
Fixed in > 7.2-beta.79
