### ISSUE TITLE
Change proxy aggregation test criteria for the stroom.maxStreamSize setting

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#382]
During proxy aggregation, it appears the test to see if the addition of an additional stream raw events is greater than the setting `stroom.maxStreamSize` is performed after the addition of the next stream. The test should occur **before** the addition.

For example, if I have two streams 960MB and 1.2GB and have set `stroom.maxStreamSize`  to be 1GB, I end up with a stream greater than 2GB!

**Comment by stroomdev66** [comment]
Should be fixed in v6.0-beta.31 onwards
