### ISSUE TITLE
Unable to Display Bad Data as Hex

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#3857]
When Raw Events streams are in the wrong encoding or e.g. zipped when not tagged as such, the yellow  box comes up to say `Unable to display source [nnnn:1:1] as text ... You can right click this pane and select 'View as hex' ... `.  However right clicking does nothing.  Right clicking on valid data does allow this to happen if that helps you spot the problem.

**Comment by at055612** [comment]
Fixed in > v7.2-beta.79
