### ISSUE TITLE
Shard maked as Deleted in the UI are not being deleted

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3898]
In one environment I have an Index that has about a dozen logically Deleted shards in the UI

Index Shard Delete job is not removing these shards.

No useful debug is available for this job

I re-deleted the shards in the UI and they got deleted in the next Index Shard Delete run.

Assume something was causing it to ignore these shards

**Comment by at055612** [comment]
Fixed in >v7.3-beta.3
