### ISSUE TITLE
Ownership Validation Issues

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#3947]
Objects and Folders have only recently required mandatory ownership.  Attempting to change permissions on a cascade of folders and objects will fail if at least one item has no owner.  Adding an owner at the top level will then fail if at least one item has an owner that differs from the new top-level owner.  This system doesn't give any detail as to which object has either no owners or multiple owners.  So even when we don't care about ownership, permissions are unable to be modified on a hierarchy of folders.

Ideally, if an object has no owner, it should default to being owned by admin.  Or something.

**Comment by at055612** [comment]
Some of the confirm dialog messages that the user will now get for cascade all/changes:

![image](https://github.com/gchq/stroom/assets/22818309/5fff0b0d-40e5-40ce-ae5b-c451f2b020af)

![image](https://github.com/gchq/stroom/assets/22818309/de1b4a40-b177-4ac5-b148-7d196290e503)

![image](https://github.com/gchq/stroom/assets/22818309/9f28bee0-cd3d-4c9b-afe7-80cf3e284c92)

![image](https://github.com/gchq/stroom/assets/22818309/0c1c90ba-a085-4969-9f23-14cd08fbede1)

**Comment by stroomdev00** [comment]
Just tested on 7.2.14
An existing folder with no perms containing a number of objects all owned by me.
Try adding another user (or even myself) to the folder with any perms (even no perms) and any cascade option results in the error `java.lang.NullPointerException: Cannot invoke "stroom.securuity.shared.DocumentPermissions.getPermissions()" because "documentPermissions" is null.`

**Comment by at055612** [comment]
@stroomdev00 raising as #4012

**Comment by at055612** [comment]
Was fixed in 7.2.14
