### ISSUE TITLE
Add Maxmind GeoIP2 enrichment

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#3973]
With logs containing Internet IP addresses, it would be useful to be able to leverage the [Maxmind GeoIP2 Java library](https://maxmind.github.io/GeoIP2-java/doc/v4.2.0/com.maxmind.geoip2/com/maxmind/geoip2/DatabaseReader.Builder.html) to look up details such as country code and city.

Ideally the GeoIP2 binary database would be loaded into a reference feed at a point in time. A XSLT lookup function would allow the user to look up details of an IP address. In the backend, Stroom would dynamically load the appropriate database from the specified reference feed, and perform the lookup.

**Comment by at055612** [comment]
If you can write something that will dump out the whole maxmind db into a ref stream (with IP as the key and an xml tree containing stuff like country, city, etc. as the value) then you can just do the lookups using a standard `lookup` call and standard xslt to get the bit of the value you want, e.g. the country.

**Comment by at055612** [comment]
@p-kimberley can this be closed now that the ref approach is working ok?

**Comment by p-kimberley** [comment]
Closing in favour of a vanilla CSV based ref data solution utilising #3976
