### ISSUE TITLE
Expression term operator selection resets

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#3979]
Observed with `master`:

![image](https://github.com/gchq/stroom/assets/17559369/38770e44-b62f-4344-a32c-eaf11bd19032)

When clicking on the term to edit it, the operator resets to `=`. It should instead retain its value, in this case `>`.

![image](https://github.com/gchq/stroom/assets/17559369/0d47dab1-3182-4502-98fe-c9d4447c7c0c)

**Comment by p-kimberley** [comment]
Another problem with the updated expression editor when filtering streams:

1. Create a term, such as `Create Time` as in the previous example.
2. Add a second term, with no value
3. Click on the first term again
4. The terms disappear whole or part of the expression becomes cut off
5. Expression terms now disappear when clicked, making the expression editor unusable

![image](https://github.com/gchq/stroom/assets/17559369/1f909322-ac0a-44f4-90a8-5e1b748c2252)
![image](https://github.com/gchq/stroom/assets/17559369/31e6ca0e-c6ce-4955-929e-9afaa3539d87)

**Comment by stroomdev66** [comment]
I've fixed the condition selection but haven't been able to replicate the second issue.
