### ISSUE TITLE
Pipeline filters vanish from UI after upgrade to `master`

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#3981]
Affects: `master` branch

# Steps to reproduce
1. Create a new pipeline, (e.g. by duplicating an existing one)
2. Create a processor filter and enable it
3. Wait a few seconds and refresh the `Processors` view
4. Processor filter no longer appears

What appears to be happening is in the DB, `processor.uuid` and `processor.pipeline_uuid` equal the same value. The expected value for `processor.pipeline_uuid` is a valid `doc.uuid` record. This is no longer the case.

It appears this is a regression introduced in the jump from `7.2` to `master`.

**Comment by at055612** [comment]
Fixed in 7.3-beta.5
