### ISSUE TITLE
Query an Index, only `Stored` fields can be `Select`ed

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4007]

**Comment by at055612** [comment]
This seems to have been fixed on master already, @66 to confirm

**Comment by at055612** [comment]
Not fixed in master, will fix in 7.2 and merge up

**Comment by at055612** [comment]
![image](https://github.com/gchq/stroom/assets/22818309/8598dc3c-594d-45a0-bed5-44a7274a90b9)

**Comment by at055612** [comment]
Fixed in >7.2.20
