### ISSUE TITLE
Stuck Search Tasks v7.2.20 (LMDB?)

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4024]
Tasks can't be killed in Server Tasks.

Stuck Process Name is:
`Thread Name	Stroom P2 #9675`

[20240119_Stuck_Search.txt](https://github.com/gchq/stroom/files/13986420/20240119_Stuck_Search.txt)

**Comment by at055612** [comment]
This appears to be concurrency issues with CompleteableQueue.
