### ISSUE TITLE
Stroom 7.3-beta.7 data browser initially appears empty

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#4059]
Double click on "System" or a feed will show the data browser view.  As of v7.3-beta.7 this window initially appears empty and the refresh button must be clicked to populate.  This issue has been introduced since v7.3-beta.5

Update - it seems that the view from a feed does not show newly created streams, even when the refresh button is clicked.  To see new streams it is necessary to close the data browser (feed) view and reopen.

**Comment by at055612** [comment]
Fixed in >7.3-beta.7
