### ISSUE TITLE
Add XSLT function to decode a hex string using a specified charset

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#4082]
Proposed function `stroom:hex-to-string()` would accept two arguments:

1. Hex string, such as `74 65 73 74 69 6e 67 20 31 32 33`, containing a hex representation of encoded text.
2. The text encoding to use, such as `UTF-8`.

The purpose of this function is to allow certain log data to be decoded, where the text encoding can be one of a number of schemes.

**Comment by at055612** [comment]
Fixed in > v7.3-beta.7
