### ISSUE TITLE
Duration with Format = Number in Table column

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4091]
I have an expression `parseISODuration(now()-${EventTime})`

If I format the column as a `Number`, I get values that are of the form `xn` or `n` where `n` is a small integer.

e.g. `1h` `2` `3` `6h`

If I display the value as General I get the expected `nh` or `nd`

If i format the column as a Number, then ,my expectation is that the numeric value is displayed. i.e. the raw duration

Happy to have a discussion if you have a better suggestion

![image](https://github.com/gchq/stroom/assets/28703366/c4b33bbf-f627-4996-b24c-2ebdfe868ba2)

**Comment by at055612** [comment]
`stroom.query.common.v2.format.NumberFormatter#format` is just a bit wrong.

Needs to tailor its behaviour based on the input type, e.g.
ValLong/ValInteger/ValDuration - get asLong(), add 000s separators if needs be
ValDouble/ValFloat - convert to BigDecimal and use that to format appropriately
ValNull/ValErr - return null
ValString - if numeric and with decimal part treat as ValDouble, else if numeric treat as ValLong, else, return null

**Comment by at055612** [comment]
Fixed in >7.3-beta.7
