### ISSUE TITLE
Dashboard errors when a table has no columns

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#412]
ERROR  [13:54:12.665] [dw-134 - POST /api/sqlstatistics/v2/search] i.d.j.e.LoggingExceptionMapper -  Error handling a request: 289460a1a122baff 
stroom             | java.lang.NullPointerException: null
stroom             | 	at stroom.query.common.v2.CompiledFields.<init>(CompiledFields.java:37)
stroom             | 	at stroom.query.common.v2.TableCoprocessor.<init>(TableCoprocessor.java:43)
stroom             | 	at stroom.statistics.server.sql.search.StatisticsQueryServiceImpl.createCoprocessor(StatisticsQueryServiceImpl.java:62)
stroom             | 	at stroom.statistics.server.sql.search.StatisticsQueryServiceImpl.buildResponse(StatisticsQueryServiceImpl.java:149)
stroom             | 	at stroom.statistics.server.sql.search.StatisticsQueryServiceImpl.search(StatisticsQueryServiceImpl.java:108)
stroom             | 	at stroom.resources.query.v2.SqlStatisticsQueryResource.search(SqlStatisticsQueryResource.java:84)
stroom             | 	at sun.reflect.GeneratedMethodAccessor506.invoke(Unknown Source)
stroom             | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
stroom             | 	at java.lang.reflect.Method.invoke(Method.java:498)
stroom             | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
stroom             | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
stroom             | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
stroom             | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
stroom             | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
stroom             | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
stroom             | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
stroom             | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
stroom             | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
stroom             | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
stroom             | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
stroom             | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
stroom             | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
stroom             | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
stroom             | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
stroom             | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
stroom             | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
stroom             | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
stroom             | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
stroom             | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
stroom             | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
stroom             | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
stroom             | 	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
stroom             | 	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
stroom             | 	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
stroom             | 	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
stroom             | 	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
stroom             | 	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
stroom             | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
stroom             | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
stroom             | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
stroom             | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
stroom             | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
stroom             | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
stroom             | 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
stroom             | 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
stroom             | 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
stroom             | 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
stroom             | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
stroom             | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
stroom             | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
stroom             | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
stroom             | 	at stroom.servlet.RejectPostFilter.doFilter(RejectPostFilter.java:55)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
stroom             | 	at stroom.util.thread.ThreadScopeContextFilter.doFilter(ThreadScopeContextFilter.java:41)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
stroom             | 	at stroom.util.upgrade.UpgradeDispatcherFilter.doFilter(UpgradeDispatcherFilter.java:36)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
stroom             | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
stroom             | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
stroom             | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
stroom             | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
stroom             | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
stroom             | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
stroom             | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
stroom             | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
stroom             | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
stroom             | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
stroom             | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
stroom             | 	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241)
stroom             | 	at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:38)
stroom             | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:494)
stroom             | 	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
stroom             | 	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
stroom             | 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
stroom             | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
stroom             | 	at org.eclipse.jetty.server.Server.handle(Server.java:564)
stroom             | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
stroom             | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
stroom             | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
stroom             | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
stroom             | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
stroom             | 	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
stroom             | 	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
stroom             | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
stroom             | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
stroom             | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
stroom             | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
stroom             | 	at java.lang.Thread.run(Thread.java:748)
stroom             | 127.0.0.1 - - [25/Sep/2017:13:54:12 +0000] "POST /api/sqlstatistics/v2/search HTTP/1.1" 500 110 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 64
stroom             | 172.21.0.1 - - [25/Sep/2017:13:54:12 +0000] "POST /dispatch.rpc HTTP/1.1" 200 621 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 164
stroom             | 172.21.0.1 - - [25/Sep/2017:13:54:13 +0000] "POST /dispatch.rpc HTTP/1.1" 200 525 "http://localhost:8080/dashboard.jsp?type=Dashboard&uuid=346fa8d0-50fb-4283-845a-3f47f1938809" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 5
stroom             | 172.21.0.1 - - [25/Sep/2017:13:54:13 +0000] "POST /dispatch.rpc HTTP/1.1" 200 104 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 10
stroom             | 172.21.0.1 - - [25/Sep/2017:13:54:14 +0000] "POST /dispatch.rpc HTTP/1.1" 200 104 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 8
stroom             | 172.21.0.1 - - [25/Sep/2017:13:54:15 +0000] "POST /dispatch.rpc HTTP/1.1" 200 104 "http://localhost:8080/dashboard.jsp?type=Dashboard&uuid=346fa8d0-50fb-4283-845a-3f47f1938809" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 8
stroom             | 172.21.0.1 - - [25/Sep/2017:13:54:15 +0000] "POST /dispatch.rpc HTTP/1.1" 200 104 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 5
stroom             | 172.21.0.1 - - [25/Sep/2017:13:54:16 +0000] "POST /dispatch.rpc HTTP/1.1" 200 104 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 60
stroom             | 127.0.0.1 - - [25/Sep/2017:13:54:17 +0000] "POST /api/sqlstatistics/v2/destroy HTTP/1.1" 200 4 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 4
stroom             | 127.0.0.1 - - [25/Sep/2017:13:54:17 +0000] "POST /api/sqlstatistics/v2/destroy HTTP/1.1" 200 4 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 18
stroom             | INFO   [13:54:17.790] [dw-94 - POST /ap

**Comment by GCHQ-11** [comment]
This doesn't seem to happen with index based dashboards, I will try and recreate with stats based one.
The line that null pointers is taking the size of a list.

**Comment by at055612** [comment]
See also the same issue in stroom-stats https://github.com/gchq/stroom-stats/issues/37

**Comment by GCHQ-11** [comment]
I believe this will be fixed by this upgrade to stroom-query
https://github.com/gchq/stroom-query/pull/4

**Comment by GCHQ-11** [comment]
Fixes merged in
