### ISSUE TITLE
Expand /Collapse All can't see currently highlighted Item

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4141]
If I select/highlight something down the bottom of the Explorer, then click Expand All, the selected Item is no longer visible in the window, I have to scroll down to see it.

Also can I have `Expand / Collapse This Folder` as a context menu item on the Explorer please

**Comment by stroomdev66** [comment]
"Also can I have Expand / Collapse This Folder as a context menu item on the Explorer please"
Raised as separate issue gh-4145
