### ISSUE TITLE
7.3 Stack JOOQ WARN on startup

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4156]
Version mismatch: Database version is older than what dialect MYSQL supports: 8.0.28. Consider https://www.jooq.org/download/support-matrix to see what jOOQ version and edition supports which RDBMS versions.

<img width="1050" alt="image" src="https://github.com/gchq/stroom/assets/28703366/8b9c3910-faef-4356-a156-7a2d1a386663">

**Comment by at055612** [comment]
stroom-resources has been uplifted to use MySql 8.0.36.
The 7.3 CI build has been changed to use the 7.3 stroom-all-dbs image with MySQL 8.0.36
