### ISSUE TITLE
Annotations, Show Linked Events , List of Ids is too small for Medium/Large Fonts

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4168]
![image](https://github.com/gchq/stroom/assets/28703366/bf05c77f-1f2c-4cb1-9b6d-ce725fe6fb8b)

**Comment by at055612** [comment]
Changed column to auto fill whole width.  Increased size of popup.  Increased initial size of left hand split pane.

![image](https://github.com/gchq/stroom/assets/22818309/88de6432-7c1f-467c-8b11-60830124773c)

**Comment by at055612** [comment]
also added a copy text link in case it is useful

**Comment by at055612** [comment]
Fixed in >7.3-beta.14
