### ISSUE TITLE
Proc Filters owned by Low Priv Users failing to update PipelineStreamProcerssor SQL Stat store

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4199]
```stroom.statistics.impl.MultiServiceStatisticsReceiver```

```Error sending internal statistics to SQLInternalStatisticsService, due to [Not permitted to read PipelineStreamProcessor] caused by: [unknown] (enable DEBUG for full stacktrace)```

**Comment by at055612** [comment]
Fixed in >7.3-beta.14
