### ISSUE TITLE
Extraction pipeline resetting to default if not tagged as Extraction

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#4202]
stroom 7.2.22
If an existing Dashboard uses an extraction pipeline that is not tagged as Extraction then any modifications to the dashboard will revert the pipeline to the default when the dashboard is saved.

Steps to replicate:
1. Create dashboard with a Table extraction pipeline.
2. Check it works.
3. Select the extraction pipeline and remove the extraction tag from it.
4. Close and reopen the dashboard - the extraction pipeline will be as expected.
5. Make any change to the dashboard (not even extraction related) and save it.
6. Close and reopen the dashboard - the extraction pipeline will now have been reset to the original/default.

I can't tell if this would work if no pipelines are tagged as Extraction.

Ideally it would continue to use the existing pipeline but if not possible, a warning should be raised upon attempting to save the dashboard.

**Comment by at055612** [comment]
Fixed in 7.5-beta.16
