### ISSUE TITLE
Proxy aggregation is slow and should be using multiple threads for aggregating streams

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#423]

**Comment by at055612** [comment]
Need to adopt some of the multi threading work done in v5 that has not been merged in.

Also proxy agg has a setting for the max aggregation size but at the moment it only stops aggregating into a file when it has gone over that size so if the last file being aggregated in is huge then the limit can be blown substantially.

**Comment by burnalting** [comment]
#382 refers also

**Comment by stroomdev66** [comment]
Duplicate #1116 

v6.0-beta.30 now includes a change to allow more threads to perform proxy aggregation
