### ISSUE TITLE
During migration pipelines are failing to have all XSLT and index references correctly updated

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#425]

**Comment by at055612** [comment]
The problem appears to be caused when the entity in question has regex special chars in the name, e.g. 'myXSLT-v2+' or 'All text (very large)'.  

The offending line is `newData = newData.replaceAll(ref, sb.toString());` in EntityReferenceReplacer.

The special chars will be interpreted by the regex engine so it won't find a match.  

Need to escape any special chars, or use a non-regex string replace.

**Comment by at055612** [comment]
Released a patched beta48 (https://github.com/gchq/stroom/releases/tag/v5.0-beta.48-patch1) to re-test the migration

**Comment by at055612** [comment]
tested https://github.com/gchq/stroom/releases/tag/v5.0-beta.48-patch1 against a pre v5 database and it migrated all pipelines correctly.

**Comment by at055612** [comment]
Merged fix into 5.0 branch
