### ISSUE TITLE
Meta Store , Time fields aren't Date types

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4256]
Create Time, Status Time etc

e.g.
```
from "Meta Store"

eval Type=typeOf(${Create Time})
eval Dt=parseDate(formatDate(${Create Time}))

limit 10

select ${Create Time}, Type, Dt
```

**Comment by at055612** [comment]
The following changes will be made to the data source field types:

**Annotations**
Change `CreadtedOn` to Date
Change `UpdatedOn` to Date

**Index Shards**
Change `Last Commit` to Date

**Meta**
Change `Status Time` to Date
Change `Create Time` to Date
Change `Effective Time` to Date

**Reference Date**
Change `Date` to Date

**Task Manager**
Change `Submit Time` to Date
Change `Age` to Duration

**Any Statistic data source**
Change `Date Time` to Date

**Comment by stroomdev10** [comment]
closed
