### ISSUE TITLE
Auto content import on boot needs to be done as a configured user

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#4262]
Currently auto import is done as `admin` which is no good if you do not want that user present in stroom.

Suggestion is to have a config prop like `autoImportAs` and for it to take the identity of a user or group.  The import would run as this user/group so all imported content would be owned by them/it.

**Comment by gcdev373** [comment]
Is it safe to assume that there is never a group and a user with the same name?

**Comment by at055612** [comment]
They can be the same.  will need another prop to specify grp or usr

**Comment by at055612** [comment]
Fixed in >7.4-beta.13
