### ISSUE TITLE
Server Tasks is querying non-enabled nodes and showing an Error Triangle

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4305]
It ought to not bother trying non-enabled nodes

**Comment by at055612** [comment]
Changing it so it will still hit disabled nodes (in case they are still up and doing work), but will ignore errors from disabled nodes.

Also the errors in the triangle were not being cleared prior to refresh so have fixed that.

**Comment by at055612** [comment]
Fixed in >7.4.4
