### ISSUE TITLE
HttpAppender with Compression is ignoring the User defined Feed header argument

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4317]
I have a pipeline with an HttpAppender that send to a Stroom instance.

The HttpAppender has a `httpHeadersUserDefinedHeader1=Feed: MY-FEED`

This pipe works OK if I have `useCompression=false`

If I set `useCompression=true` then the transfer fails with `No Feed Specified` from the remote Stroom

**Comment by at055612** [comment]
Fixed in > 7.4.4
