### ISSUE TITLE
[GUI] View Jobs by node rather view by Job Title with each job displaying each nodes setting. 

### ISSUE THREAD

**Issue by stroomdev42** [gchq/stroom#4327]
Can be 
- added to Nodes Page ( g n )
or
- have page selection  "By Job/By Node" on existing Jobs Page ( g j )

**Comment by at055612** [comment]
We could do this by having the following sub-tabs on the Jobs screen (`Jobs`|`Nodes`) with the former showing we have at the moment, and the latter showing a list of nodes and the detail pane showing a list of jobs with enabled at the top and disabled at the bottom (or only show the enabled ones with :heavy_plus_sign: / :heavy_minus_sign: icons to add/remove.

**Comment by at055612** [comment]
@stroomdev10 would prefer a Jobs detail pane on the Nodes screen.

**Comment by at055612** [comment]
Fixed in >7.5-beta.5
