### ISSUE TITLE
NPE When Viewing a Folder

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#4385]
Occasionally when updating a folder permission, usually for older folders, an NPE is raised as the system can't see a given uuid.  This seems to be resolvable by giving the folder an owner from the `perms` right-click option.

However, subsequently searching for the uuid gives the folder name in the browser tree and `right-click/info` results in an NPE for `https://stroom.host/api/explorer/v2/info` with a bunch of `Unknown.xx(stroom-0.js)` entries.  It seems possible to duplicate the folder name and move everything from old to new, but this isn't a great solution.

Nothing seen in stroom-errors.
Clearing one of the doc caches (Document Owner Permissions Cache or Document Permission Cache) after giving the folder an owner does seem to resolve the issue but it takes several minutes to kick into life.

**Comment by at055612** [comment]
Fixed in >7.4.9
