### ISSUE TITLE
Scheduled Query Analytics not reflecting changes to the Analytic doc

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4449]
I made changes to the query that underpins a Rule, but the changes weren't reflected in subsequent executions of the Rule.

**Comment by at055612** [comment]
`stroom.analytics.impl.ScheduledQueryAnalyticExecutor#exec` runs every 10min (or whatever it is configured as).  When it runs it finds all the rules with type Scheduled Query.  It then processes each rule in turn until all are done.  If say you have 2 rules A & B and A is taking ages, meanwhile you change B before A has finished, then when B finally runs it will run the pre-change version of B.

It needs to re-fetch the rule on processing and re-check that the rule is the right type and enabled.
