### ISSUE TITLE
v7.5 User pref for some users is broken

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4472]
User prefs aren't being picked up, entering User Pref dialog gives Alert box with : 

Error calling GET https://xxxxxxxxxxxxx/api/preferences/v1 - dateTimePattern: yyyy-MM-dd'T'HH:mm:ss.SSSXX, density: Compact, editorKeyBindings: STANDARD, editorLiveAutoCompletion: OFF, editorTheme: tomorrow_night, enableTransparency: true, font: Tahoma, fontSize: Small, theme: Darker, timeZone: {"use":"UTC"}

Nothing obvious in the logs

**Comment by at055612** [comment]
Fixed in >7.5-beta.15
