### ISSUE TITLE
ClusterSearchTask never ends

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#448]

**Comment by stroomdev66** [comment]
IndexShardSearchTaskHandler.java:45
IndexShardSearchSearchTaskHandler.java71
IndexShardSearchSearchTaskHandler.java 83
IndexShardSearcherCacheImpl.java 110
AbstractCacheBean.java 68
BlockingCache.java 308
SelfPopulatingCache 73
AbstractCacheBean 50
IndexShardSeacheerCacheImpl 129
IndexShardSearcherImpl 107
read past EOF boom (edited)
