### ISSUE TITLE
Delete Functionality Appears Available for Users without Delete Permissions

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#4503]
A user with Update but not Delete access to a feed has the ability to select streams for deletion and to select the delete icon.  The user is in a group with `Data - Delete` application permissions.  They will then be advised that `nn items will be deleted`.  At this point, nothing happens.

I'd expect the Delete icon to be unavailable or at least greyed out in this situation.

**Comment by at055612** [comment]
Fixed in 7.5-beta.18
