### ISSUE TITLE
Auth proxy endpoint causes a HTTP redirect

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#4514]
Auth proxy endpoint `/api/authproxy/v1/noauth/fetchClientCredsToken` is causing a 307 redirect when invoked during node bootstrap. The expected behaviour is for the endpoint to return an authentication token to the caller.

This API endpoint is critical for running Stroom in K8s.

**Comment by at055612** [comment]
Fixed in >7.5-beta.19
