### ISSUE TITLE
Exporting a ZIP file results in decompression errors on Windows systems

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#4562]
Since the 7.5 upgrade, exporting a ZIP file from Stroom, such as a configuration export or stream data export, causes an error when trying to extract the ZIP file using certain Windows-based archive routines (including PowerShell, .NET Framework and 7-zip).

For example, the following PowerShell command: `Expand-Archive config.zip -DestinationPath .\output` results in the following error:
```
Exception calling "ExtractToDirectory" with "2" argument(s): "A local file header is corrupt."
At line:1 char:1
+ [System.IO.Compression.ZipFile]::ExtractToDirectory("config.zip", "ou ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidDataException
```

This was introduced in [this commit](https://github.com/gchq/stroom/blob/35d573c06c02ce49f9fd2723410bd63818dd3b59/stroom-util/src/main/java/stroom/util/zip/ZipUtil.java#L55).

To resolve, replace:
```java
zipArchiveOutputStream.setUseZip64(Zip64Mode.Always);
```
with:
```java
zipArchiveOutputStream.setUseZip64(Zip64Mode.AlwaysWithCompatibility);
```

**Comment by at055612** [comment]
Fixed in 7.5.1
