### ISSUE TITLE
Stroom QL with show will only display values from the first page of results

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4612]
sQl viz only shows results from the first page in the table

```
from "Meta Store"
where Type = 'Raw Events'
eval Period = floorHour(${Create Time})
eval Value = any(random())
group by Period
sort by Period
select Period, Value
show LineChart(x=Period, y = Value, maxValues=10000)
```

Run this Query, this is the output

![image](https://github.com/user-attachments/assets/668fe181-a71b-4772-bf31-daf6a36801aa)

Go to the table, alter the page size to 1000, change tab back to Viz, and run the query again, this s the result.

![image](https://github.com/user-attachments/assets/b6681f3e-f9ba-4dac-b99c-a7a2c24b0578)

**Comment by at055612** [comment]
Fixed in > v7.5.2
