### ISSUE TITLE
Lots of Index shards are being marked as corrupt

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#463]

**Comment by stroomdev66** [comment]
Adding logging to the two areas of code that could set a shard to CORRUPT.
The log lines will contain: `Setting index shard status to corrupt because`

Also the status value for CORRUPT has been changed to 100

**Comment by stroomdev10** [comment]
10 got a corrupt message!


[2:27 PM] 
java.io.FileNotFoundException
from IndexShardWriterCacheImpl 156
 IndexShardWriterImpl 741 (edited)
lucene shiz
java RandomAccessFile open (edited)
boom

**Comment by stroomdev10** [comment]
codec header mismatch actual header=12345 vs expected header=56789 (resource: NIOFSIndexInput (path=/xxx/xxx/xxx.tip))
