### ISSUE TITLE
Description column on Monitoring->Jobs tab truncates long description

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#472]
![image](https://user-images.githubusercontent.com/22818309/32379700-286e39da-c0a6-11e7-80e5-67a325ceb3b3.png)

Options:
* it needs to be expanded to fill the available space
* It needs to wrap text onto multiple lines
* the column is resizeable
* the description text in question is made shorter

**Comment by stroomdev10** [comment]
Column is resizeable now
