### ISSUE TITLE
SQL deadlock when running Stream Retention

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#483]
SQL deadlock occurring when performing Stream retention job, (possibly colliding with StreamDelete job?)

The locks in the DB are
TASK 1 STRM.PRIMARY locked by 
DELETE FROM STRM INNER JOIN TEMP(STRM.ID = TEMP_STRM_ID.ID)
TASK 1 STRM.STRM_FK_FD_ID_CRT_MS_IDX locked by 
?

TASK 2 STRM.PRIMARY locked by
UPDATE STRM S USE INDEX (STRM_FK_FD_ID_CRT_MS_IDX) SET S.VER=S.VER+1, S.STAT=99, STAT_MS=123456789 WHERE STAT <>  99 AND S.CRT_MS < 123456789 AND S.STAT IN (0) AND S.FK_FD_ID in (999) LIMIT 10001

Both queries originate from the same Node,

Both Stream Retention and Stream Delete run at the same time, will change time of one, and monitor.

**Comment by at055612** [comment]
While it does resolve the issue it would make sense for the default schedules for these two jobs to set at different times, given there is a high likely hood of contention as they are both hitting the STRM table.

From the deadlock report:
Task 1 (stream delete) has a lock on strm.strm_fk_fd_id_crt_ms_idx and is waiting for one on strm.id
Task 2 (stream retention) is waiting on a lock on strm.id
Lock mode is X in all three cases.
Task2 is marked as the victim.

I believe an `insert into select ` statement will create a lock on the index records covered by the select criteria.  So the stream delete first inserts into a temp table based on a select on strm based on age. which will lock the index mentioned above. 

Need to verify that the queries are definitely not touching the same rows in strm, as the update should only be touching rows with a STAT of 0 and the delete should only be touching rows with a STAT of 99.

**Comment by at055612** [comment]
Options to try:

In stroom.streamstore.server.fs.FileSystemStreamStoreImpl#findDelete change the update to an update ... limit n and loop it to reduce the number of rows that it is locking at once.

In stroom.streamtask.server.BatchIdTransactionHelper change the transaction propogation to REQUIRES_NEW to ensure that each method gets a new transaction.  The code is already written in a way to expect each statement (the insert...select and four deletes) to each be done in their own transaction, but it maybe spring is still lumping them together in one.

stroom.streamstore.server.StreamDeleteExecutor#exec has @Transactional and Propogation.NEVER.  It is not obvious why these are needed here.  Possibly removing them would help.

If we are only ever doing one statement in a transaction then it should not be possible to deadlock.

Also need to confirm the behaviour of select..insert wrt locking or not.
