### ISSUE TITLE
Provide construct to allow dictionaries to be aggregated (or included) into "parent dictionaries"  [Enhancement]

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#507]
In searches or other XSLT constructs, dictionaries are used to provide a list of criteria or generic data.

To better manage grouping of dictionary content, it is proposed to allow a dictionary to `include` other dictionaries. That is, if one had dictionaries

`ThematicDataA`
`ThematicDataB` 
and `ThematicDataC`

one could create a dictionary that concatenates all three using a construct such as

```
_#_include "ThematicDataA"
_#_include "ThematicDataB"
_#_include "ThematicDataC"
```

which results in a dictionary containing the content of the subordinate dictionaries.

**Comment by stroomdev66** [comment]
Added to v6.0-alpha.5

**Comment by burnalting** [comment]
Can an example be provided below ... what should the import reference look like?

**Comment by stroomdev66** [comment]
This is a v6+ feature and allows a user to add dictionary imports to a dictionary object via the settings page for a dictionary. The references are added via the UI which allows dictionaries to be chosen via a typical explorer selection popup.
