### ISSUE TITLE
Too many active destinations: 101 Error on Rolling File appender

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#516]
With a RollingFile Appender configured as per

![image](https://user-images.githubusercontent.com/10084635/33757504-9507dace-dc4e-11e7-98b7-8f4ad1f6bd77.png)

I get the error 
`[textWriter] FATAL: Too many active destinations: 101`
multiple times. This is on all streams processed by the pipeline.

No errors occur if using a simple `fileAppender`.

I am using the example `Event Data` pipeline found in 
`./stroom/stroom-core-server/src/test/resources/samples/config/Standard Pipelines/Event Data.Pipeline.data.xml`
with the `fileAppender` manually replaced with a `rollingFileAppender`

**Comment by stroomdev10** [comment]
Remove the uuid from the fileName portion, and replace with ${node} and it will be fine.

You are making a new destination for every stream otherwise.

**Comment by burnalting** [comment]
For completeness, the configuration change that works appears below. Perhaps it can be considered to either

- provided a warning if a user attempts a ${uuid} variable expansion in the fileName property of a rollingFileAppender, or
- ensure the documentation warns of it's use

![image](https://user-images.githubusercontent.com/10084635/33800134-c23bcf3c-dd8e-11e7-85f1-f4c278147174.png)

**Comment by burnalting** [comment]
For more completeness should one need to emit one stream at a time (ie one stream to one file) then the combination limiting the number of process filters on the pipeline (see #3966) and the use of a FileAppender (not rolling) achieves this.
