### ISSUE TITLE
Filtering on logical conditions in a dashboard table does not work.

### ISSUE THREAD

**Issue by stroomnz** [gchq/stroom#52]
If I use the function under expression to trigger a true or false value, I'm unable to filter in include/exclude using the true or false value.

**Comment by stroomdev66** [comment]
The filtering only applies to the raw field values that act as input to the expression. If filtering was applied only to the evaluated result of an expression then filters could not be used to reduce/filter the input to an expression. The currently proposed solution to provide post expression evaluation filtering is with conditional formatting/hiding of table rows as described in issue #26.

**Comment by stroomnz** [comment]
I thought the filtering was post expression as you can filtering on Max, min, table etc that must be post.
