### ISSUE TITLE
Missing Visualisation icons in 5.1

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#536]
Visualisations are missing the Legend and Resize icons in 5.1 releases.

A small square appears instead.

**Comment by stroomdev10** [comment]
Still happening in Beta 5

**Comment by at055612** [comment]
This was still happening despite the fix due to the instance of Chrome holding onto a cached copy of index.html without the import of the font awesome css in it. Clearing the cache and doing a `shift-ctrl-r` resolved it.

**Comment by at055612** [comment]
No fix required
