### ISSUE TITLE
Explorer tree not showing content on startup

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#546]
./bounceIt.sh -f env/stroom6-core.yml

On startup stroom installs a number of content packs but when you login to stroom, no content is displayed.  On collapsing and expanding the root of the tree, the content appears.

**Comment by GCHQ-11** [comment]
We have improved the multi threading access to the explorer tree, factored that out into a separate class and tested it as thoroughly as we can. This has solved the problem in so far as we were able to recreate it
