### ISSUE TITLE
Provide a function that parses and returns the components of a URI

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#554]
For many, an audit event containing a URL (or URI), is very common.

There would be benefit to provide a Stroom function, that given a URI, will return it's components as per

- scheme
- authority
- path
- query
- fragment

if present.

This function should also be provided as a [Stroom-Expression](https://github.com/gchq/stroom-expression) function should users of Stroom not want to store URI components separately.

**Comment by stroomdev66** [comment]
Added XSLT function `parseUri` to v6.0-alpha.5. Expression to be moved to a separate issue #557
