### ISSUE TITLE
Highlighted text in table is automatically unhighlighted after a very short time

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#559]
When a user highlights text within cell values in the table, the system deselects (unhighlights?) this after about 1 second.  This makes copying data out of the table difficult, using copy and paste.

**Comment by stroomdev66** [comment]
During search a table will constantly update as new results arrive. Each update clears any existing text selection that you may have. You need to pause the query if you want the table to stop updating while you select some text.
