### ISSUE TITLE
Stopping a query doesn't allow a user to expand grouped table detail

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#562]
You can expand a group if you pause a query, but not if you stop a query.

Possibly it also does this if the query finishes.

**Comment by stroomdev66** [comment]
This is not an easy issue to fix. Stop needs to be changed so it actively requests termination of the underlying search process and doesn't rely on taking the search out of the list of active searches as this also ends up clearing the associated data.

**Comment by stroomdev66** [comment]
In addition to this it would be an improvement for pause to be a per component feature and not an alternate state for the play button. As an alternate state there is a chance that clicking pause will result in a new search starting and often does.
