### ISSUE TITLE
Replace kafka pipeline filters with a single one that relies on a schema and responds to sax events

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#563]
Currently the StroomStatsFilter is just sending the whole document as a single msg which isn't ideal for kafka. We would rather have lots of smaller events than huge batch of many.

Make the AbstractKafkaProducerFilter extend from AbstractXMLFitler. Make StroomStatsFilter a child of SamplingXMLFilter that wraps a SplitFilter and an new child of an AbstractKafkaProducerFilter, ensureing all events are delegated to the SplitFilter and its childFilter is the new inner filter. The childFilter of the inner filter should be set to the childFilter of the StroomStatsFilter to complete the chain.

May be worth exposing setSplitCount as something like setBatchSize rather than hard coding at a count of 1 and later finding a moderate batch size is preferable.

**Comment by at055612** [comment]
It is debatable if this is worth changing as we already have the StroomStatsAppender which has a recordCount property to control this (with a default of 1).  There is possible merit in removing the two kafka filters as the appenders so the same thing in a more logical way.

The only reason to keep the the StroomStats filter is if we want to make use of the sax events to extract each field of the stat event to build something like a flatbuffer or kryo serializable object.  However as the original event will have to undergo some form of xslt the result of that may just as well be fired off to kafka rather than transforming it again.

**Comment by at055612** [comment]
We had a team discussion and agreed to remove the two kafka filters as they add nothing over the kafka appenders.

**Comment by at055612** [comment]
Having thought about this and remembering a requirement for a more generic approach to sending kafka messages that allows values in an event to drive the key/topic, I think we should remove the two kafka based pipeline filters but replace them with a more intelligent filter.

We could define an xml schema that allows xml like
```
<KafkaRecord>
    <KafkaRecord topic="MyTopic" partition="1">
        <Key>jbloggs</Key>
        <Value>
            ...
        </Value>
    </KafkaRecord>
</KafkaRecord>
```
Thus the sax event handler can build a kafka producer record on each </KafkaRecord>. The partition attr would be optional as this is a fairly niche use case.  Both Key and Value could be xs:anyType to allow for xml/json/yml/simple text/etc.

This would allow an XSLT to craft very bespoke producer records with total flexibility.

Another option would be to do this with a writer/appender, however the existing writer classes are geared around character outputstreams which doesn't fit well with needing to create producer records.

**Comment by at055612** [comment]
Suggestion from @stroomdev66 is to re-use the stroom record format rather than creating a new XML structure, e.g. 
```
<record>
   <data name="topic" value="mytopic" />
   <data name="key" value="mykey" />
   <data name="value" value="myvalue" />
</record>
```
However this would put kafka's K and V in attributes which is not ideal for structured data, e.g. xml/json.

**Comment by at055612** [comment]
My preference is for a bespoke XML structure as putting a message payload in an attribute is pretty grim.

We need to be able to support a message payload of xml, json or any other text based format that we can craft via xslt.

Also since this was written we now have a `KakaAppender` and `RollingKafkaAppender` so these would need to be changed to work more generically.  We still have a `KafkaFilter` but this ought to be dropped as a filter is not the right name for a terminal element of this nature.

**Comment by at055612** [comment]
Having discovered headers in kafka the XML probably ought to be something like 
```xml
<KafkaRecordBatch>
    <KafkaRecord topic="MyTopic" partition="1"> <!-- 1:*, topic mandatory, partition optional -->
        <Key>jbloggs</Key> <!-- 0:1, xs:string or maybe xs:any-->
        <Header key="someKey1" value="someValue1" /> <!-- 0:*, key/value mandatory-->
        <Header key="someKey2" value="someValue2" />
        <Value> <!-- 1:1 xs:any-->
            ...
        </Value>
    </KafkaRecord>
</KafkaRecordBatch>
```

**Comment by at055612** [comment]
Proposed schema

![image](https://user-images.githubusercontent.com/22818309/65975336-62639000-e466-11e9-8676-69848b63464d.png)

**Comment by gcdev373** [comment]
An implementation of the Kafka Pipeline element is available on the `analytic-demo` branch. [https://github.com/gchq/stroom/tree/analytic-demo/stroom-kafka/stroom-kafka-demo/src/main/java/stroom/kafkademo](github directory listing).  `StandardKafkaProducer` is the class to consider merging into this branch.

**Comment by gcdev373** [comment]
Delivered by StandardKafkaProducer and kafka schema, released with Stroom v7
