### ISSUE TITLE
Stepping: Allow warning text to be displayed without scrolling to top

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#564]
This is something that causes stress when developing XSLT in Stroom.  Warning text (eg from stroom:lookup) is displayed at the top of the top window (yellow area on scroll bar) but user must scroll up to see detail. 
 Would be better if just hovering mouse over the yellow area would display error without having to scroll up, to prevent losing place where editing is taking place.

**Comment by at055612** [comment]
Closing as this will be covered by #1941
