### ISSUE TITLE
Getting user not authorized exception when opening a dashboard

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#565]
With a clean stroom running in docker (6core + zk + kafka) if you open the Stroom Status dashboard it will try and query 5/6 stats at once.  It looks like each one is triggering the auto-creation of a token (as 'admin' doesn't have one at this point) and multiple User Unauthorized exceptions are shown (one for each stat query on the dash).  It appears that the auth service creates multiple tokens, so possible should be synchronizing the creation process to avoid the multiple tokens.

On requerying the dashboard the authorization problem appears to go away, presumably due to the api tokens being present.

**Comment by jc064522** [comment]
60c5a922147c029df2048b920412f875938f90ff
91e15e6a13bed166e588d30ec3da3a5cb74bf0da

**Comment by GCHQ-11** [comment]
Can this be closed now jc064522?
