### ISSUE TITLE
Additional functions in the table

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#581]
substring-before
substring-after
index-of
last-index-of
conditional (if x then y else z) . regex version
std-dev
string to date
cast

**Comment by stroomdev66** [comment]
stroom-expression gh-15 : Added `if` and `not()` functions.

stroom-expression gh-13 : Added value functions `true()`, `false()`, `null()` and `err()`.

stroom-expression gh-14 : Added `match` boolean function.

stroom-expression gh-12 : Added `variance` and `stDev` functions.

stroom-expression gh-8 : Added `hash` function.

stroom-expression gh-10 : Added `formatDate` function.

stroom-expression gh-9 : Added `parseDate` function.

stroom-expression gh-6 : Made `substring` and `decode` functions capable of accepting functional parameters.

stroom-expression gh-5 Added `substringBefore`, `substringAfter`, `indexOf` and `lastIndexOf` functions.
