### ISSUE TITLE
Rolling streams to roll on a schedule 

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#596]
I'd like to be able to specify that a rolling stream rolls on a schedule (maybe via a cron value)

Currently they only roll on frequency.

I'd like it to still roll if it hits the size limit before the schedule

**Comment by burnalting** [comment]
This is the standard cron schedule mechanism used throughout Stroom as per ...
`minute hour day`, e.g. `* * *` to roll every minute
