### ISSUE TITLE
Index Shard view page is showing blank pages when an index has > 100 shards.

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#600]
Not present in v5.1 beta 12, but introduced in v5.1 beta 13

**Comment by stroomdev66** [comment]
Unable to replicate. Please turn on debug logging for queries `stroom.entity.server.util.StroomEntityManagerImpl`

**Comment by stroomdev66** [comment]
Also turn on debug logging for `stroom.index.server.IndexShardServiceImpl`

**Comment by stroomdev10** [comment]
Turns out it was a data issue, some shards had a bad status value.
