### ISSUE TITLE
Permissions not being correctly set following entity copy

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#615]
Copying an entity to a folder with only "User" permissions set, results in a new entity in the correct folder with no permissions set.

**Comment by stroomdev66** [comment]
Unable to reproduce the permission setting issue when copying. Please provide more detailed steps to reproduce, i.e. the entity type being copied and the permissions of each item before and after copy.

**Comment by gcdev373** [comment]
This isn't consistently reproduceable.  Closing for now.

**Comment by stroomdev66** [comment]
Dealt with in gh-523
