### ISSUE TITLE
Allow different retention time for RAW/Events

### ISSUE THREAD

**Issue by stroomnz** [gchq/stroom#640]
Related but not directly linked to "Feature request: Separate Raw Events and Events".
Legally, I need to keep "raw logs" for a minimum of 7 years. However, I don't always need the Event data for that period of time. It would be nice to be able to have different retention time for the Raw-xxx and the Events in a feed.

**Comment by stroomdev10** [comment]
Stroom v5.1.0 enables this via the Data Retention feature, check it out.

https://github.com/gchq/stroom/releases/tag/v5.1.0
