### ISSUE TITLE
Unable to select extraction pipeline in dashboard

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#651]
Seen in f570bc9

Steps:
* Run setupSampleData
* Create a dashboard against ExampleIndex
* Attempt to configure the table to use an extraction pipeline

Pipeline picker dialog is always empty preventing the user from picking a pipeline to extract with.

**Comment by GCHQ-11** [comment]
The picker dialog is being configured to find Pipelines with a tag of 'Search Extraction' but the explorer nodes for pipelines are not being given a tag that corresponds with their 'Type', so the filter is returning zero results

**Comment by GCHQ-11** [comment]
We will remove the pipeline tag filtering, as it's a bit of a kludge anyway. If we want to filter pipelines by type, or do other such things, we will have a proper design session.
