### ISSUE TITLE
Unable to run V6.0 Alpha 10

### ISSUE THREAD

**Issue by stroomnz** [gchq/stroom#652]
Trying to have  first look t V6 A10
Runs but when accessing http://server:8080 or http://server:8080/stroom, it redirects the browser to http://server/auth....
There is nothing that listen to port 80 or 443. Tried nginx redirect to 8080 but that did not help.
Probably need a few more lines in Readme file for how to get things working.
Help?
Cheers
/Kiwi

**Comment by at055612** [comment]
Sorry, the readme hasn't quite kept pace with the changes that have happened between 5 and 6.  Will sort out the readme and report back.

**Comment by at055612** [comment]
See the updated root readme in stroom-docs - https://github.com/gchq/stroom-docs/blob/master/README.md

There are a few other pages relating to running stroom that are also out of date and I will address these next.

Let me know if you  have issues with the instructions on the link above.

**Comment by at055612** [comment]
I have re-jigged some of the markdown relating to running stroom in docker.  The instructions are now here 
https://gchq.github.io/stroom-docs/dev-guide/docker-running.html 
or 
https://github.com/gchq/stroom-docs/blob/master/dev-guide/docker-running.md

**Comment by jc064522** [comment]
Hi - it's probably easier if we continue this on Slack. I'll send you a DM.

**Comment by stroomnz** [comment]
I'm away till next week. Will see if I can get Slack.

**Comment by jc064522** [comment]
Hi @stroomnz -- did we resolve this?

**Comment by jc064522** [comment]
I'll close it -- happy to re-open if we need to.
