### ISSUE TITLE
All ports need to be configurable

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#670]
Currently stroom's two ports (8080 and 8081) are backed into the dropwizard dev/prod.yml that is baked into the docker image.  These (and similarly for our other services that expose ports) need to be replace with env vars (with defaults) so they can be configured by bouceit and env files.  Also all ports specified in the compose yml files need to be replaced with defaulted env vars.

This will also us to deploy onto a host where certain ports are already in use.

**Comment by jc064522** [comment]
Done for stroom and auth. Remaining: elastic, annotations, stats.

**Comment by jc064522** [comment]
Elastic, annotations, stats not part of 6.0 release. Not doing now.
