### ISSUE TITLE
UI allows user to select any pipeline for search extraction

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#745]
But unless its a Search Extraction pipeline, then the query will fail with the following error:
Unable to find single 'stroom.search.server.extraction.SearchResultsOutputFilter' in search result pipeline
Earlier versions of Stroom presented a filtered view of pipelines to the user, so that only appropriate ones could be selected, making this feel like a bug.  It is likely to cause user confusion, as it is a change to (now expected) behaviour.

**Comment by stroomdev10** [comment]
Tags
