### ISSUE TITLE
Allow dictionaries to be referenced indirectly rather than by name

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#747]
When a dictionary is used by an XSLT, and is renamed, the XSLT breaks.  This is not consistent with other Stroom behaviour, where renaming is a safe operation.

Possibly the UI might allow a key to be associated with a dictionary, and it is that key that is referenced from the xslt function to access the dictionary contents, rather than using dictionary name directly

**Comment by stroomdev66** [comment]
The lookup ought to try and use a UUID first and then fall back to a lookup by name
