### ISSUE TITLE
Visualisations under 5.3.0 do not render in latest Chrome but do on latest Firefox

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#755]
Visualisations work on Firefox - both 52.7.2 (64-bit) Firefox ESR on Linux and 59.0.3 Firefox Quantum on Windows 10
Visualisations do **not** work on Chrome - both Version 66.0.3359.117 (Official Build) (64-bit) on Linux and Version 66.0.3359.139 (Official Build) (64-bit) on Windows 10
Visualisations do work on Chromium Version 65.0.3325.181 (Developer Build) Fedora Project (64-bit) on Linux

Search results are gained (looking at the logs and dashboard tables), but visualisations only render in Firefox.

**Comment by stroomdev66** [comment]
I think we established that this is because you need the latest visualisation content pack that contains a JS fix in `Generic Grid`.
