### ISSUE TITLE
Allow Stroom to easily ingest the stroom.log

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#757]
Ideally make this a configurable option, maybe if one supplied a feed name to the setup then the log is sent to that feed regularly.

There is lots of useful stuff in the event log that will help our monitoring

**Comment by burnalting** [comment]
Should this configuration item be extended to
- the proxy logs
- the event logs
?

**Comment by at055612** [comment]
This issue has been discussed previously as we will soon have many more services producing log4j/slf4j type log output (i.e. n stroom nodes, n stroom-auth-service nodes, n stroom-stats nodes, etc) and there is no current means for collating all these logs and querying them.  Some form of kafka based log appender has been discussed so each service could send its log messages to a kafka topic (with a file based fallback for kafka un-availability).  Stroom would then consume from this topic, normalise, index and store in the stream store.
