### ISSUE TITLE
Provide FileAppender pipeline element option to compress output [Enhancement]

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#759]
In some circumstances, users can export significant amounts of data via file Appenders. To minimise  storage cost and external script integration, it would be useful to optionally compress (zip or gzip) the resultant output files.

This would be particularly useful for rollingFileAppenders (say a compressRolledFileName option with zip/gzip argument), although there would be no reason (aside from complexity to implement) compressing files generated from a simple fileAppender.

**Comment by robin54747** [comment]
We'd like to see this too.
