### ISSUE TITLE
Display and set the computed EventId when Stepping through a pipeline

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#760]
Occasionally, one needs to refer to the original raw data a Stroom XML event hailed from. A method of doing this is to search for the given event and display the StreamId and EventId within a the Stream.

With the StreamId, one can look up the `Events` stream and hence it's original `Raw' stream.
At this point one could go to the `Raw` stream and start stepping to obtain the original raw data.

It would have value to jump directly to the identified EventId within this 'stepping stream'

**Comment by stroomdev66** [comment]
Fixed as part of #1247
