### ISSUE TITLE
table expression if(${x} = null(),true(),false()) always returns false if x is null()

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#769]

**Comment by stroomdev66** [comment]
Add `isNull()` and `isNotNull()` functions and disallow `= null()`

**Comment by at055612** [comment]
see also gchq/stroom-expression#18, gchq/stroom-expression#19

**Comment by stroomdev66** [comment]
This was fixed in stroom-expression v1.4.0. Stroom currently uses v1.4.3.
