### ISSUE TITLE
Dashboard search appears to end, but refresh of table continue's to provide more results

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#791]
When a search returns over 100,000 events and the red stop button greys out which, one expects, signals the end of the search, pressing the `Refresh` button on a `Table` display gains more events with a subsequent log message along the lines of
`2018-06-21T12:51:51.897Z INFO  [ajp-apr-8009-exec-10 - SearchBusPollAction] server.SearchResultCreator (SearchResultCreator.java:125) - Delivering 100 rows for table-IIO1T`

For example, the search below appears complete

![image](https://user-images.githubusercontent.com/10084635/41720424-596f843e-75a6-11e8-89af-bca3da532a79.png)

but pressing the `Refresh` button on the table display results in more events returned as per

![image](https://user-images.githubusercontent.com/10084635/41720469-7bb092f4-75a6-11e8-8f1a-56b57d39fc32.png)

with a corresponding SearchBusPollAction as per
`2018-06-21T12:56:49.534Z INFO  [ajp-apr-8009-exec-8 - SearchBusPollAction] server.SearchResultCreator (SearchResultCreator.java:125) - Delivering 100 rows for table-IIO1T`

If one continues to press the `Refresh` button, more events display. It will sometimes 'pause' from displaying more events, but wait for 60 or so seconds and more events are displayed on the counter as a result of the `Refresh` action.

At present one sees

![image](https://user-images.githubusercontent.com/10084635/41720756-602dc6cc-75a7-11e8-9bee-aa201f6e15e6.png)

but a `Download` from the table results in 567407 data rows being exported curiously.

Search settings are

![image](https://user-images.githubusercontent.com/10084635/41720979-fc9979c0-75a7-11e8-99e7-a7f03c0c85eb.png)

and the table `Maximum Results` setting is the default of 1000000.

**Comment by burnalting** [comment]
For reference, pressing `Refresh` after 18 minutes from submitting this bug report we gain more data as per

![image](https://user-images.githubusercontent.com/10084635/41722137-f8d2aa20-75aa-11e8-915e-47cef9729967.png)

**Comment by burnalting** [comment]
For reference, leaving the search overnight allowed the search to hit the 1,000,000 result set size limit.

**Comment by burnalting** [comment]
If one unticks `Extract Values` in the Table display configuration, then the search is much faster and quickly reaches the 1,000,000 max limit, but the search still keeps on running (but not adding to the result set count naturally).

In this state, `Server Tasks` shows
![image](https://user-images.githubusercontent.com/10084635/41801795-f54aa16c-76bf-11e8-9419-6dc79686cd8c.png)

and threads dumps whilst in this state are attached.
[issue_791_dump1.zip](https://github.com/gchq/stroom/files/2129340/issue_791_dump1.zip)

**Comment by burnalting** [comment]
Running the search with the original test (`Extract Values` is ticked), the `Stop Query` greys out and refreshing the table gains more results, and in this state, `Server Tasks` shows

![image](https://user-images.githubusercontent.com/10084635/41808394-1fb98db8-7720-11e8-9ad8-22cfce0cc132.png)

and again thread dumps whilst in this state are attached.
[issue_791_dump2.zip](https://github.com/gchq/stroom/files/2129823/issue_791_dump2.zip)

Please advise if more is required.

**Comment by stroomdev66** [comment]
As part of the investigation into this issue it was found that search result merges are taking a long time due to excessive sorting. This is still the case and needs fixing, however the UI will now show search completion correctly hence this issue is fixed.
