### ISSUE TITLE
Preferred order of properties for Pipeline Elements

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#792]
combinedParser: type,tesxtConverter,fixInvalidChars
elasticIndexingFilter: index,idFieldName
genericKafkaProducerFilter:topic,recordKey,flushOnSend
schemaFilter: schemaGroup,systemId,namespaceURI,schemaLanguage,schemaValidation
statisticsFilter:statisticsDataource,flushoOnSend
xsltFilter: xslt,xsltNamePattern,suppressXSLTNotFoundWarning,usePool
hdfsFileAppender:outputPaths,fileSystemUri,runAsUser
httpdAppender:forwardURL,useCompression,connectionTimeout,forwardChunkSize,logMetaKeys
kafkaAppender:topic,recordKey,maxRecordCount,flushOnSend
rollingFileAppender:outputPaths,fileName,rolledFileName,frequency,maxSize
rollingkafkaAppender:topic,recordKey,frequency,maxSize,flushOnSend
rollingStreamAppender:streamType,feed,frequency,maxSize,segmentOutput
streamAppender:streamType,feed,segmentOutput
stroomStatsAppender:statisticsDataSource,maxRecordCount,flushonSend

All others can be left as is

**Comment by jc064522** [comment]
I guess all ways of defining order aren't great: 
- on the class's annotation means it could easily get out of date, especially if names change and we're using strings to describe the order
- on the property itself means it's not a definite list but rather some lame 'priority' list, where there could easily be priority conflicts and getting a definite list means eyeballing all the annotations on the properties
- `getMethods` doesn't guarantee order

**Comment by jc064522** [comment]
Done
