### ISSUE TITLE
XXE in XML Parser

### ISSUE THREAD

**Issue by ProDigySML** [gchq/stroom#813]
# The Issue
An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

# Where the Issue Occurred
The following code snippet displays the usage of `XMLReader` without disabling entities:
https://github.com/gchq/stroom/blob/336fa676d502cc38305fb0a97f8a5e407e8315a1/stroom-core-server/src/main/java/stroom/entity/util/XMLUtil.java#L114-L117

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.8
