### ISSUE TITLE
Negation of a single dashboard term always returns no results

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#816]
In attempting to achieve a `not equals` expression within a Stroom dashboard, it has been noted that a negation of a simple test always returns no results.

For example, the term
![image](https://user-images.githubusercontent.com/10084635/43703149-42cbb58c-999f-11e8-88e9-638d0ce78cf9.png)
returns many thousands of results, but to change this to 
![image](https://user-images.githubusercontent.com/10084635/43703196-646cf462-999f-11e8-8124-5c7c22ac2f2d.png)
and this search returns no results. Add additional terms such as those below return many hundreds of thousands (as expected).
![image](https://user-images.githubusercontent.com/10084635/43703280-aae49d5a-999f-11e8-95ca-dc83ef41919b.png)

This also is an issue for `Text` type fields. Given an index which records feedname, simply search with a single term such as `AND {Feed = <yourknownfeedname>}` and see many results. Change the `AND` to a `NOT` in order to search for all events not from <yourknownfeedname> and zero results are returned.

**Comment by stroomdev66** [comment]
This is just the way Lucene works. Basically you have to search for something you want and then use NOT to remove specific results. I don't think we can change this behaviour without internally altering the query to be:
```
AND
   Field = *
   NOT Field = negation
```

**Comment by burnalting** [comment]
Thanks for the clarification. Closing.
