### ISSUE TITLE
Deleting a folder doesn't seem to delete it's descendants

### ISSUE THREAD

**Issue by GCHQ-11** [gchq/stroom#869]
if you delete a folder while you have an editor open for one of the doc refs in that folder….it lets you delete the folder (fine I guess) but it also lets you keep editing and saving changes to the document (which indicates that it still exists)

This is in contrast to deleting a document in the explorer when you have an existing editor window on that document, any attempts to save changes after the deletion give you ‘unable to update record, it has been updated by another transaction’ which whilst that process is not as helpful as it could be, seems more correct

These are tests EXPL014 and EXPL015 in the test scripts worksheet

**Comment by GCHQ-11** [comment]
Further to this, after saving the 'deleted' document, I did a content import of the content which had been deleted. It showed the 'Text Converter' as being an update, but all the other content as being new. This suggests that the deletion IS deleting things recursively, but that the open editor is allowing the text converter to be recreated in an orphaned state.

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.12
