### ISSUE TITLE
Password Complexity and Reuse

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#874]
The first time you use the auth service you are asked to change password. There are no password complexity rules enforced. You can reuse the same password.

**Comment by jc064522** [comment]
I've added checks but they're provisional until I can confirm the requirements:
- Cannot re-use previous password. Does not check against all previous passwords. If this is policy then it will require a database change.
- Configurable complexity, using a regex.
- Configurable minimum password length. A regex can do this, obviously. Except length is a salient requirement and if there aren't any other complexity requirements it avoids a regex. Possibly we'll always need complexity requirements, and if we do I'll consider scraping the length option.

I'll leave this open until the requirements are confirmed. NB: NCSC guidance says "enforcing the requirement for complex character sets in passwords is not recommended".
