### ISSUE TITLE
v5 SplitAggregated Streams doesn't work if you add a findReplaceFilter

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#882]
I have a simple pipeline that does raw streaming, the output stream has splitAggregatedStreams=true.

The pipeline structure is source->streamAppender, when the input is an aggregated stream, then the output is split out as expected.

If I add a findReplaceFilter between Source and StreamAppender, then the splitAggregatedStreams functionality doesn't appear to work.  

With the findReplaceFIlter in place I just get the original aggregated stream as output.

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.9

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.9
