### ISSUE TITLE
Multiple `writeRecordCount` pipeline filters record the same count

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#891]
In a pipeline that splits and stores events into two different feeds as per

![image](https://user-images.githubusercontent.com/10084635/47292614-4864df00-d653-11e8-887c-b7116d828888.png)

The two `writeRecordCountFilters` record the same count despite a different number of events `passing through` them as per below where we see

the top pipeline path processed 580 events  of the 1760 total

![image](https://user-images.githubusercontent.com/10084635/47292785-d17c1600-d653-11e8-9e3a-9982f8dbffa5.png)

and the bottom pipeline path records the other 1180 events
![image](https://user-images.githubusercontent.com/10084635/47292872-16a04800-d654-11e8-88c8-810049573a5e.png)

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.9
