### ISSUE TITLE
Adding a volume can show an error

### ISSUE THREAD

**Issue by jc064522** [gchq/stroom#892]
There can be a few seconds between clicking 'OK' on the add volume dialogue and the dialogue closing. This has a few issues.

Issues:
1. It's not clear what is happening or if the button click has worked because it remains enabled. There is a spinner in the top right but it's hard to notice because the dialogue is modal and lightboxes the rest of the application.
2. If you click 'OK' before the dialog disappears there is an error message. I'd guess it's trying to perform the same action again but can't because of a conflict in the path.

There are other issues on this page:
1. The 'OK' button is spelt 'Ok'. 'OK' should not be spelt 'Ok' (it's not the name of someone whose name is pronounced 'ock') or 'ok' (it's not pronounced 'ock') or 'okay' (ew).
2. If, after adding a volume, you try to add another, you will find that the 'node' dropdown on the dialogue is empty, or at least missing the node that was there previously. It comes back if you close the Volumes dialogue and re-open it.

None of these are particularly high impact. Suggest we don't fix but instead wait for the new UI.

**Comment by jc064522** [comment]
The Volume dialogue is also very wide, at nearly 1000px.

**Comment by jc064522** [comment]
The dialogue closing issue is a wider problem. You can create multiple indexs of the same name by creating a new one and clicking the OK button repeatedly.

**Comment by stroomdev66** [comment]
I changed `Ok` to `OK` :)

**Comment by stroomdev66** [comment]
Closing as we aren't going to change the close/progress behaviour on dialogs until the new UI comes along
