### ISSUE TITLE
Feed name not updated in explorer tree after rename through import

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#897]
Had a feed called STROOM_PROXY_EVENT_LOG.  Imported a content pack that had a feed with the same UUID but a new name of STROOM_PROXY_SEND_LOG.  Import showed a warning but ticked the update and imported anyway.  

The tree still shows the old name but if you dbl click it, it opens the feed with the tab showing the new name.

![image](https://user-images.githubusercontent.com/22818309/47410254-18a1fe00-d75d-11e8-904b-578ac6ac9f72.png)

**Comment by stroomdev66** [comment]
Import no longer attempts to rename or move existing items but will still update content. I'm not entirely sure that this is the right thing to do but if the user has updated the name of an item in the explorer tree then it is assumed that this name should be preserved.

Ideally the functionality would allow the user to choose which name to keep and would make a default decision based on the update time of the item.
