### ISSUE TITLE
Bug in XSLT function format-date

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#902]
The stream receipt timestamp metadata is somehow able to interfere with calls to format-date that do not use this timestamp at all.

Stepping the attached demonstrates this issue.  An error is produced that says that there is a conflict between the timestamp of the stream receipt and the timestamp provided within the XSLT itself.  But stroom shouldn't be using the timestamp from the metadata at all, yet it is somehow hanging around in scope/memory and causing problems such as this to crop up.

[problem.txt](https://github.com/gchq/stroom/files/2510713/problem.txt)

**Comment by stroomdev66** [comment]
Improved for v6.0-beta.9. Further date formats may have issues but testing all eventualities is virtually impossible,
