### ISSUE TITLE
Possible to resize some dialogs so much that the close button can't be accessed 

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#905]
System properties can now be viewed or edited within resizeable forms.  This is very useful when working on some of the html properties.  However, it is currently possible to stretch the window too far - e.g. beyond the top of the taskbar on Windows.  This is a problem, as it is may then be impossible to access the Close/Apply buttons needed to dismiss the dialog.  Once in this state, it is necessary to restart the UI, which is annoying.

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.9
