### ISSUE TITLE
Changes to an index under 'Settings' tab do not trigger 'dirty indicator' or allow saving

### ISSUE THREAD

**Issue by GCHQ-11** [gchq/stroom#910]
INDEX001
Adding a volume as per the test does not allow saving.
Adding fields under that tab DOES allow saving, which means we can work around it. but we've had this problem before with editors. I'm sure this one worked before so has something been merged in to effectively re-introduce the error?

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.12
