### ISSUE TITLE
findReplaceFilter doesn't work with escaped character ranges

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#912]
Have a filter with the following regex:      [\x00-\x09\x0C\x0E-\x1F]

It isn't matching as expected

regex101 seems to think it is valid https://regex101.com/r/utuWOF/1

[\x08\x09] doesn't work as expected either

**Comment by stroomdev66** [comment]
because it is Java, characters are expected to be referenced as unicode code points, e.g. `\u0000` rather than `\x00`
