### ISSUE TITLE
Import dialog says 'Import complete' when nothing is imported

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#915]
Seen in `stroom_core-v6.0-beta.11-2`
Steps:
1. Import a content pack
2. Don't tick any of the checkboxes
3. Click OK

The dialog says 'Import complete' when nothing has been imported.

I think the OK button should be disabled until at least one thing is ticked, else ok, is a bit meaningless.  This would help prevent users from thinking that they have imported something, when they haven't.

**Comment by stroomdev66** [comment]
Users now get a message if they didn't select anything for import. Fixed as part of gh-916.
