### ISSUE TITLE
Import/Export of empty folders doesn't work

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#916]
Seen in `stroom_core-v6.0-beta.11-2`
Steps to reproduce (Import)
1. Import a content pack that contains only a folder (see attached standard translations zip) 
1. Tick all the boxes.
1. Click OK.
The dialog says import completed but no folder is imported.
[standard-translations.zip](https://github.com/gchq/stroom/files/2561410/standard-translations.zip)

Steps to reproduce (Export)
1. Create an empty folder in the UI
1. Tool->Export, select just the empty folder
1. Export runs and an empty zip is downloaded

Either the import/export of empty folders should be handled correctly or the imp/exp windows should warn/prevent users from doing it.

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.12
