### ISSUE TITLE
Unable to delete 'xxxxxx' Unable to find tree node to delete

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#917]
Seen in `stroom_core-v6.0-beta.11-2`

Steps to recreate:
1. Delete a folder containing content - folder is deleetd
1. Delete another folder

Get error
>Unable to delete 'xxxxxx' Unable to find tree node to delete

where xxxxx is the name of the folder deleted in step 1.  Caching of the tree issue maybe?

**Comment by stroomdev66** [comment]
Unable to recreate, possibly fixed as part of changes for gh-869
