### ISSUE TITLE
Pipeline structure tab not displaying structure for fragment pipelines

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#918]
Seen in `stroom_core-v6.0-beta.11-2`

Steps to recreate:
1. Import the attached content pack
1. Open the `Event Data Base` pipeline, select the Structure tab

Only the `Source` element is displayed.  The _View Source_ function appears to show the correct source.  Pipelines that are based on this one (e.g. `Event Data (XML)`) show their structure ok.

Is it because the base pipeline has no parser?

[StroomConfig (3).zip](https://github.com/gchq/stroom/files/2561804/StroomConfig.3.zip)

**Comment by stroomdev66** [comment]
Remove fragment pipeline from the content pack and replace with 3 top level concrete pipelines

**Comment by at055612** [comment]
There is currently no means in the UI to create a fragment pipeline so the problem only came about due to a pipeline in a content pack.  The content packs has been changed to remove the fragment pipeline, so the bug is essentially fixed.  At some point we may revisit the ability to create fragment pipelines in the UI,
