### ISSUE TITLE
Allow export/import of pipeline processor filters

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#926]
We are building up more content packs that include pipelines.  As it stands once these have been imported you have to go into each pipeline and add a processor filter, typically setting a feed and a type.

It would be great if we could export the proc filters with the pipeline so that we can make content packs that have filters in place and ready to run.
@stroomdev66 and I had a discussion about this, some thoughts:
* A proc filter probably ought to be an entity in its own right, with its own UUID
* The export of a pipeline should also export all the proc filters associated with it.
* The export dialog maybe ought to display the proc filter entities as children of the pipeline, so there is the option to include/exclude some/all as required.
* Debate as to whether the explorer tree should display the proc filters if they become entities, but this would require different screens for managing them in isolation to the pipeline, e.g. its editor would need a selector for the pipeline.  This is probably an optional piece of work.
* There should be a global prop to control whether proc filters are enabled on import or not.  In our docker stack we would want them to be enabled on import so data can start flowing.
* Thought needs to be given to whether to export filters that involve things like stream ID as this is not a portable concept.  Maybe we don't worry and just export everything, or let the user in the export dialog decide (if that is implemented).

**Comment by gcdev373** [comment]
Delivered by resolution to issue gh-1417
