### ISSUE TITLE
Capture certificate DN etc from NGINX as meta data attribute on data receipt if available

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#936]
We need to sort out capturing certificate DN as a data meta attribute in proxy and stroom for NGINX fronted receipt.

Version 5 included the following attributes from the certificate:
`RemoteDN`
`RemoteCertExpiry`

Example attributes from v5:
```
content-type:application/x-www-form-urlencoded
Environment:DEV
Feed:FEED_NAME
GUID:xxx-xxx-xxx
host:xxx.ddd.fff.com
ReceivedTime:2018-11-11T12:12:12.000Z
RemoteAddress:123.234.11.222
RemoteHost:xxx.ddd.xxx.xom (edited)
RemoteCertExpiry:2019-12-12T11:11:11.000Z
RemoteDN:CN=fred, OU=Plop, O=Ploop, C=UK
StreamSize:232344
System:FRED
user-agent:beefy_1.0
```

It sounds as if NGINX can be configured to add the appropriate HTTP headers (`RemoteCertExpiry` and `RemoteDN`) when NGINX is doing SSL termination. We also need to figure out how to add these if DW is used directly (see gh-940).

**Comment by jc064522** [comment]
It's easy to configure NGINX to pass on SSL stuff as headers -- this is done using `proxy_set_header`. Our default `stroom-resources` NGINX config isn't adding the DN for `datafeed` but we do it elsewhere, for example:
```
location /authenticationService/ {
    ...
   proxy_set_header X-SSL-CLIENT-S-DN $ssl_client_s_dn;
   ...
}
```
There are a bunch of other embedded variables you can set in the headers, including expiry stuff. From the [docs](https://nginx.org/en/docs/http/ngx_http_ssl_module.html):

> `$ssl_client_escaped_cert`
>     returns the client certificate in the PEM format (urlencoded) for an established SSL connection (1.13.5); 
>`$ssl_client_v_end`
>    returns the end date of the client certificate (1.11.7); 
>`$ssl_client_v_remain`
>    returns the number of days until the client certificate expires (1.11.7); 
>`$ssl_client_v_start`
>    returns the start date of the client certificate (1.11.7);

**Comment by stroomdev66** [comment]
Capturing these details if using DW without NGINX requires that Jetty be configured to use: `SecureRequestCustomizer`. It appears that DW is configured to use `SecureRequestCustomizer` by default in `io.dropwizard.jetty.HttpsConnectorFactory` line 567.

If this is correct it should be possible to retrieve the necessary attributes with some code like this:
```
        final X509Certificate[] certs = (X509Certificate[]) request.getAttribute("javax.servlet.request.X509Certificate");
            
        if (certs!=null && certs.length > 0 && certs[0]!=null)  {
            final X509Certificate cert = certs[0];
            final String remoteDN = cert.getIssuerDN().toString();
            final String remoteCertExpiry = DateUtil.createNormalDateTimeString(cert.getNotAfter().getTime());

```

**Comment by at055612** [comment]
Changed nginx config to put the remoteDN and cert expiry in the headers (and stroom code has been changed to rename/format the expiry date) .

Example meta output below.

```
Content-Type:application/x-www-form-urlencoded
Environment:DEV
Feed:TEST_FEED
GUID:76f6adda-753a-4984-ab11-093f3b102d34
Host:stroom_proxy_upstream
ReceivedTime:2018-11-27T11:56:36.429Z
RemoteAddress:172.25.0.1
RemoteCertExpiry:2292-09-10T06:39:20.000Z
RemoteDN:CN=A Stroom Client,O=GCHQ,L=Cheltenham,C=UK
RemoteHost:172.25.0.1
StreamSize:29
System:MY_SYSTEM
User-Agent:curl/7.47.0
X-Forwarded-For:172.25.0.1
X-SSL-Client-V-End:Sep 10 06:39:20 2292 GMT
X-SSL-Client-V-Start:Nov 27 06:39:20 2018 GMT
X-SSL-Client-Verify:SUCCESS
X-SSL-Protocol:TLSv1.2
```
