### ISSUE TITLE
Meta Data internal statistics aren't being written to the database

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#941]
Have checked the Stat Data Source, all enabled, other stats are being written.

Missing Stats are:
Meta Data-Stream Size
Meta Data-Streams Received

**Comment by GCHQ-11** [comment]
The code based config was using the doc ref names instead of the property keys

**Comment by stroomdev10** [comment]
The stats are the wrong way round!!

Sizes contains the counts and vice versa

**Comment by GCHQ-11** [comment]
Yep, error in the fix, fixed the fix, now should be fixed fixed
