### ISSUE TITLE
Visualisations only showing 10 data points

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#945]
Seen in v6.0-beta.2

Steps to recreate:
1. Create a dashboard with a query and table that shows >10 rows.
1. Create a bar chart where the x axis should have >10 data points.

It appears that even though the table is showing >10, only 10 values are being sent to the viz when `setData()` is called.  Assume it must be some truncation in the stroom-query code as this is happening on both sql stats and lucene queries.

Needs to be recreated in a more recent 6 build as beta.2 is pretty old.

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.14
