### ISSUE TITLE
An error in the startup of the JPA entity manager was not showing in the logs

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#948]
Stroom beta.13 started up and was missing the ACTIVITY table.  The error produced by the initialisation of the JPA entity manger was not shown in the logs.  The yml config had the root level as ERROR and stroom as INFO.

Need to change root level to WARN and to ensure any exception in the initialisation of the JPA entity manager is logged, possibly by catching and logging an explicit error ourselves.

When we change root level to INFO (to track down the problem) we saw:

```
INFO ..... java.sql.DatabaseMetaData .... Table not found: ACTIVITY
WARN .....org.springframework.context.annotation.AnnotationConfigApplicationContext - Exception encountered during context initialisation ....... BeanCreationException........HibernateException ........Missing table ACTIVITY
```

**Comment by GCHQ-11** [comment]
I have added a catch of Runtime errors in the app initialisation and logged them as errors before rethrowing
