### ISSUE TITLE
Aggregated search results can be inconsistent due to over aggressive result reduction

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#98]
When asking for a low number of table results the aggregated output sometimes loses results due to the way the in memory results are trimmed.

**Comment by at055612** [comment]
Created PR https://github.com/gchq/stroom-query/pull/1 on stroom-query

**Comment by at055612** [comment]
Now we have stroom.search.storeSize for controlling the amount of results stored in the in-memory store and stroom.dashboard.defaultMaxResults for controlling the number of results that are returned to the client/user.  See #375
