### ISSUE TITLE
Ensure NGINX is configured to reach the direct dashboard UI

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#986]
In Stroom 6 you can open dashboards directly via the appropriate URL. NGINX needs to be configured to expose this URL correctly.

**Comment by GCHQ-11** [comment]
This seems to work just by using the existing /stroom reverse proxy

**Comment by GCHQ-11** [comment]
There is an issue that the auth flow redirects to the /stroom/ui, even if visiting dashboard
