### ISSUE TITLE
Document URL for directly opening dashboards

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#987]
In Stroom 6 you can open dashboards directly via the appropriate URL. The details of this URL need to be documented.

**Comment by GCHQ-11** [comment]
URL is http://<ip>:<port>/stroom/dashboard?type=Dashboard&uuid=<uuid>

**Comment by GCHQ-11** [comment]
It can already be reached via nginx it seems on https://<ip>/stroom/dashboard?type=Dashboard&uuid=<uuid>

**Comment by at055612** [comment]
Added this so far.  The permissions section needs finishing as I could not figure out all the permissions my user needed.

https://github.com/gchq/stroom-docs/blob/master/user-guide/dashboards/direct-urls.md
